import {readFile,realpath,stat} from 'node:fs/promises';import {join,dirname} from 'node:path';import {digest,isWithin} from '../tools/source';
interface Metadata {name:string;version:string;license?:unknown;dependencies?:Record<string,string>;optionalDependencies?:Record<string,string>;devDependencies?:Record<string,string>}
export async function dependencyInventory(root:string){
 root=await realpath(root);const moduleRoot=await realpath(join(root,'node_modules'));const packages:Record<string,unknown>[]=[];const relationships:{spdxElementId:string;relationshipType:string;relatedSpdxElement:string}[]=[];const seen=new Map<string,string>();const notices:string[]=[];const unavailable:string[]=[];
 const read=async(path:string)=>{if((await stat(path)).size>1024*1024)throw new Error('Package metadata limit');return JSON.parse(await readFile(path,'utf8')) as Metadata;};
 const locate=async(name:string,from:string)=>{if(!/^(@[a-z0-9_.-]+\/)?[a-z0-9_.-]+$/i.test(name))throw new Error('Invalid dependency name');let directory=from;while(isWithin(root,directory)){const candidate=join(directory,'node_modules',name);try{const canonical=await realpath(candidate);if(!isWithin(moduleRoot,canonical))throw new Error('Dependency outside installed module tree');return canonical;}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}if(directory===root)break;directory=dirname(directory);}return null;};
 const project=await read(join(root,'package.json'));const rootId='SPDXRef-Mavona';packages.push({SPDXID:rootId,name:project.name,versionInfo:project.version,downloadLocation:'NOASSERTION',filesAnalyzed:false,licenseConcluded:'NOASSERTION',licenseDeclared:typeof project.license==='string'?project.license:'NOASSERTION',copyrightText:'NOASSERTION'});
 const queue:{name:string;from:string;parent:string;optional:boolean;build:boolean}[]=[];
 const enqueue=(metadata:Metadata,from:string,parent:string,build=false)=>{for(const name of Object.keys({...metadata.dependencies,...metadata.optionalDependencies}))queue.push({name,from,parent,optional:Object.hasOwn(metadata.optionalDependencies??{},name),build});};enqueue(project,root,rootId);for(const name of Object.keys(project.devDependencies??{}))queue.push({name,from:root,parent:rootId,optional:false,build:true});
 for(let index=0;index<queue.length;index++){if(queue.length>10000||seen.size>2000)throw new Error('Dependency inventory limit');const item=queue[index]!;const path=await locate(item.name,item.from);if(!path){if(!item.optional)throw new Error('Installed dependency missing: '+item.name);unavailable.push(item.name);continue;}let id=seen.get(path);if(!id){const metadata=await read(join(path,'package.json'));if(typeof metadata.name!=='string'||typeof metadata.version!=='string')throw new Error('Invalid installed metadata');id='SPDXRef-Package-'+digest(metadata.name+'@'+metadata.version+':'+path.slice(moduleRoot.length)).slice(0,24);seen.set(path,id);packages.push({SPDXID:id,name:metadata.name,versionInfo:metadata.version,downloadLocation:'NOASSERTION',filesAnalyzed:false,licenseConcluded:'NOASSERTION',licenseDeclared:typeof metadata.license==='string'?metadata.license:'NOASSERTION',copyrightText:'NOASSERTION',sourceInfo:'Installed package.json SHA256: '+digest(await readFile(join(path,'package.json')))});enqueue(metadata,path,id,item.build);
  for(const name of ['LICENSE','LICENSE.md','LICENSE.txt','license','COPYING','NOTICE']){try{const file=join(path,name);if((await stat(file)).size>256*1024)continue;const canonical=await realpath(file);if(!isWithin(path,canonical))throw new Error('Notice outside package');notices.push(metadata.name+'@'+metadata.version+' · '+name+'\n'+await readFile(file,'utf8'));}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}}
 }relationships.push({spdxElementId:item.parent,relationshipType:item.build?'BUILD_DEPENDENCY_OF':'DEPENDS_ON',relatedSpdxElement:id});}
 // BUILD_DEPENDENCY_OF points from the build dependency to its dependent.
 for(const relation of relationships)if(relation.relationshipType==='BUILD_DEPENDENCY_OF'){const parent=relation.spdxElementId;relation.spdxElementId=relation.relatedSpdxElement;relation.relatedSpdxElement=parent;}
 return {project,packages,relationships,notices: notices.join('\n\n---\n\n'),unavailableOptional:[...new Set(unavailable)].sort()};
}
