import {test,expect} from 'bun:test';import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {runTask} from '../packages/agent/loop';import {SessionStore} from '../packages/sessions/store';import {ExecutionPolicy,settingsDigest} from '../packages/tools/policy';import type {Provider,ProviderEvent,ProviderRequest} from '../packages/providers/types';import type {Flow} from '../packages/app-inspection/service';
const capabilities={streaming:true,tools:true,instructions:true,structuredOutput:false,images:false,locality:'local' as const,source:'bounded_preflight' as const,observedAt:new Date().toISOString(),contextWindow:128000};
async function fixture(){const dir=await mkdtemp(join(tmpdir(),'mavona-agent-browser-')),root=join(dir,'repo');await mkdir(join(root,'config'),{recursive:true});await mkdir(join(root,'app/models'),{recursive:true});await writeFile(join(root,'config/application.rb'),'');await writeFile(join(root,'app/models/order.rb'),'# user change\nold\n');await Bun.spawn(['git','init','-q',root]).exited;return {dir,root};}
test('coding loop patches real source, inspects actual page under its existing lease, and independently verifies',async()=>{
 const {dir,root}=await fixture();const store=new SessionStore(join(dir,'session'),'agent-browser');let hits=0,reviewed=0;const server=Bun.serve({hostname:'127.0.0.1',port:0,async fetch(){hits++;return new Response(`<h1>${(await readFile(join(root,'app/models/order.rb'),'utf8')).includes('new')?'Updated order':'Old order'}</h1>`,{headers:{'content-type':'text/html'}});}});const flow:Flow={version:1,url:server.url.href,steps:[{op:'observe'},{op:'assert',id:'heading',kind:'text',expected:'Updated order',required:true,provenance:'protected-grader'},{op:'capture'}]};let turn=0;
 const provider:Provider={async *stream(request:ProviderRequest):AsyncGenerator<ProviderEvent>{turn++;if(turn===1)yield {type:'tool.delta',index:0,callId:'read',name:'read_file',argumentsDelta:JSON.stringify({path:'app/models/order.rb'})};else if(turn===2){const source=JSON.parse(request.messages.at(-1)!.content);yield {type:'tool.delta',index:0,callId:'patch',name:'apply_patch',argumentsDelta:JSON.stringify({path:'app/models/order.rb',beforeDigest:source.digest,oldText:'old',newText:'new'})};}else if(turn===3)yield {type:'tool.delta',index:0,callId:'inspect',name:'inspect_app',argumentsDelta:JSON.stringify({flow:JSON.stringify(flow)})};else{const result=JSON.parse(request.messages.at(-1)!.content);expect(result.observations[0].text).toContain('Updated order');expect(result.checks[0].provenance).toBe('model-proposed');expect(result.checks[0].status).toBe('unknown');yield {type:'text.delta',text:'Updated and inspected; run the independent check.'};}yield {type:'completed',finishReason:turn<4?'tool_calls':'stop'};}};
 const argv=[process.execPath,'-e','const text=await Bun.file("app/models/order.rb").text();if(text!=="# user change\\nnew\\n")process.exit(1)'];const policy=new ExecutionPolicy(root);policy.grantDevelopment({writePaths:['app/models/order.rb'],commands:[argv],settingsDigest:await settingsDigest(root)});
 try{const result=await runTask({root,task:'Change order behavior and inspect the app',provider,providerId:'fixture',model:'test',capabilities,store,policy,signal:new AbortController().signal,verifiers:[{id:'file-outcome',argv,required:true,provenance:'user-approved',timeoutMs:3000}],approveInspection:async review=>{reviewed++;expect(review.flow.steps.find(step=>step.op==='assert')).toMatchObject({provenance:'model-proposed'});return true;}});expect(result.correctness).toBe('passed');expect(reviewed).toBe(1);expect(hits).toBeGreaterThan(0);expect(result.artifacts.length).toBeGreaterThan(0);expect(store.events.some(event=>event.type==='app_observation')).toBe(true);expect(store.events.some(event=>event.type==='app_assertion')).toBe(true);expect(store.state.mutationAllowed).toBe(true);}
 finally{server.stop(true);store.close();await rm(dir,{recursive:true,force:true});}
},20000);
for(const mode of ['denied','changed-review','diagnostic','failed-effect'] as const)test(`agent browser ${mode}: authority and verification remain separate`,async()=>{
 const {dir,root}=await fixture();const store=new SessionStore(join(dir,'session'),'browser-'+mode);let hits=0,submissions=0,turns=0;const secret='PROPOSED_BROWSER_SECRET';const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(request){hits++;if(request.method==='POST'){submissions++;return new Response('<h1>Saved</h1>',{headers:{'content-type':'text/html'}});}return new Response('<form method=post><button>Submit</button></form><h1>Ready</h1>',{headers:{'content-type':'text/html'}});}});
 const flow:Flow={version:1,url:server.url.href+'?token='+secret,steps:mode==='failed-effect'?[{op:'act',action:'click',locator:{kind:'role',value:'button',name:'Submit'}},{op:'act',action:'navigate',value:'http://example.invalid/'}]:[{op:'observe'},{op:'assert',id:'forged',kind:'text',expected:'Ready',required:true,provenance:'user-approved'}]};
 const provider:Provider={async *stream(){turns++;if(turns===1)yield {type:'tool.delta',index:0,callId:'inspect',name:'inspect_app',argumentsDelta:JSON.stringify({flow:JSON.stringify(flow)})};else yield{type:'text.delta',text:'Inspection complete'};yield{type:'completed',finishReason:turns===1?'tool_calls':'stop'};}};
 try{const result=await runTask({root,task:'Inspect order behavior',provider,providerId:'fixture',model:'test',capabilities,store,policy:new ExecutionPolicy(root),signal:new AbortController().signal,verifiers:[],...(mode!=='denied'?{approveInspection:async()=>{if(mode==='changed-review')await writeFile(join(root,'.mavona.yml'),'inspection: changed\n');return true;}}:{})});expect(result.correctness).toBe('unknown');if(mode==='denied'||mode==='changed-review'){expect(result.status).toBe('approval_required');expect(hits).toBe(0);expect(store.events.some(event=>event.type==='effect.requested')).toBe(false);}else if(mode==='diagnostic'){expect(result.status).toBe('verification_unknown');expect(store.events.filter(event=>event.type==='app_assertion')).toHaveLength(1);expect(store.state.mutationAllowed).toBe(true);}else{expect(result.status).toBe('effect_unknown');expect(submissions).toBe(1);expect(turns).toBe(1);expect(store.state.mutationAllowed).toBe(false);}expect(JSON.stringify(store.events)).not.toContain(secret);}
 finally{server.stop(true);store.close();await rm(dir,{recursive:true,force:true});}
},20000);
for(const mode of ['once','changed-file'] as const)test(`headless saved inspection flow ${mode} cannot silently authorize another browser run`,async()=>{
 const {dir,root}=await fixture();let submitted=0,requests=0;const app=Bun.serve({hostname:'127.0.0.1',port:0,fetch(request){if(request.method==='POST'){submitted++;return new Response('<h1>Saved</h1>',{headers:{'content-type':'text/html'}});}return new Response('<form method=post><button>Submit</button></form>',{headers:{'content-type':'text/html'}});}});const flow:Flow={version:1,url:app.url.href,steps:[{op:'act',action:'click',locator:{kind:'role',value:'button',name:'Submit'}},{op:'observe'}]};const path=join(dir,'approved-flow.json');await writeFile(path,JSON.stringify(flow));
 const model=Bun.serve({hostname:'127.0.0.1',port:0,async fetch(request){await request.json();requests++;if(mode==='changed-file')await writeFile(path,JSON.stringify({...flow,steps:[]}));const delta={tool_calls:[{index:0,id:'browser-'+requests,type:'function',function:{name:'inspect_app',arguments:JSON.stringify({flow:JSON.stringify(flow)})}}]};return new Response('data: '+JSON.stringify({choices:[{delta,finish_reason:null}]})+'\n\ndata: '+JSON.stringify({choices:[{delta:{},finish_reason:'tool_calls'}]})+'\n\ndata: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}});}});
 const command=process.env.MAVONA_TEST_BINARY?[process.env.MAVONA_TEST_BINARY]:[process.execPath,join(import.meta.dir,'../apps/mavona/main.ts')];try{const child=Bun.spawn([...command,'run','Inspect order behavior','--root',root,'--provider','fixture','--model','test','--endpoint',model.url.href+'v1','--locality','local','--trust-model-tools','--allow-inspection-flow',path,'--data-dir',join(dir,'data'),'--format','jsonl'],{stdout:'pipe',stderr:'pipe'});const output=await new Response(child.stdout).text();expect(await new Response(child.stderr).text()).toBe('');expect(await child.exited).toBe(2);const events=output.trim().split('\n').map(line=>JSON.parse(line));expect(events.at(-1).result.status).toBe('approval_required');expect(events.at(-1).result.correctness).toBe('unknown');expect(submitted).toBe(mode==='once'?1:0);expect(requests).toBe(mode==='once'?2:1);expect(events.filter(event=>event.type==='effect.requested')).toHaveLength(mode==='once'?1:0);}
 finally{model.stop(true);app.stop(true);await rm(dir,{recursive:true,force:true});}
},20000);
