import {test,expect} from 'bun:test';import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {runTask} from '../packages/agent/loop';import {ExecutionPolicy,settingsDigest} from '../packages/tools/policy';import {SessionStore} from '../packages/sessions/store';import type {Provider,ProviderEvent,ProviderRequest} from '../packages/providers/types';
test('large Rails source survives deterministic context compaction, ranged retrieval and an independently verified patch',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'mavona-context-')),root=join(dir,'repo');await mkdir(join(root,'config'),{recursive:true});await mkdir(join(root,'app/models'),{recursive:true});await writeFile(join(root,'config/application.rb'),'');await writeFile(join(root,'AGENTS.md'),'Preserve the PRIOR_MARKER and use existing conventions.');const lines=['# PRIOR_MARKER',...Array.from({length:1500},(_,i)=>`# order context row ${i} ${'x'.repeat(45)}`),'broken',''];await writeFile(join(root,'app/models/order.rb'),lines.join('\n'));await Bun.spawn(['git','init','-q',root]).exited;
 const store=new SessionStore(join(dir,'session'),'context');const argv=[process.execPath,'-e','const text=await Bun.file("app/models/order.rb").text();if(!text.includes("PRIOR_MARKER")||!text.includes("fixed"))process.exit(1)'];const policy=new ExecutionPolicy(root);policy.grantDevelopment({commands:[argv],writePaths:['app/models/order.rb'],settingsDigest:await settingsDigest(root)});let calls=0;let lastDigest='';
 const provider:Provider={async *stream(request:ProviderRequest):AsyncGenerator<ProviderEvent>{calls++;const serialized=JSON.stringify(request.messages);expect(serialized).toContain('Preserve the PRIOR_MARKER');expect(serialized).toContain('Fix order behavior while preserving prior work');for(let i=0;i<request.messages.length;i++){const message=request.messages[i]!;if(message.role==='tool')expect(request.messages.slice(0,i).some(prior=>prior.tool_calls?.some(call=>call.id===message.tool_call_id))).toBe(true);}
 if(calls<=3)yield{type:'tool.delta',index:0,callId:'read-'+calls,name:'read_file',argumentsDelta:JSON.stringify({path:'app/models/order.rb',startLine:1,endLine:100})};else if(calls===4)yield{type:'tool.delta',index:0,callId:'target',name:'read_file',argumentsDelta:JSON.stringify({path:'app/models/order.rb',startLine:1498,endLine:1503})};else if(calls===5){const source=JSON.parse(request.messages.at(-1)!.content);expect(source.startLine).toBe(1498);expect(source.text).toContain('broken');lastDigest=source.digest;yield{type:'tool.delta',index:0,callId:'patch',name:'apply_patch',argumentsDelta:JSON.stringify({path:'app/models/order.rb',beforeDigest:lastDigest,oldText:'broken',newText:'fixed'})};}else yield{type:'text.delta',text:'Ready for verification.'};yield{type:'completed',finishReason:calls<=5?'tool_calls':'stop'};}};
 try{const result=await runTask({root,task:'Fix order behavior while preserving prior work',provider,providerId:'fixture',model:'test',capabilities:{streaming:true,tools:true,instructions:true,structuredOutput:false,images:false,locality:'local',source:'bounded_preflight',observedAt:new Date().toISOString(),contextWindow:18000},store,policy,signal:new AbortController().signal,verifiers:[{id:'independent',argv,required:true,provenance:'user-approved',timeoutMs:3000}]});expect(result.correctness).toBe('passed');expect(calls).toBe(6);expect(store.events.some(event=>event.type==='context.compacted')).toBe(true);expect(await readFile(join(root,'app/models/order.rb'),'utf8')).toContain('# PRIOR_MARKER');expect(store.events.filter(event=>event.type==='tool.completed')).toHaveLength(5);}
 finally{store.close();await rm(dir,{recursive:true,force:true});}
},15000);

import {compactContext,readSourceRange,readResultRange} from '../packages/agent/context';
import type {ProviderMessage} from '../packages/providers/types';
test('compaction retains constraints and canonical references without persisting raw browser arguments',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'mavona-compact-'));const store=new SessionStore(dir,'compact');try{
 store.append('task.started',{taskId:'task',text:'preserve edits'});store.append('tool.completed',{callId:'browser',result:JSON.stringify({state:'unknown'})});
 const messages:ProviderMessage[]=[{role:'system',content:'policy'},{role:'user',content:JSON.stringify({task:'preserve edits',instructions:['exact constraint'],selectedContext:['pinned source'],sources:[{path:'large.rb',digest:'full',text:'x'.repeat(20000)}]})},{role:'assistant',content:'',tool_calls:[{id:'browser',type:'function',function:{name:'inspect_app',arguments:'secret-browser-value'}}]},{role:'tool',tool_call_id:'browser',content:'{"state":"unknown"}'}];
 const result=compactContext(messages,1800,store.events,'task',[{id:'test',state:'unknown',fresh:false}],'repo');expect(result).not.toBeNull();expect(JSON.stringify(result!.snapshot)).not.toContain('secret-browser-value');expect(JSON.stringify(result!.messages)).toContain('exact constraint');expect(JSON.stringify(result!.messages)).toContain('pinned source');expect(result!.snapshot.results[0]!.callId).toBe('browser');expect(result!.bytes).toBeLessThanOrEqual(1800);expect(store.events).toHaveLength(2);
 const again=compactContext(result!.messages,1800,store.events,'task',[],'repo');expect(again!.messages.filter(m=>m.content.startsWith('{"kind":"deterministic_context_checkpoint"'))).toHaveLength(1);
 expect(compactContext(messages,20,store.events,'task',[])).toBeNull();
 }finally{store.close();await rm(dir,{recursive:true,force:true});}
});
test('ranged source retains full digest and bounds whole Unicode lines',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'mavona-range-'));try{await writeFile(join(dir,'large.rb'),'first\n'+'😀'.repeat(5000)+'\nlast');const first=await readSourceRange(dir,'large.rb',1,3);const last=await readSourceRange(dir,'large.rb',3,3);expect(first.text).toBe('first');expect(first.truncated).toBe(true);expect(last.text).toBe('last');expect(first.digest).toBe(last.digest);expect(last.totalLines).toBe(3);await expect(readSourceRange(dir,'large.rb',1,401)).rejects.toThrow('400 lines');}finally{await rm(dir,{recursive:true,force:true});}
});
test('canonical result retrieval is task scoped, bounded and does not split Unicode',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'mavona-result-'));const store=new SessionStore(dir,'result');try{store.append('task.started',{taskId:'one',text:'one'});store.append('tool.completed',{callId:'old',result:'old'});store.append('task.started',{taskId:'two',text:'two'});const value='x'.repeat(2047)+'😀'+'tail';store.append('tool.completed',{callId:'new',result:value});expect(()=>readResultRange(store.events,'two','old')).toThrow();expect(()=>readResultRange(store.events,'one','new')).toThrow();const first=readResultRange(store.events,'two','new');expect(first.text).toHaveLength(2047);expect(readResultRange(store.events,'two','new',first.nextOffset!).text).toBe('😀tail');expect(()=>readResultRange(store.events,'two','new',2048)).toThrow();}finally{store.close();await rm(dir,{recursive:true,force:true});}
});
