import {test,expect} from 'bun:test';import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {InspectionService,approveFlow,type Flow} from '../packages/app-inspection/service';
for(const mode of ['once','mismatch','invalid','changed-settings','absent'] as const)test(`headless selected image grant ${mode} uses exact bytes and retains unknown correctness`,async()=>{
 const dir=await mkdtemp(join(tmpdir(),'mavona-image-cli-')),root=join(dir,'repo');await mkdir(join(root,'config'),{recursive:true});await mkdir(join(root,'app/models'),{recursive:true});await writeFile(join(root,'config/application.rb'),'');await writeFile(join(root,'app/models/order.rb'),'class Order; end');await Bun.spawn(['git','init','-q',root]).exited;
 const app=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>new Response('<style>html{background:rgb(10,20,30)}</style>',{headers:{'content-type':'text/html'}})});const flow:Flow={version:1,url:app.url.href,steps:[{op:'capture'},{op:'capture'}]};const service=new InspectionService();const report=await service.run(flow,approveFlow(flow,root,'explicit-user'),{checkout:root,artifactRoot:dir,artifactDirectory:join(dir,'baseline')});expect(report.artifacts).toHaveLength(2);expect(report.artifacts[0]!.sha256).toBe(report.artifacts[1]!.sha256);const path=join(dir,'flow.json');await writeFile(path,JSON.stringify(flow));let calls=0;let ids:string[]=[];const imageCounts:number[]=[];
 const model=Bun.serve({hostname:'127.0.0.1',port:0,async fetch(r){const body:any=await r.json();calls++;if(mode==='changed-settings'&&calls===2)await writeFile(join(root,'.mavona.yml'),'inspection: changed\n');imageCounts.push(body.messages.flatMap((m:any)=>Array.isArray(m.content)?m.content:[]).filter((b:any)=>b.type==='image_url').length);if(calls===2)ids=JSON.parse(body.messages.at(-1).content).artifacts.map((a:any)=>a.id);const tool=calls===1?{name:'inspect_app',arguments:JSON.stringify({flow:JSON.stringify(flow)})}:calls<=3?{name:'select_inspection_images',arguments:JSON.stringify({artifactIds:[ids[calls-2]]})}:undefined;const delta=tool?{tool_calls:[{index:0,id:'tool-'+calls,type:'function',function:tool}]}:{content:'Visual evidence only.'};return new Response('data: '+JSON.stringify({choices:[{delta,finish_reason:null}]})+'\n\ndata: '+JSON.stringify({choices:[{delta:{},finish_reason:tool?'tool_calls':'stop'}]})+'\n\ndata: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}});}});
 const command=process.env.MAVONA_TEST_BINARY?[process.env.MAVONA_TEST_BINARY]:[process.execPath,join(import.meta.dir,'../apps/mavona/main.ts')];
 try{const child=Bun.spawn([...command,'run','Inspect order behavior','--root',root,'--provider','fixture','--model','vision-test','--endpoint',model.url.href+'v1','--locality','local','--trust-model-tools','--allow-inspection-flow',path,...(mode==='absent'?[]:['--allow-image-sha256',JSON.stringify([mode==='once'||mode==='changed-settings'?report.artifacts[0]!.sha256:mode==='mismatch'?'0'.repeat(64):'invalid'])]),'--data-dir',join(dir,'data'),'--format','jsonl'],{stdout:'pipe',stderr:'pipe'});const [stdout,stderr,code]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);if(mode==='invalid'){expect(code).toBe(5);expect(calls).toBe(0);}else{expect(stderr).toBe('');expect(code).toBe(4);const events=stdout.trim().split('\n').map(line=>JSON.parse(line));expect(events.at(-1).result.correctness).toBe('unknown');expect(calls).toBe(4);expect(imageCounts).toEqual(mode==='once'?[0,0,1,1]:[0,0,0,0]);const decisions=events.filter(e=>e.type==='approval.resolved').map(e=>e.payload.decision);expect(decisions).toEqual(mode==='once'?['approved','approved','denied']:mode==='absent'?['approved']:['approved','denied','denied']);expect(stdout).not.toContain('base64');}}
 finally{await service.stop(false);app.stop(true);model.stop(true);await rm(dir,{recursive:true,force:true});}
},20000);
