import {expect,test} from 'bun:test';
import {mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {editorHandoff} from '../packages/tools/editor';
import {ExecutionPolicy,prepareAction} from '../packages/tools/policy';
import {ToolRuntime} from '../packages/tools/runtime';
import {readSource} from '../packages/tools/source';

test('scenario C: editor drift rejects a prepared patch, preserves unrelated edits and permits a fresh recheck',async()=>{const root=await mkdtemp(join(tmpdir(),'mavona-scenario-c-')),order=join(root,'order.rb'),notes=join(root,'notes.txt');await writeFile(order,'class Order\n  STATE = :old\nend\n');await writeFile(notes,'committed note\n');await Bun.spawn(['git','init','-q',root]).exited;await Bun.spawn(['git','-C',root,'add','.']).exited;await Bun.spawn(['git','-C',root,'-c','user.name=Mavona Test','-c','user.email=test@mavona.invalid','commit','-qm','base']).exited;await writeFile(notes,'committed note\npre-existing user edit\n');const policy=new ExecutionPolicy(root),runtime=new ToolRuntime(root,policy),source=await readSource(root,'order.rb'),proposal={tool:'apply_patch' as const,path:'order.rb',beforeDigest:source.digest,oldText:':old',newText:':agent'},prepared=await prepareAction(root,proposal);let suspended=false,resumed=false;try{const handoff=await editorHandoff({root,path:'order.rb',line:2,adapter:{argv:[process.execPath,'-e','await Bun.write(process.argv[1],"class Order\\n  STATE = :editor\\nend\\n")','{path}'],terminal:true},policy,signal:new AbortController().signal,approve:async()=>true,suspend:()=>{suspended=true;},resume:()=>{resumed=true;}});expect(suspended).toBe(true);expect(resumed).toBe(true);expect(handoff.changed.paths).toContain('order.rb');expect(handoff.changed.preexistingPaths).toContain('notes.txt');policy.approveOnce(prepared);await expect(runtime.execute(proposal,new AbortController().signal)).rejects.toThrow('stale');expect(await readFile(order,'utf8')).toContain(':editor');expect(await readFile(notes,'utf8')).toContain('pre-existing user edit');const current=await readSource(root,'order.rb'),fresh={...proposal,beforeDigest:current.digest,oldText:':editor'};policy.approveOnce(await prepareAction(root,fresh));expect((await runtime.execute(fresh,new AbortController().signal)).state).toBe('passed');const check=Bun.spawn([process.execPath,'-e','const a=await Bun.file("order.rb").text(),b=await Bun.file("notes.txt").text();if(!a.includes(":agent")||!b.includes("pre-existing user edit"))process.exit(1)'],{cwd:root});expect(await check.exited).toBe(0);}finally{await rm(root,{recursive:true,force:true});}});
