import {expect,test} from 'bun:test';
import {cp,mkdir,mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {runTask} from '../packages/agent/loop';
import {SessionStore} from '../packages/sessions/store';
import {ExecutionPolicy,settingsDigest} from '../packages/tools/policy';
import type {Provider,ProviderEvent,ProviderRequest} from '../packages/providers/types';
const capabilities={streaming:true,tools:true,instructions:true,structuredOutput:false,images:false,locality:'local' as const,source:'bounded_preflight' as const,observedAt:new Date().toISOString(),contextWindow:64000};

test('scenario B: a failing namespaced Rails test supplies repair evidence and passes one focused rerun',async()=>{const directory=await mkdtemp(join(tmpdir(),'mavona-scenario-b-')),root=join(directory,'rails'),modelPath='app/models/admin/order.rb',testPath='test/models/admin/order_test.rb';await cp(resolve(import.meta.dir,'../fixtures/rails-dogfood'),root,{recursive:true});await mkdir(join(root,'app/models/admin'),{recursive:true});await mkdir(join(root,'test/models/admin'),{recursive:true});await writeFile(join(root,modelPath),'module Admin\n  class Order\n    def self.label = "broken"\n  end\nend\n');await writeFile(join(root,testPath),'require "test_helper"\nclass AdminOrderTest < ActiveSupport::TestCase\n  test "label" do\n    assert_equal "ready", Admin::Order.label\n  end\nend\n');await Bun.spawn(['git','init','-q',root]).exited;const store=new SessionStore(join(directory,'session'),'scenario-b');store.append('session.opened',{repository:root});const argv=['ruby','bin/rails','test',testPath],policy=new ExecutionPolicy(root);policy.grantDevelopment({commands:[argv],writePaths:[modelPath],settingsDigest:await settingsDigest(root)});let calls=0;const provider:Provider={async *stream(request:ProviderRequest):AsyncGenerator<ProviderEvent>{calls++;if(calls===1)yield{type:'text.delta',text:'Run the focused failing test.'};else if(calls===2){const failure=JSON.parse(request.messages.at(-1)!.content);expect(failure.kind).toBe('objective_verification_failure');const evidence=JSON.stringify(failure.checks[0].result);expect(evidence).toContain('AdminOrderTest');expect(evidence).toContain('test/models/admin/order_test.rb');yield{type:'tool.delta',index:0,callId:'read-admin-order',name:'read_file',argumentsDelta:JSON.stringify({path:modelPath})};}else if(calls===3){const source=JSON.parse(request.messages.at(-1)!.content);yield{type:'tool.delta',index:0,callId:'fix-admin-order',name:'apply_patch',argumentsDelta:JSON.stringify({path:modelPath,beforeDigest:source.digest,oldText:'"broken"',newText:'"ready"'})};}else yield{type:'text.delta',text:'The namespaced Rails behavior is repaired; rerun the same focused test.'};yield{type:'completed',finishReason:calls===2||calls===3?'tool_calls':'stop'};}};try{const result=await runTask({root,task:'Repair the failing Admin::Order test',provider,providerId:'deterministic-local',model:'scenario-b',capabilities,store,policy,signal:new AbortController().signal,verifiers:[{id:'admin-order-focused',argv,required:true,provenance:'user-approved',timeoutMs:60000}],repairAttempts:1});expect(result.status).toBe('verified');expect(result.correctness).toBe('passed');expect(calls).toBe(4);expect(await readFile(join(root,modelPath),'utf8')).toContain('"ready"');expect(store.events.filter(event=>event.type==='task.repair.started')).toHaveLength(1);expect(store.events.filter(event=>event.type==='verification.completed')).toHaveLength(2);}finally{store.close();await rm(directory,{recursive:true,force:true});}},60000);
