import {test,expect} from 'bun:test';import {mkdtemp,mkdir,writeFile,readFile,rm,chmod,copyFile} from 'node:fs/promises';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {digest} from '../packages/tools/source';
test('local installer validates digest, refuses overwrite and removes only its unchanged binary',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'mavona-install-')),artifact=join(dir,'artifact'),prefix=join(dir,'prefix');await mkdir(artifact);const executable=process.env.MAVONA_TEST_BINARY??process.execPath;await copyFile(executable,join(artifact,'mavona'));await chmod(join(artifact,'mavona'),0o755);await writeFile(join(artifact,'BINARY_SHA256'),digest(await readFile(executable))+'\n');await writeFile(join(artifact,'TARGET'),process.platform+'-'+process.arch+'\n');
 const script=resolve(import.meta.dir,'../distribution/install.sh');const uninstall=resolve(import.meta.dir,'../distribution/uninstall.sh');const run=async(argv:string[])=>{const child=Bun.spawn(['/bin/sh',...argv],{stdout:'pipe',stderr:'pipe'});return {code:await child.exited,out:await new Response(child.stdout).text(),error:await new Response(child.stderr).text()};};
 try{expect((await run([script,artifact,prefix])).code).toBe(0);const child=Bun.spawn([join(prefix,'bin/mavona'),'--version'],{env:{PATH:'/usr/bin:/bin'},stdout:'pipe',stderr:'pipe'});expect(await child.exited).toBe(0);expect((await run([script,artifact,prefix])).code).not.toBe(0);await writeFile(join(prefix,'bin/mavona'),'user replacement');expect((await run([uninstall,prefix])).code).not.toBe(0);expect(await readFile(join(prefix,'bin/mavona'),'utf8')).toBe('user replacement');await copyFile(executable,join(prefix,'bin/mavona'));expect((await run([uninstall,prefix])).code).toBe(0);expect(await Bun.file(join(prefix,'bin/mavona')).exists()).toBe(false);await writeFile(join(artifact,'BINARY_SHA256'),'0'.repeat(64)+'\n');expect((await run([script,artifact,prefix])).code).not.toBe(0);}finally{await rm(dir,{recursive:true,force:true});}
},30000);
import {dependencyInventory} from '../packages/distribution/inventory';
test('dependency inventory resolves installed metadata without executing packages and records missing optional targets',async()=>{
 const root=await mkdtemp(join(tmpdir(),'mavona-inventory-'));try{await mkdir(join(root,'node_modules/example'),{recursive:true});await writeFile(join(root,'package.json'),JSON.stringify({name:'fixture',version:'1.0.0',license:'MIT',dependencies:{example:'1.0.0'},optionalDependencies:{absent:'1.0.0'}}));await writeFile(join(root,'node_modules/example/package.json'),JSON.stringify({name:'example',version:'1.0.0',license:'ISC',scripts:{postinstall:'touch PWNED'}}));await writeFile(join(root,'node_modules/example/LICENSE'),'Example license fixture');const inventory=await dependencyInventory(root);expect(inventory.packages).toHaveLength(2);expect(inventory.unavailableOptional).toEqual(['absent']);expect(inventory.notices).toContain('Example license fixture');expect(inventory.relationships[0]?.relationshipType).toBe('DEPENDS_ON');expect(await Bun.file(join(root,'PWNED')).exists()).toBe(false);}finally{await rm(root,{recursive:true,force:true});}
});
import {requireCurrentBuild} from '../packages/distribution/build-inputs';
test('packaging refuses stale binary bytes, source input, target or toolchain provenance',()=>{
 const inputs={sourceCommit:'commit',sourceDirty:false,statusDigest:'status',trackedDiffDigest:'diff',authoredInputDigest:'source',lockfileDigest:'lock',inputScope:'fixture'};const record={schemaVersion:1,...inputs,target:process.platform+'-'+process.arch,bun:Bun.version,binarySha256:'binary',builtAt:new Date().toISOString()};expect(requireCurrentBuild(record,inputs,record.target,'binary')).toBe(record);for(const change of [{authoredInputDigest:'changed'},{binarySha256:'changed'},{target:'other'},{bun:'old'}])expect(()=>requireCurrentBuild({...record,...change},inputs,record.target,'binary')).toThrow('stale');
});
import {symlink} from 'node:fs/promises';
test('installer refuses wrong-host artifacts and symlink destinations without touching outside files',async()=>{
 const root=await mkdtemp(join(tmpdir(),'mavona-install-boundary-')),artifact=join(root,'artifact'),prefix=join(root,'prefix');await mkdir(artifact);await writeFile(join(artifact,'mavona'),'fixture');await writeFile(join(artifact,'BINARY_SHA256'),digest('fixture')+'\n');await writeFile(join(artifact,'TARGET'),'unsupported-target\n');const run=async()=>{const child=Bun.spawn(['/bin/sh',resolve(import.meta.dir,'../distribution/install.sh'),artifact,prefix],{stdout:'ignore',stderr:'ignore'});return child.exited;};try{expect(await run()).not.toBe(0);await writeFile(join(artifact,'TARGET'),process.platform+'-'+process.arch+'\n');await mkdir(prefix);await mkdir(join(root,'outside'));await writeFile(join(root,'outside/mavona'),'user bytes');await symlink(join(root,'outside'),join(prefix,'bin'));expect(await run()).not.toBe(0);expect(await readFile(join(root,'outside/mavona'),'utf8')).toBe('user bytes');}finally{await rm(root,{recursive:true,force:true});}
});
