import {test,expect} from 'bun:test';import {mkdtemp,mkdir,rm,readFile,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {SessionStore} from '../packages/sessions/store';import {runInspection} from '../packages/agent/inspection';import {InspectionService,approveFlow,type Flow} from '../packages/app-inspection/service';
import {compareRecordedCaptures,startComparisonViewer} from '../packages/app-inspection/comparison';
test('actual recorded captures expose raw layout differences while missing comparability and baseline stay unknown',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'mavona-comparison-')),root=join(directory,'repo');await mkdir(root);await Bun.spawn(['git','init','-q',root]).exited;const store=new SessionStore(join(directory,'data/sessions/comparison'),'comparison');store.append('session.opened',{repository:root});let shifted=false,hits=0;const app=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>{hits++;return new Response('<h1 style="margin-left:'+(shifted?100:0)+'px">Order layout</h1>',{headers:{'content-type':'text/html'}});}});let viewer:ReturnType<typeof startComparisonViewer>|undefined;const flow:Flow={version:1,url:app.url.href,viewport:{width:640,height:480},steps:[{op:'capture'}]};
 try{const first=await runInspection({root,flow,store,signal:new AbortController().signal});shifted=true;const second=await runInspection({root,flow,store,signal:new AbortController().signal});const before=first.report.artifacts[0]!,after=second.report.artifacts[0]!,count=hits,events=store.events.length;const pair=await compareRecordedCaptures(store.directory,store.events,before.id,after.id);expect(pair.summary.status).toBe('unknown');expect(pair.summary.comparability).toBe('unknown');expect(pair.summary.changedPixels).toBeGreaterThan(0);expect(pair.summary.before.sha256).toBe(before.sha256);expect(store.events).toHaveLength(events);expect(hits).toBe(count);viewer=startComparisonViewer(pair);const html=await (await fetch(viewer.url)).text();expect(html).toContain('Overlay captures');expect(html).toContain(before.id);expect(html).toContain('Visual comparison: unknown');expect(Buffer.from(await (await fetch(new URL('before.png',viewer.url))).arrayBuffer())).toEqual(await readFile(join(first.reportPath,'..',before.path)));expect((await fetch(new URL('events.jsonl',viewer.url))).status).toBe(404);const browserFlow:Flow={version:1,url:viewer.url,steps:[{op:'assert',id:'heading',kind:'text',expected:'Visual comparison: unknown',required:true,provenance:'user-approved'},{op:'act',action:'check',locator:{kind:'label',value:'Overlay captures at 50%'}},{op:'assert',id:'overlay',kind:'visible',locator:{kind:'role',value:'img',name:'Before overlay'},required:true,provenance:'user-approved'},{op:'assert',id:'pair-hidden',kind:'hidden',locator:{kind:'role',value:'img',name:'Before'},required:true,provenance:'user-approved'}]};const viewed=await new InspectionService().run(browserFlow,approveFlow(browserFlow,root,'explicit-user'),{checkout:root,artifactRoot:directory,artifactDirectory:join(directory,'viewer-check')});expect(viewed.status).toBe('passed');expect(hits).toBe(count);
 const {TuiController}=await import('../packages/tui/controller');const controller=new TuiController(root,store,()=>{});try{controller.draft('comparison draft');await controller.command('/app compare');await controller.pickFile('capture:'+before.id);expect(controller.model.picker?.title).toContain('after');await controller.pickFile('capture:'+after.id);expect(controller.model.inspection?.text).toContain('Local comparison:');expect(controller.model.inspection?.text).toContain('"comparability": "unknown"');expect(controller.model.draft).toBe('comparison draft');await controller.command('/app stop');}finally{controller.cancel();}
 await expect(compareRecordedCaptures(store.directory,store.events,before.id,before.id)).rejects.toThrow();await expect(compareRecordedCaptures(store.directory,store.events,'missing',after.id)).rejects.toThrow();
 const command=process.env.MAVONA_TEST_BINARY?[process.env.MAVONA_TEST_BINARY]:[process.execPath,join(import.meta.dir,'../apps/mavona/main.ts')];const log=await readFile(join(store.directory,'events.jsonl'));const child=Bun.spawn([...command,'app','compare','--session','comparison','--data-dir',join(directory,'data'),'--before',before.id,'--after',after.id,'--summary'],{stdout:'pipe',stderr:'pipe'});const [output,error,code]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);expect(code).toBe(4);expect(error).toBe('');expect(JSON.parse(output)).toMatchObject({status:'unknown',comparability:'unknown',before:{id:before.id},after:{id:after.id}});expect(await readFile(join(store.directory,'events.jsonl'))).toEqual(log);expect(hits).toBe(count);
 await writeFile(join(second.reportPath,'..',after.path),'changed');await expect(compareRecordedCaptures(store.directory,store.events,before.id,after.id)).rejects.toThrow();}
 finally{viewer?.stop();app.stop(true);store.close();await rm(directory,{recursive:true,force:true});}
},20000);
