import {test,expect} from 'bun:test';import {mkdtemp,mkdir,writeFile,readFile,rm,access} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {runInspection} from '../packages/agent/inspection';import {SessionStore} from '../packages/sessions/store';import {prepareReportExport,exportReport} from '../packages/app-inspection/export';import type {Flow} from '../packages/app-inspection/service';
test('explicit report export previews exact files, preserves existing output and produces a portable archive without authentication data',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'mavona-export-')),root=join(dir,'repo');await mkdir(root);await Bun.spawn(['git','init','-q',root]).exited;const store=new SessionStore(join(dir,'session'),'export');const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>new Response('<h1>Exported order</h1><input type=password value=PASSWORD_CANARY>',{headers:{'content-type':'text/html'}})});const flow:Flow={version:1,url:server.url.href,steps:[{op:'observe'},{op:'capture'}]};const destination=join(dir,'evidence.tar.gz');
 try{const result=await runInspection({root,flow,store,signal:new AbortController().signal});const review=await prepareReportExport(store.directory,store.events,result.report.id,destination);expect(review.files.some(f=>f.name==='report.html')).toBe(true);expect(review.files.some(f=>f.name==='report.json')).toBe(false);expect(review.files.find(f=>f.name.endsWith('.png'))?.redaction).toBe('masked');await expect(access(destination)).rejects.toThrow();await expect(exportReport(store,result.report.id,destination,'wrong-review',new AbortController().signal)).rejects.toThrow();await expect(access(destination)).rejects.toThrow();const originalReport=await readFile(result.reportPath);await writeFile(result.reportPath,'changed');await expect(exportReport(store,result.report.id,destination,review.id,new AbortController().signal)).rejects.toThrow();await expect(access(destination)).rejects.toThrow();await writeFile(result.reportPath,originalReport);const output=await exportReport(store,result.report.id,destination,review.id,new AbortController().signal);expect(output.status).toBe('passed');const files=await new Bun.Archive(await readFile(destination)).files();expect([...files.keys()].sort()).toEqual(['manifest.json',...review.files.map(f=>f.name)].sort());expect(await files.get('report.html')!.text()).toContain('Exported order');expect(await files.get('report.html')!.text()).not.toContain('PASSWORD_CANARY');const before=await readFile(destination);await expect(exportReport(store,result.report.id,destination,review.id,new AbortController().signal)).rejects.toThrow();expect(await readFile(destination)).toEqual(before);await expect(prepareReportExport(store.directory,store.events,result.report.id,join(root,'export.tar.gz'))).rejects.toThrow('Git');expect(store.events.filter(e=>e.type==='inspection.export.completed')).toHaveLength(1);}
 finally{server.stop(true);store.close();await rm(dir,{recursive:true,force:true});}
},20000);

test('headless export requires exact preview, uses the bundled archive runtime and never overwrites',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'mavona-export-cli-'));const app=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>new Response('<h1>Export CLI</h1>',{headers:{'content-type':'text/html'}})});const command=process.env.MAVONA_TEST_BINARY?[process.env.MAVONA_TEST_BINARY]:[process.execPath,join(import.meta.dir,'../apps/mavona/main.ts')];const flow:Flow={version:1,url:app.url.href,steps:[{op:'observe'},{op:'capture'}]};const path=join(dir,'flow.json');await writeFile(path,JSON.stringify(flow));const {digestFlow}=await import('../packages/app-inspection/service');const destination=join(dir,'portable.tar.gz');const run=async(args:string[])=>{const child=Bun.spawn([...command,...args],{stdout:'pipe',stderr:'pipe'});const [out,err,code]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);return {out,err,code};};
 try{const captured=await run(['app','run','--root',dir,'--flow',path,'--approve-flow',digestFlow(flow),'--data-dir',join(dir,'data')]);expect(captured.code).toBe(4);const result=JSON.parse(captured.out);const args=['app','export','--session',result.sessionId,'--inspection',result.report.id,'--data-dir',join(dir,'data'),'--destination',destination];const preview=await run(args);expect(preview.code).toBe(2);expect(preview.err).toBe('');const review=JSON.parse(preview.out).review;await expect(access(destination)).rejects.toThrow();const refused=await run([...args,'--approve-export','wrong']);expect(refused.code).toBe(2);await expect(access(destination)).rejects.toThrow();const actual=await run([...args,'--approve-export',review.id]);expect(actual.code).toBe(0);expect(actual.err).toBe('');expect(JSON.parse(actual.out).status).toBe('passed');const bytes=await readFile(destination);const files=await new Bun.Archive(bytes).files();expect(files.has('report.html')).toBe(true);expect(files.has('manifest.json')).toBe(true);expect(files.has('report.json')).toBe(false);expect((await run([...args,'--approve-export',review.id])).code).toBe(5);expect(await readFile(destination)).toEqual(bytes);}
 finally{app.stop(true);await rm(dir,{recursive:true,force:true});}
},20000);
