import {PNG} from 'pngjs';import {registry} from 'playwright-core/lib/coreBundle';
import {test,expect} from 'bun:test';import {mkdtemp,readFile,readdir,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {InspectionService,approveFlow,type Flow} from '../packages/app-inspection/service';
import {browserEngines} from './helpers/browser-engines';
for(const browser of browserEngines)test(browser+': constrained Playwright trace records actual browser actions and passes offline loading without secret-bearing payloads',async()=>{
 const root=await mkdtemp(join(tmpdir(),'mavona-trace-'));const canary='private-trace-canary-93481';const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(){return new Response(`<label>Password<input type=password value="${canary}"></label><div data-mavona-private>${canary}</div><button onclick="document.querySelector('p').textContent='Saved'">Save</button><p>Ready</p><script>console.error('${canary}');document.cookie='credential=${canary}';</script>`,{headers:{'content-type':'text/html'}});}});const flow:Flow={version:1,browser,url:`http://127.0.0.1:${server.port}/?token=${canary}`,evidence:{trace:true,video:true},steps:[{op:'observe'},{op:'act',action:'fill',locator:{kind:'label',value:'Password'},value:canary},{op:'capture'},{op:'act',action:'click',locator:{kind:'role',value:'button',name:'Save'}},{op:'assert',id:'saved',kind:'text',expected:'Saved',locator:{kind:'text',value:'Saved'},provenance:'user-approved',required:true}]};const service=new InspectionService();
 try{const report=await service.run(flow,approveFlow(flow,root,'test'),{artifactDirectory:root,secrets:[canary]});expect(report.status).toBe('passed');expect(report.trace.status).toBe('passed');expect(report.video?.status).toBe('passed');if(report.video?.status==='passed'){expect(report.video.frames).toBe(flow.steps.length+1);expect((await readFile(join(root,report.video.path))).subarray(0,4).toString('hex')).toBe('1a45dfa3');const decoded=join(root,'decoded.png');const decoder=Bun.spawn([registry.registry.findExecutable('ffmpeg')!.executablePath()!,'-loglevel','error','-i',join(root,report.video.path),'-frames:v','1',decoded],{stdout:'ignore',stderr:'ignore'});expect(await decoder.exited).toBe(0);const pixels=PNG.sync.read(await readFile(decoded)).data;let masked=0;for(let i=0;i<pixels.length;i+=4)if(pixels[i]!>200&&pixels[i+1]!<60&&pixels[i+2]!>200)masked++;expect(masked).toBeGreaterThan(1000);}if(report.trace.status!=='passed')throw new Error(report.trace.reason);const {validateTraceArchive}=await import('../packages/app-inspection/trace');const verified=await validateTraceArchive(join(root,report.trace.path));expect(verified.actions).toBeGreaterThan(0);expect(verified.frames).toBeGreaterThan(0);expect(verified.text).not.toContain(canary);expect(verified.text).not.toContain('storageState');expect(verified.text).not.toContain('cookies');expect(verified.text).not.toContain('document.querySelector');for(const file of await readdir(root))if(file.endsWith('.json'))expect(await readFile(join(root,file),'utf8')).not.toContain(canary);}
 finally{await service.stop();server.stop(true);await rm(root,{recursive:true,force:true});}
});

import {sanitizeTraceEvent} from '../packages/app-inspection/trace';
import {digestFlow,parseFlow} from '../packages/app-inspection/service';
import {renderReport} from '../packages/app-inspection/report';
test('trace projection drops untrusted payloads and approval binds recording choice',()=>{
 const secret='never-persist';for(const type of ['console','log','resource-snapshot','frame-snapshot','event','unknown'])expect(sanitizeTraceEvent({type,text:secret,params:{secret}})).toBeUndefined();
 const context=sanitizeTraceEvent({type:'context-options',version:8,options:{viewport:{width:800,height:600},storageState:{cookies:[secret]}},browserName:'chromium'});expect(context?.options).toEqual({viewport:{width:800,height:600}});expect(JSON.stringify(context)).not.toContain(secret);
 const before=sanitizeTraceEvent({type:'before',callId:'call@123',class:'Frame',method:'fill',title:secret,params:{value:secret},stack:[secret]});expect(before).toMatchObject({params:{},title:'Frame.fill'});expect(JSON.stringify(before)).not.toContain(secret);
 const after=sanitizeTraceEvent({type:'after',callId:'call@123',error:{message:secret},result:secret});expect(JSON.stringify(after)).not.toContain(secret);
 const flow:Flow={version:1,url:'http://localhost/',steps:[]};expect(digestFlow(flow)).not.toBe(digestFlow({...flow,evidence:{trace:true}}));expect(()=>parseFlow({...flow,evidence:{trace:'yes'}})).toThrow();expect(()=>parseFlow({...flow,evidence:{raw:true}})).toThrow();
 const service=new InspectionService();const report=service.snapshot();report.trace={status:'passed',path:'../../unsafe.zip',sha256:'',size:1,format:'playwright',sanitizerVersion:1,constrained:true,reason:''};expect(()=>renderReport(report)).toThrow('Invalid managed trace path');
});
test('cancelled inspection retains constrained partial trace without claiming correctness',async()=>{
 const root=await mkdtemp(join(tmpdir(),'mavona-trace-cancel-'));const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>new Response('<h1>Partial</h1>',{headers:{'content-type':'text/html'}})});const flow:Flow={version:1,url:server.url.href,evidence:{trace:true},steps:[{op:'observe'},{op:'capture'}]};const service=new InspectionService();try{await service.start(flow,approveFlow(flow,root,'test'),{artifactDirectory:root});await service.observe();await service.capture();const [report]=await Promise.all([service.stop(true),service.stop(true)]);expect(report.status).toBe('unknown');expect(report.state).toBe('cancelled');expect(report.trace.status).toBe('passed');expect(report.video).toBeUndefined();}finally{await service.stop();server.stop(true);await rm(root,{recursive:true,force:true});}
});
