import {TuiController} from '../packages/tui/controller';import {SessionStore} from '../packages/sessions/store';
import {test,expect} from 'bun:test';
import {mkdtemp,rm,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {InspectionService,approveFlow,type Flow} from '../packages/app-inspection/service';
import {startTraceViewer} from '../packages/app-inspection/viewer';
for(const mode of ['source','packaged'] as const)test.skipIf(mode==='packaged'&&!process.env.MAVONA_TEST_BINARY)(mode+': embedded upstream viewer loads constrained trace locally and refuses unrelated file/host requests',async()=>{
 const root=await mkdtemp(join(tmpdir(),'mavona-viewer-'));const app=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>new Response('<button>Continue</button>',{headers:{'content-type':'text/html'}})});const service=new InspectionService();let viewer:Awaited<ReturnType<typeof startTraceViewer>>|undefined;let child:ReturnType<typeof Bun.spawn>|undefined;
 try{const flow:Flow={version:1,url:app.url.href,evidence:{trace:true},steps:[{op:'capture'},{op:'act',action:'click',locator:{kind:'role',value:'button',name:'Continue'}}]};const report=await service.run(flow,approveFlow(flow,root,'test'),{artifactDirectory:root});expect(report.trace.status).toBe('passed');if(report.trace.status!=='passed')throw new Error(report.trace.reason);await writeFile(join(root,'private.txt'),'not-served');if(mode==='source')viewer=await startTraceViewer(join(root,report.trace.path));else{child=Bun.spawn([process.env.MAVONA_TEST_BINARY!,'app','replay','--trace-file',join(root,report.trace.path)],{cwd:root,env:{PATH:'/usr/bin:/bin'},stdout:'pipe',stderr:'inherit'});const reader=(child.stdout as ReadableStream<Uint8Array>).getReader();const timeout=setTimeout(()=>child?.kill('SIGKILL'),10000);try{const first=await reader.read();const ready=JSON.parse(new TextDecoder().decode(first.value));expect(ready.status).toBe('ready');viewer={url:ready.url,stop:async()=>{child?.kill('SIGTERM');await child?.exited;}};}finally{clearTimeout(timeout);reader.releaseLock();}}expect((await fetch(viewer.url)).status).toBe(200);expect((await fetch(new URL('/private.txt',viewer.url))).status).toBe(404);expect((await fetch(viewer.url,{headers:{host:'attacker.invalid'}})).status).toBe(403);expect((await fetch(viewer.url,{headers:{origin:'https://attacker.invalid'}})).status).toBe(403);const result=await service.verifyTraceViewer(viewer.url);expect(result.actionsVisible).toBe(true);expect(result.framesVisible).toBe(true);expect(result.remoteRequests).toEqual([]);if(mode==='source'){const store=new SessionStore(join(root,'session'),'viewer-test');const controller=new TuiController(root,store,()=>{});try{await controller.submit('/app replay '+join(root,report.trace.path));const message=controller.model.messages.at(-1)?.text??'';const url=message.match(/http:\/\/[^\s]+/)?.[0];expect(url).toBeDefined();expect((await fetch(url!)).status).toBe(200);await controller.submit('/app stop');expect(controller.model.messages.at(-1)?.text).toContain('stopped');expect(store.events.some(event=>event.type==='provider.selected'||event.type==='effect.requested')).toBe(false);}finally{controller.cancel();store.close();}}}
 finally{await viewer?.stop();if(child)expect(await child.exited).toBe(0);await service.stop();app.stop(true);await rm(root,{recursive:true,force:true});}
},30000);
