import {expect,test} from 'bun:test';
import {mkdtemp,rm,readFile,writeFile,stat} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {InspectionService,approveFlow,parseFlow} from '../packages/app-inspection/service';
import {browserEngines} from './helpers/browser-engines';

test('observations omit CSS-hidden and redacted text; host artifact root can be outside checkout',async()=>{
 const checkout=await mkdtemp(join(tmpdir(),'mavona-advanced-checkout-')),artifacts=await mkdtemp(join(tmpdir(),'mavona-advanced-artifacts-'));const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(){return new Response('<style>.hide{display:none}</style><h1>Visible</h1><p class="hide">HIDDEN_CANARY</p><div style="visibility:hidden">INVISIBLE_CANARY</div><p data-mavona-private>PRIVATE_CANARY</p>',{headers:{'content-type':'text/html'}});}});try{const flow=parseFlow({version:1,url:server.url.href,steps:[{op:'observe'},{op:'capture'}]});const result=await new InspectionService().run(flow,approveFlow(flow,checkout,'user'),{artifactRoot:artifacts,artifactDirectory:join(artifacts,'run')});expect(result.artifacts).toHaveLength(1);expect(result.observations[0]?.text).toContain('Visible');for(const canary of ['HIDDEN_CANARY','INVISIBLE_CANARY','PRIVATE_CANARY'])expect(JSON.stringify(result)).not.toContain(canary);}finally{server.stop(true);await rm(checkout,{recursive:true,force:true});await rm(artifacts,{recursive:true,force:true});}
});

test('protected authentication state requires explicit scoped reuse and expires outside Git/artifacts',async()=>{
 const {AuthenticationStore}=await import('../packages/app-inspection/authentication');const checkout=await mkdtemp(join(tmpdir(),'mavona-auth-checkout-')),root=await mkdtemp(join(tmpdir(),'mavona-auth-store-'));let now=1000;try{const store=new AuthenticationStore(root,()=>now);const state={cookies:[{name:'session',value:'AUTH_CANARY',domain:'127.0.0.1',path:'/',expires:-1,httpOnly:true,secure:false,sameSite:'Lax' as const}],origins:[]};const ref=await store.save(state,{checkout,origin:'http://127.0.0.1:3000',expiresAt:2000});expect(JSON.stringify(ref)).not.toContain('AUTH_CANARY');expect((await stat(join(root,ref.id+'.json'))).mode&0o777).toBe(0o600);await expect(store.load(ref.id,{checkout,origin:'http://127.0.0.1:3000',reuseApproved:false})).rejects.toThrow('approval-required');expect((await store.load(ref.id,{checkout,origin:'http://127.0.0.1:3000',reuseApproved:true})).state.cookies[0]?.value).toBe('AUTH_CANARY');await expect(store.load(ref.id,{checkout,origin:'http://127.0.0.1:3000',reuseApproved:true,artifactRoot:root})).rejects.toThrow('outside checkout and artifacts');await expect(store.load(ref.id,{checkout,origin:'http://127.0.0.1:4000',reuseApproved:true})).rejects.toThrow('scope');now=2001;await expect(store.load(ref.id,{checkout,origin:'http://127.0.0.1:3000',reuseApproved:true})).rejects.toThrow('expired');await expect(new AuthenticationStore(join(checkout,'auth')).save(state,{checkout,origin:'http://127.0.0.1:3000',expiresAt:Date.now()+10000})).rejects.toThrow('outside');}finally{await rm(root,{recursive:true,force:true});await rm(checkout,{recursive:true,force:true});}
});

test('real browser authentication reuse is explicit and fresh contexts remain isolated',async()=>{
 const {AuthenticationStore}=await import('../packages/app-inspection/authentication');const checkout=await mkdtemp(join(tmpdir(),'mavona-browser-auth-')),root=await mkdtemp(join(tmpdir(),'mavona-private-auth-'));const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){if(new URL(req.url).pathname==='/login')return new Response('Signed in',{headers:{'set-cookie':'session=AUTH_BROWSER_CANARY; HttpOnly; SameSite=Lax; Path=/','content-type':'text/html'}});return new Response(req.headers.get('cookie')?'Authenticated':'Anonymous',{headers:{'content-type':'text/html'}});}});const service=new InspectionService();try{const store=new AuthenticationStore(root);const login=parseFlow({version:1,url:new URL('/login',server.url).href,steps:[]});await service.start(login,approveFlow(login,checkout,'user'));await expect(service.saveAuthentication(store,{approved:false,expiresAt:Date.now()+10000})).rejects.toThrow('approval-required');const reference=await service.saveAuthentication(store,{approved:true,expiresAt:Date.now()+10000});await service.stop();const flow=parseFlow({version:1,url:server.url.href,steps:[{op:'observe'}]});const fresh=await new InspectionService().run(flow,approveFlow(flow,checkout,'user'));expect(fresh.observations[0]?.text).toBe('Anonymous');const reused=await new InspectionService().run(flow,approveFlow(flow,checkout,'user'),{authentication:{store,referenceId:reference.id,reuseApproved:true}});expect(reused.observations[0]?.text).toBe('Authenticated');expect(JSON.stringify(reused)).not.toContain('AUTH_BROWSER_CANARY');}finally{await service.stop();server.stop(true);await rm(checkout,{recursive:true,force:true});await rm(root,{recursive:true,force:true});}
});

for(const browser of browserEngines)test(`${browser} advanced declarative effects: popup/frame, scoped upload, dialog, download and drag`,async()=>{
 const checkout=await mkdtemp(join(tmpdir(),'mavona-browser-effects-'));await writeFile(join(checkout,'upload.txt'),'approved upload');
 const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){const path=new URL(req.url).pathname;if(path==='/frame')return new Response('<label>Frame name<input aria-label="Frame name"></label>',{headers:{'content-type':'text/html'}});if(path==='/popup')return new Response('<h1>Popup content</h1>',{headers:{'content-type':'text/html'}});if(path==='/download')return new Response('Downloaded token=DOWNLOAD_CANARY',{headers:{'content-type':'text/plain','content-disposition':'attachment; filename="unsafe.txt"'}});return new Response(`<h1>Effects</h1><button onclick="window.open('/popup')">Popup</button><iframe data-testid="editor" src="/frame"></iframe><label>Upload<input type="file" aria-label="Upload" onchange="document.querySelector('#upload-state').textContent=this.files[0].name"></label><p id="upload-state"></p><button onclick="document.querySelector('#dialog-state').textContent=confirm('Untrusted dialog')?'Accepted':'Dismissed'">Confirm</button><p id="dialog-state"></p><a download href="/download">Download</a><div draggable="true" data-testid="drag">Drag</div><div data-testid="drop" ondragover="event.preventDefault()" ondrop="this.textContent='Dropped';event.preventDefault()">Drop here</div>`,{headers:{'content-type':'text/html'}});}});
 try{const {createHash}=await import('node:crypto');const flow=parseFlow({version:1,url:server.url.href,browser,steps:[
 {op:'act',action:'click',locator:{kind:'role',value:'button',name:'Popup'},opensPageId:'popup'},
 {op:'act',action:'select-page',value:'popup'},
 {op:'assert',id:'popup',kind:'text',expected:'Popup content',provenance:'user-approved',required:true},
 {op:'act',action:'select-page',value:'main'},
 {op:'act',action:'select-frame',locator:{kind:'testId',value:'editor'},value:'editor'},
 {op:'act',action:'fill',locator:{kind:'label',value:'Frame name'},value:'Frame input'},
 {op:'assert',id:'frame',kind:'value',locator:{kind:'label',value:'Frame name'},expected:'Frame input',provenance:'user-approved',required:true},
 {op:'act',action:'main-frame'},
 {op:'act',action:'upload',locator:{kind:'label',value:'Upload'},value:'approved-file'},
 {op:'act',action:'click',locator:{kind:'role',value:'button',name:'Confirm'},dialog:{type:'confirm',decision:'accept'}},
 {op:'assert',id:'dialog',kind:'text',expected:'Accepted',provenance:'user-approved',required:true},
 {op:'act',action:'download',locator:{kind:'role',value:'link',name:'Download'},value:'text'},
 {op:'act',action:'drag',locator:{kind:'testId',value:'drag'},destination:{kind:'testId',value:'drop'}},
 {op:'assert',id:'drag',kind:'text',expected:'Dropped',provenance:'user-approved',required:true},
 {op:'capture'}]});
 const service=new InspectionService();const report=await service.run(flow,approveFlow(flow,checkout,'user'),{secrets:['DOWNLOAD_CANARY'],uploads:[{reference:'approved-file',path:join(checkout,'upload.txt'),sha256:createHash('sha256').update('approved upload').digest('hex')}],recording:{approved:true,includeObservations:true}});if(report.status!=='passed')console.log(report.reason,report.checks);expect(report.status).toBe('passed');expect(report.downloads).toHaveLength(1);expect(report.surfaces?.some(s=>s.pageId==='popup')).toBe(true);expect(report.recording?.path).toBeDefined();const dir=join(checkout,'.mavona','inspection',report.id);expect(await readFile(join(dir,report.downloads![0]!.path),'utf8')).not.toContain('DOWNLOAD_CANARY');expect(await readFile(join(dir,report.recording!.path),'utf8')).not.toContain('DOWNLOAD_CANARY');
 }finally{server.stop(true);await rm(checkout,{recursive:true,force:true});}
},30000);

test('imported images and region annotations retain unknown runtime provenance',async()=>{
 const checkout=await mkdtemp(join(tmpdir(),'mavona-import-'));const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(){return new Response('<h1>Image</h1>',{headers:{'content-type':'text/html'}});}});const service=new InspectionService();try{const flow=parseFlow({version:1,url:server.url.href,steps:[{op:'capture'}]});const report=await service.run(flow,approveFlow(flow,checkout,'user'));const bytes=await readFile(join(checkout,'.mavona','inspection',report.id,report.artifacts[0]!.path));const imported=await service.importImage(bytes,{approved:true});expect(imported.provenance).toBe('imported');expect(imported.browser).toBe('unknown');expect(imported.context?.repository.status).toBe('unknown');expect(imported.context?.repository.dirtyDigest).toBeNull();expect(imported.context?.server.origin).toBeNull();expect(imported.pageId).toBeNull();expect(imported.redaction).toBe('unreviewed');const annotation=await service.annotate(imported.id,{text:'User reference region',region:{x:0,y:0,width:40,height:40},provenance:'user'});expect(annotation.artifactId).toBe(imported.id);await expect(service.annotate(imported.id,{text:'outside',region:{x:0,y:0,width:50000,height:10},provenance:'user'})).rejects.toThrow('outside image');}finally{await service.stop();server.stop(true);await rm(checkout,{recursive:true,force:true});}
});

test('changed approved upload bytes refuse the effect and preserve unknown required check',async()=>{
 const {createHash}=await import('node:crypto');const checkout=await mkdtemp(join(tmpdir(),'mavona-changed-upload-'));const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(){return new Response('<label>Upload<input type="file" aria-label="Upload"></label>',{headers:{'content-type':'text/html'}});}});try{const path=join(checkout,'selected.txt');await writeFile(path,'changed after approval');const flow=parseFlow({version:1,url:server.url.href,steps:[{op:'act',action:'upload',locator:{kind:'label',value:'Upload'},value:'selected'},{op:'assert',id:'later',kind:'text',expected:'not reached',provenance:'user-approved',required:true}]});const report=await new InspectionService().run(flow,approveFlow(flow,checkout,'user'),{uploads:[{reference:'selected',path,sha256:createHash('sha256').update('approved bytes').digest('hex')}]});expect(report.reason).toContain('upload content changed');expect(report.checks[0]?.status).toBe('unknown');}finally{server.stop(true);await rm(checkout,{recursive:true,force:true});}
});

test('cancellation after a real form effect preserves unknown and never duplicates submission',async()=>{
 const checkout=await mkdtemp(join(tmpdir(),'mavona-cancel-effect-'));let submissions=0;let signalSubmitted:()=>void=()=>{};const submitted=new Promise<void>(resolve=>{signalSubmitted=resolve;});const server=Bun.serve({hostname:'127.0.0.1',port:0,async fetch(req){if(new URL(req.url).pathname==='/submit'){submissions++;signalSubmitted();await new Promise(resolve=>setTimeout(resolve,200));return new Response('<h1>Completed</h1>',{headers:{'content-type':'text/html'}});}return new Response('<form method="post" action="/submit"><button>Submit once</button></form>',{headers:{'content-type':'text/html'}});}});const service=new InspectionService();try{const flow=parseFlow({version:1,url:server.url.href,steps:[{op:'act',action:'click',locator:{kind:'role',value:'button',name:'Submit once'}},{op:'assert',id:'outcome',kind:'text',expected:'Completed',provenance:'user-approved',required:true}]});const running=service.run(flow,approveFlow(flow,checkout,'user'));await submitted;await service.stop();const result=await running;expect(submissions).toBe(1);expect(result.status).toBe('unknown');expect(result.state).toBe('cancelled');expect(result.checks[0]?.status).toBe('unknown');expect(result.events.filter(e=>e.operation==='act'&&e.phase==='intent')).toHaveLength(1);}finally{await service.stop();server.stop(true);await rm(checkout,{recursive:true,force:true});}
});
