import {expect,test} from 'bun:test';
import {copyFile,mkdir,mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {SessionStore} from '../packages/sessions/store';
import {runInspection} from '../packages/agent/inspection';
import type {Flow} from '../packages/app-inspection/service';

test('reviewed repository baseline passes or fails exact comparable captures without rewriting baseline',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'mavona-baseline-')),root=join(directory,'repo'),data=join(directory,'data'),session='visual';await mkdir(join(root,'visual'),{recursive:true});await Bun.spawn(['git','init','-q',root]).exited;let shifted=false;const app=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>new Response('<style>*{font-family:sans-serif}</style><h1 style="margin-left:'+(shifted?80:0)+'px">Stable layout</h1>',{headers:{'content-type':'text/html'}})}),flow:Flow={version:1,url:app.url.href,fixtureRevision:'seed-v1',viewport:{width:640,height:480},steps:[{op:'capture'}]},store=new SessionStore(join(data,'sessions',session),session);store.append('session.opened',{repository:root});
 try{const baselineRun=await runInspection({root,flow,store,signal:new AbortController().signal}),sameRun=await runInspection({root,flow,store,signal:new AbortController().signal});shifted=true;const changedRun=await runInspection({root,flow,store,signal:new AbortController().signal}),baseline=baselineRun.report.artifacts[0]!,same=sameRun.report.artifacts[0]!,changed=changedRun.report.artifacts[0]!;expect(baseline.captureConditions?.fixtureRevision).toBe('seed-v1');expect(same.captureConditions).toEqual(baseline.captureConditions);expect(changed.captureConditions).toEqual(baseline.captureConditions);const baselinePath=join(root,'visual','stable.png');await copyFile(join(baselineRun.reportPath,'..',baseline.path),baselinePath);const original=await readFile(baselinePath),configPath=join(root,'visual','stable.json');const config=(checkId:string)=>({version:1,checkId,baselinePath:'visual/stable.png',baselineSha256:baseline.sha256,conditions:baseline.captureConditions,maxChangedPixelRatio:0,channelTolerance:0,required:true});await writeFile(configPath,JSON.stringify(config('layout-stable')));store.close();
  const command=process.env.MAVONA_TEST_BINARY?[process.env.MAVONA_TEST_BINARY]:[process.execPath,join(import.meta.dir,'../apps/mavona/main.ts')],base=['app','baseline','--session',session,'--data-dir',data,'--capture',same.id,'--config','visual/stable.json'],run=async(args:string[])=>{const child=Bun.spawn([...command,...args],{stdout:'pipe',stderr:'pipe'});const [out,err,code]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);return {out,err,code};};const before=await readFile(join(data,'sessions',session,'events.jsonl')),preview=await run(base);expect(preview.code).toBe(2);expect(await readFile(join(data,'sessions',session,'events.jsonl'))).toEqual(before);const review=JSON.parse(preview.out).review;expect(review.capture.conditions.fixtureRevision).toBe('seed-v1');const passed=await run([...base,'--approve-baseline',review.id]);expect(passed.code).toBe(0);expect(passed.err).toBe('');expect(JSON.parse(passed.out).check).toMatchObject({id:'layout-stable',status:'passed',provenance:'configured-repository',required:true});expect(await readFile(baselinePath)).toEqual(original);
  await writeFile(configPath,JSON.stringify(config('layout-regression')));const reopened=new SessionStore(join(data,'sessions',session),session);let allow=false,controller:InstanceType<typeof import('../packages/tui/controller').TuiController>;const {TuiController}=await import('../packages/tui/controller');controller=new TuiController(root,reopened,model=>{if(model.approval)queueMicrotask(()=>controller.resolveApproval(allow));});try{controller.draft('keep baseline draft');const count=reopened.events.length;await controller.command('/app baseline '+changed.id+' visual/stable.json');expect(reopened.events).toHaveLength(count);expect(controller.model.messages.at(-1)?.text).toContain('not evaluated');allow=true;await controller.command('/app baseline '+changed.id+' visual/stable.json');expect(controller.model.messages.at(-1)?.text).toContain('failed');expect(controller.model.draft).toBe('keep baseline draft');const event=reopened.events.filter(item=>item.type==='app_assertion').at(-1)!;expect(JSON.parse(String(event.payload.evidence))).toMatchObject({id:'layout-regression',status:'failed',provenance:'configured-repository'});expect(await readFile(baselinePath)).toEqual(original);}finally{controller.cancel();reopened.close();}
 }finally{store.close();app.stop(true);await rm(directory,{recursive:true,force:true});}
},30000);
