import {test,expect} from 'bun:test';import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {InspectionService,approveFlow,digestFlow,parseFlow,type Flow} from '../packages/app-inspection/service';import {renderReport} from '../packages/app-inspection/report';
import {browserEngines} from './helpers/browser-engines';
for(const browser of browserEngines)for(const profile of ['desktop','tablet','mobile'] as const)test(`${browser} ${profile}: requested emulation and actual outcome remain explicit`,async()=>{
 const root=await mkdtemp(join(tmpdir(),'mavona-profile-'));const service=new InspectionService();const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>new Response(`<meta name=viewport content="width=device-width,initial-scale=1"><p id=result></p><button id=touch>Touch target</button><p id=outcome></p><script>document.getElementById('result').textContent=[innerWidth,devicePixelRatio,matchMedia('(prefers-color-scheme: dark)').matches,matchMedia('(prefers-reduced-motion: reduce)').matches].join('|');document.getElementById('touch').addEventListener('touchstart',()=>document.getElementById('outcome').textContent='input:touch');document.getElementById('touch').addEventListener('mousedown',()=>{if(!document.getElementById('outcome').textContent)document.getElementById('outcome').textContent='input:mouse';});</script>`,{headers:{'content-type':'text/html'}})});
 const expected=profile==='desktop'?'1280|1|true|true':profile==='tablet'?'820|2|true|true':'390|2|true|true';const flow:Flow={version:1,url:server.url.href,browser,profile,colorScheme:'dark',reducedMotion:'reduce',steps:[{op:'assert',id:'emulated-settings',kind:'text',expected,required:true,provenance:'user-approved'},{op:'act',action:profile==='desktop'?'click':'tap',locator:{kind:'role',value:'button',name:'Touch target'}},{op:'assert',id:'touch-outcome',kind:'text',expected:profile==='desktop'?'input:mouse':'input:touch',required:true,provenance:'user-approved'},{op:'capture'}]};
 try{const report=await service.run(flow,approveFlow(flow,root,'test'),{artifactDirectory:root});expect(report.profile?.id).toBe(profile);expect(report.status).toBe('passed');expect(report.profile?.status).toBe('passed');expect(report.artifacts[0]?.profile?.id).toBe(profile);expect(renderReport(report)).toContain('Emulation is not real-device testing');}
 finally{await service.stop();server.stop(true);await rm(root,{recursive:true,force:true});}
},20000);
test('responsive choices are validated and participate in exact flow approval',()=>{const flow:Flow={version:1,url:'http://localhost',steps:[]};expect(digestFlow(flow)).not.toBe(digestFlow({...flow,profile:'mobile'}));expect(()=>parseFlow({...flow,profile:'invented'})).toThrow();expect(()=>parseFlow({...flow,profile:'mobile',viewport:{width:1000,height:700}})).toThrow();});
