import {test,expect} from 'bun:test';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {InspectionService,approveFlow,type Flow} from '../packages/app-inspection/service';import {renderReport} from '../packages/app-inspection/report';
import {browserEngines} from './helpers/browser-engines';
for(const browser of browserEngines)test(`${browser} actual request timing distinguishes HTTP errors and transport failures without recording private payloads`,async()=>{
 const dir=await mkdtemp(join(tmpdir(),'mavona-requests-'));const outside=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>new Response('must not reach')});const app=Bun.serve({hostname:'127.0.0.1',port:0,async fetch(r){const path=new URL(r.url).pathname;if(path==='/slow'){await Bun.sleep(35);return new Response('BODY_CANARY',{headers:{'set-cookie':'private=COOKIE_CANARY'}});}if(path==='/error')return new Response('ERROR_BODY_CANARY',{status:500});return new Response(`<h1>Order</h1><script>fetch('/slow?token=QUERY_CANARY',{method:'POST',body:'POST_BODY_CANARY',headers:{Authorization:'Bearer HEADER_CANARY'}});fetch('/error');fetch('${outside.url.href}').catch(()=>{});</script>`,{headers:{'content-type':'text/html'}});}});const flow:Flow={version:1,url:app.url.href,browser,steps:[{op:'act',action:'wait',value:'300'},{op:'observe'}]};
 try{const report=await new InspectionService().run(flow,approveFlow(flow,dir,'explicit-user'),{artifactRoot:dir,artifactDirectory:dir});const records=report.network!.requests;const slow=records.find(r=>r.url.includes('/slow'))!;expect(slow.method).toBe('POST');expect(slow.status).toBe(200);expect(slow.outcome).toBe('completed');expect(slow.pageId).toBe('main');expect(slow.timing.responseEnd).toBeGreaterThanOrEqual(0);expect(records.find(r=>r.url.endsWith('/error'))).toMatchObject({status:500,outcome:'completed'});expect(records.some(r=>r.outcome==='failed')).toBe(true);expect(new Set(records.map(r=>r.id)).size).toBe(records.length);expect(report.network!.truncated).toBe(false);expect(report.diagnostics.some(d=>d.kind==='http-error')).toBe(true);expect(report.diagnostics.some(d=>d.kind==='failed-request')).toBe(true);expect(JSON.stringify(report)).not.toContain('CANARY');const html=renderReport(report);expect(html).toContain('Request timing');expect(html).not.toContain('CANARY');}
 finally{outside.stop(true);app.stop(true);await rm(dir,{recursive:true,force:true});}
},20000);

test('request ledger bounds identity and retains unknown timing, pending outcomes and explicit truncation',async()=>{
 const {RequestLedger}=await import('../packages/app-inspection/request-evidence');const timing={startTime:1,domainLookupStart:-1,domainLookupEnd:NaN,connectStart:Infinity,secureConnectionStart:-1,connectEnd:2,requestStart:3,responseStart:4,responseEnd:5};const request=()=>({url:()=>'<untrusted>',method:()=>'GET',resourceType:()=>'fetch',timing:()=>timing});const first=request(),second=request(),third=request();const ledger=new RequestLedger(()=>'/safe',2);const surface={pageId:'page',frameId:null,stepId:null};ledger.begin(first,surface);ledger.begin(first,surface);ledger.begin(second,surface);ledger.begin(third,surface);ledger.response(first,500);ledger.finish(first,'completed');const snapshot=ledger.snapshot();expect(snapshot.requests).toHaveLength(2);expect(snapshot.truncated).toBe(true);expect(snapshot.requests[0]!.timing).toMatchObject({domainLookupStart:null,domainLookupEnd:null,connectStart:null,responseEnd:5});expect(snapshot.requests[0]!.status).toBe(500);expect(snapshot.requests[1]!.outcome).toBe('unknown');expect(snapshot.requests[1]!.timing.responseEnd).toBeNull();snapshot.requests[0]!.url='mutated';expect(ledger.snapshot().requests[0]!.url).toBe('/safe');
});
