import {expect,test} from 'bun:test';
import {mkdir,mkdtemp,readdir,rm,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {digestFlow,type Flow} from '../packages/app-inspection/service';
import {readHistory} from '../packages/sessions/lifecycle';

test('process death after form submission resumes with an unknown effect and never repeats the side effect',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'mavona-inspection-crash-')),root=join(directory,'repo'),data=join(directory,'data');await mkdir(root);await Bun.spawn(['git','init','-q',root]).exited;let submissions=0,child:ReturnType<typeof Bun.spawn>|undefined;const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(request){if(request.method==='POST'){submissions++;queueMicrotask(()=>child?.kill('SIGKILL'));return new Response('<h1>Submitted</h1>',{headers:{'content-type':'text/html'}});}return new Response('<form method="post" action="/submit"><button>Submit once</button></form>',{headers:{'content-type':'text/html'}});}}),flow:Flow={version:1,url:server.url.href,steps:[{op:'act',action:'click',locator:{kind:'role',value:'button',name:'Submit once'}},{op:'act',action:'wait',value:'5000'}]},flowPath=join(root,'flow.json');await writeFile(flowPath,JSON.stringify(flow));const command=process.env.MAVONA_TEST_BINARY?[process.env.MAVONA_TEST_BINARY]:[process.execPath,join(import.meta.dir,'../apps/mavona/main.ts')];
 try{child=Bun.spawn([...command,'app','run','--root',root,'--flow',flowPath,'--approve-flow',digestFlow(flow),'--data-dir',data],{stdout:'pipe',stderr:'pipe'});const code=await child.exited;expect(code).not.toBe(0);expect(submissions).toBe(1);await Bun.sleep(150);const sessions=await readdir(join(data,'sessions'));expect(sessions).toHaveLength(1);const session=sessions[0]!,history=readHistory(join(data,'sessions',session),session),intent=history.events.find(event=>event.type==='effect.requested');expect(intent).toBeDefined();expect(history.state.effects[String(intent!.payload.effectId)]).toBe('unknown');expect(history.events.some(event=>event.type==='effect.completed')).toBe(false);const resumed=Bun.spawn([...command,'resume',session,'--data-dir',data,'--format','json'],{stdout:'pipe',stderr:'pipe'}),[out,err,resumeCode]=await Promise.all([new Response(resumed.stdout).text(),new Response(resumed.stderr).text(),resumed.exited]);expect(resumeCode).toBe(0);expect(err).toBe('');expect(JSON.parse(out)).toMatchObject({mutationAllowed:false,effectReplay:'never'});await Bun.sleep(150);expect(submissions).toBe(1);const after=readHistory(join(data,'sessions',session),session);expect(after.events.filter(event=>event.type==='effect.requested')).toHaveLength(1);expect(after.events.some(event=>event.type==='session.resumed')).toBe(true);}
 finally{child?.kill('SIGKILL');server.stop(true);await rm(directory,{recursive:true,force:true});}
},20000);
