import {test,expect} from 'bun:test';import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {SessionStore} from '../packages/sessions/store';import {runInspection} from '../packages/agent/inspection';import type {Flow} from '../packages/app-inspection/service';
import {prepareRerun,rerunInspection} from '../packages/app-inspection/rerun';
test('saved inspection rerun requires fresh review, preserves assertion provenance and refuses changed source',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'mavona-rerun-')),root=join(directory,'repo');await mkdir(root);await Bun.spawn(['git','init','-q',root]).exited;const store=new SessionStore(join(directory,'session'),'rerun');store.append('session.opened',{repository:root});let requests=0;const app=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>{requests++;return new Response('<h1>Orders</h1>',{headers:{'content-type':'text/html'}});}});const flow:Flow={version:1,url:app.url.href,steps:[{op:'assert',id:'orders',kind:'text',expected:'Orders',required:true,provenance:'configured-repository'},{op:'capture'}]},path=join(root,'flow.json');await writeFile(path,JSON.stringify(flow));
 try{const first=await runInspection({root,flow,flowPath:path,store,signal:new AbortController().signal});const before=requests;const review=await prepareRerun(store,first.report.id);expect(requests).toBe(before);expect(review.flow.steps[0]).toEqual(flow.steps[0]);await expect(rerunInspection(store,first.report.id,'wrong',new AbortController().signal)).rejects.toThrow();expect(requests).toBe(before);const second=await rerunInspection(store,first.report.id,review.id,new AbortController().signal);expect(second.report.status).toBe('passed');expect(second.report.id).not.toBe(first.report.id);expect(requests).toBeGreaterThan(before);await expect(rerunInspection(store,first.report.id,review.id,new AbortController().signal)).rejects.toThrow();await writeFile(path,JSON.stringify({...flow,steps:[]}));await expect(prepareRerun(store,first.report.id)).rejects.toThrow('changed');}
 finally{app.stop(true);store.close();await rm(directory,{recursive:true,force:true});}
},20000);

test('terminal rerun preserves draft, requires approval and performs no browser action on denial',async()=>{
 const {TuiController}=await import('../packages/tui/controller');const directory=await mkdtemp(join(tmpdir(),'mavona-rerun-tui-')),root=join(directory,'repo');await mkdir(root);await Bun.spawn(['git','init','-q',root]).exited;const store=new SessionStore(join(directory,'session'),'rerun-tui');store.append('session.opened',{repository:root});let requests=0,allowed=false;const app=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>{requests++;return new Response('<h1>Orders</h1>',{headers:{'content-type':'text/html'}});}});const flow:Flow={version:1,url:app.url.href,steps:[{op:'capture'}]},path=join(root,'flow.json');await writeFile(path,JSON.stringify(flow));let controller:InstanceType<typeof TuiController>;controller=new TuiController(root,store,model=>{if(model.approval)queueMicrotask(()=>controller.resolveApproval(allowed));});
 try{const first=await runInspection({root,flow,flowPath:path,store,signal:new AbortController().signal});controller.openInspection(first.report.id);controller.draft('rerun draft');const before=requests;await controller.command('/app rerun');expect(requests).toBe(before);expect(controller.model.inspection?.id).toBe(first.report.id);allowed=true;await controller.command('/app rerun');expect(requests).toBeGreaterThan(before);expect(controller.model.inspection?.id).not.toBe(first.report.id);expect(controller.model.draft).toBe('rerun draft');expect(store.events.some(e=>e.type==='inspection.rerun')).toBe(true);}
 finally{controller.cancel();app.stop(true);store.close();await rm(directory,{recursive:true,force:true});}
},20000);

test('headless native rerun previews read-only and executes the same saved flow once per exact grant',async()=>{
 const {readFile}=await import('node:fs/promises');const {digestFlow}=await import('../packages/app-inspection/service');const directory=await mkdtemp(join(tmpdir(),'mavona-rerun-cli-')),root=join(directory,'repo'),data=join(directory,'data');await mkdir(root);await Bun.spawn(['git','init','-q',root]).exited;let requests=0;const app=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>{requests++;return new Response('<h1>Orders</h1>',{headers:{'content-type':'text/html'}});}});const flow:Flow={version:1,url:app.url.href,steps:[{op:'assert',id:'orders',kind:'text',expected:'Orders',required:true,provenance:'user-approved'}]},path=join(root,'flow.json');await writeFile(path,JSON.stringify(flow));const command=process.env.MAVONA_TEST_BINARY?[process.env.MAVONA_TEST_BINARY]:[process.execPath,join(import.meta.dir,'../apps/mavona/main.ts')];const run=async(args:string[])=>{const child=Bun.spawn([...command,'app',...args,'--data-dir',data],{stdout:'pipe',stderr:'pipe'});const [out,err,code]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);return {out,err,code};};
 try{const first=await run(['run','--root',root,'--flow',path,'--approve-flow',digestFlow(flow)]);expect(first.code).toBe(0);const result=JSON.parse(first.out),args=['rerun','--session',result.sessionId,'--inspection',result.report.id],log=join(data,'sessions',result.sessionId,'events.jsonl'),before=await readFile(log),count=requests;const preview=await run(args);expect(preview.code).toBe(2);expect(await readFile(log)).toEqual(before);expect(requests).toBe(count);const review=JSON.parse(preview.out).review;const rerun=await run([...args,'--approve-rerun',review.id]);expect(rerun.code).toBe(0);expect(rerun.err).toBe('');expect(JSON.parse(rerun.out).report.id).not.toBe(result.report.id);const after=requests;expect(after).toBeGreaterThan(count);expect((await run([...args,'--approve-rerun',review.id])).code).toBe(2);expect(requests).toBe(after);}
 finally{app.stop(true);await rm(directory,{recursive:true,force:true});}
},20000);

test('flow references persist only identity and digests; inline, external and overridden flows are unavailable',async()=>{
 const {savedFlowReference}=await import('../packages/app-inspection/rerun');const directory=await mkdtemp(join(tmpdir(),'mavona-flow-reference-')),root=join(directory,'repo');await mkdir(root);const flow:Flow={version:1,url:'http://127.0.0.1:1234/',steps:[{op:'act',action:'fill',locator:{kind:'label',value:'Password'},value:'private-flow-canary'}]},path=join(root,'flow.json');await writeFile(path,JSON.stringify(flow));await writeFile(join(directory,'outside.json'),JSON.stringify(flow));
 try{const ref=await savedFlowReference(root,path,flow);expect(ref.status).toBe('passed');expect(JSON.stringify(ref)).not.toContain('private-flow-canary');expect((await savedFlowReference(root,undefined,flow)).status).toBe('unknown');expect((await savedFlowReference(root,join(directory,'outside.json'),flow)).status).toBe('unknown');expect((await savedFlowReference(root,path,{...flow,browser:'firefox'})).status).toBe('unknown');}finally{await rm(directory,{recursive:true,force:true});}
});
