import {test,expect} from 'bun:test';import {mkdtemp,writeFile,rm,mkdir,chmod} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {digestFlow,type Flow} from '../packages/app-inspection/service';
const command=process.env.MAVONA_TEST_BINARY?[process.env.MAVONA_TEST_BINARY]:[process.execPath,join(import.meta.dir,'../apps/mavona/main.ts')];
test('browser CLI requires exact flow review and emits actual checks and managed report',async()=>{
 const root=await mkdtemp(join(tmpdir(),'mavona-app-cli-'));let hits=0;
 const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(){hits++;return new Response('<h1>Local order</h1>',{headers:{'content-type':'text/html'}});}});
 const flow:Flow={version:1,url:`http://127.0.0.1:${server.port}`,steps:[{op:'observe'},{op:'assert',id:'order-visible',kind:'visible',locator:{kind:'role',value:'heading',name:'Local order'},required:true,provenance:'user-approved'},{op:'capture'}]};const path=join(root,'flow.json');await writeFile(path,JSON.stringify(flow));
 const run=async(extra:string[])=>{const child=Bun.spawn([...command,'app','run','--flow',path,'--root',root,'--data-dir',join(root,'data'),...extra],{stdout:'pipe',stderr:'pipe'});const output=await new Response(child.stdout).text();return {code:await child.exited,output:JSON.parse(output)};};
 try{const refused=await run([]);expect(refused.code).toBe(2);expect(refused.output.approval.flowDigest).toBe(digestFlow(flow));expect(hits).toBe(0);
  const reviewed=await run(['--trace','--video','--profile','mobile','--color-scheme','dark']);expect(reviewed.code).toBe(2);expect(reviewed.output.approval.flow.evidence).toEqual({trace:true,video:true});expect(reviewed.output.approval.flowDigest).not.toBe(digestFlow(flow));const actual=await run(['--trace','--video','--profile','mobile','--color-scheme','dark','--approve-flow',reviewed.output.approval.flowDigest]);expect(actual.code).toBe(0);expect(actual.output.report.status).toBe('passed');expect(actual.output.report.trace.status).toBe('passed');expect(actual.output.report.video.status).toBe('passed');expect(actual.output.report.observations[0].dom.kind).toBe('rendered-dom-aria-hints');expect(actual.output.report.observations[0].dom.elements.some((element:{role:string})=>element.role==='heading')).toBe(true);expect(actual.output.report.profile.id).toBe('mobile');expect(actual.output.report.profile.colorScheme).toBe('dark');expect(actual.output.report.checks[0].status).toBe('passed');expect(await Bun.file(actual.output.reportPath).exists()).toBe(true);expect(hits).toBeGreaterThan(0);
 }finally{server.stop(true);await rm(root,{recursive:true,force:true});}
},30000);
test('headless inspect reviews, starts and cleans up the exact discovered Rails server',async()=>{
 const root=await mkdtemp(join(tmpdir(),'mavona-app-start-cli-'));await mkdir(join(root,'bin'));const rails=join(root,'bin/rails');await writeFile(rails,`#!${process.execPath}\nconst args=process.argv;const port=Number(args[args.indexOf('--port')+1]);const server=Bun.serve({hostname:'127.0.0.1',port,fetch:()=>new Response('<h1>Headless owned</h1>',{headers:{'content-type':'text/html'}})});process.on('SIGTERM',()=>{server.stop(true);process.exit(0)});await new Promise(()=>{});`);await chmod(rails,0o700);const reservation=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>new Response('reserved')}),port=reservation.port!;reservation.stop(true);const url=`http://127.0.0.1:${port}/`,base=[...command,'app','inspect','--url',url,'--root',root,'--data-dir',join(root,'data'),'--start-server'];const run=async(extra:string[])=>{const child=Bun.spawn([...base,...extra],{stdout:'pipe',stderr:'pipe'});const [out,err,code]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);return {out,err,code};};
 try{const preview=await run([]);expect(preview.code).toBe(2);const approval=JSON.parse(preview.out).approval;expect(approval.server.ownership).toBe('owned');expect(approval.server.argv).toContain('--port');const actual=await run(['--approve-flow',approval.flowDigest]);expect(actual.code).toBe(4);expect(actual.err).toBe('');expect(JSON.parse(actual.out).server.ownership).toBe('owned');await expect(fetch(url)).rejects.toThrow();}
 finally{await rm(root,{recursive:true,force:true});}
},20000);
test('headless attach reports unavailable without leaving a pending browser effect',async()=>{
 const root=await mkdtemp(join(tmpdir(),'mavona-app-unavailable-cli-')),data=join(root,'data'),url='http://127.0.0.1:1/',base=[...command,'app','inspect','--url',url,'--root',root,'--data-dir',data];const run=async(extra:string[])=>{const child=Bun.spawn([...base,...extra],{stdout:'pipe',stderr:'pipe'});const [out,code]=await Promise.all([new Response(child.stdout).text(),child.exited]);return {out,code};};try{const preview=await run([]),approval=JSON.parse(preview.out).approval;const result=await run(['--approve-flow',approval.flowDigest]);expect(result.code).toBe(4);expect(JSON.parse(result.out)).toMatchObject({status:'unavailable',correctness:'unknown',server:{ownership:'attached'}});const logs=Array.from(new Bun.Glob('sessions/*/events.jsonl').scanSync(data));const events=(await Bun.file(join(data,logs[0]!)).text()).trim().split('\n').map(line=>JSON.parse(line));expect(events.findLast(event=>event.type==='effect.completed').payload.state).toBe('failed');}finally{await rm(root,{recursive:true,force:true});}
});
test.skipIf(!process.env.MAVONA_TEST_BINARY)('compiled browser download worker uses IPC and extracts a local archive without Node',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'mavona-download-worker-'));
 const zip=Buffer.from('UEsDBBQAAAAAAAAAIVzRp3jPFQAAABUAAAAKAAAAbWFya2VyLnR4dG5hdGl2ZS13b3JrZXItZml4dHVyZVBLAQIUAxQAAAAAAAAAIVzRp3jPFQAAABUAAAAKAAAAAAAAAAAAAACAAQAAAABtYXJrZXIudHh0UEsFBgAAAAABAAEAOAAAAD0AAAAAAA==','base64');
 const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>new Response(zip,{headers:{'content-length':String(zip.length)}})});
 try{const child=Bun.spawn([process.env.MAVONA_TEST_BINARY!,'--mavona-browser-download-worker'],{cwd:dir,env:{PATH:'/usr/bin:/bin'},stdout:'pipe',stderr:'pipe',ipc(){}});child.send({method:'download',params:{title:'Local packaged fixture',browserDirectory:join(dir,'browser'),url:server.url.href,zipPath:join(dir,'archive.zip'),socketTimeout:3000,userAgent:'mavona-local-test'}});
  const timer=setTimeout(()=>child.kill(),5000);try{expect(await child.exited).toBe(0);expect(await Bun.file(join(dir,'browser/marker.txt')).text()).toBe('native-worker-fixture');}finally{clearTimeout(timer);}
 }finally{server.stop(true);await rm(dir,{recursive:true,force:true});}
},10000);
