import {test,expect} from 'bun:test';import {mkdtemp,mkdir,writeFile,rm,readFile} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {runInspection} from '../packages/agent/inspection';import {SessionStore} from '../packages/sessions/store';import {loadReportBundle,startReportViewer} from '../packages/app-inspection/report-viewer';import {InspectionService,approveFlow,type Flow} from '../packages/app-inspection/service';
test('immutable managed report serves exact full-resolution captures and actual browser text; changed artifacts refuse',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'mavona-report-viewer-'));const root=join(dir,'repo');await mkdir(root);await Bun.spawn(['git','init','-q',root]).exited;const store=new SessionStore(join(dir,'session'),'report');const app=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>new Response('<h1>Order report evidence</h1>',{headers:{'content-type':'text/html'}})});let viewer:Awaited<ReturnType<typeof startReportViewer>>|undefined;
 try{const flow:Flow={version:1,url:app.url.href,steps:[{op:'observe'},{op:'capture'}]};const result=await runInspection({root,flow,store,signal:new AbortController().signal});const bundle=await loadReportBundle(store.directory,store.events,result.report.id);expect(bundle.manifest.assets.some(a=>a.name==='report.html')).toBe(true);expect(bundle.manifest.assets.some(a=>a.name==='report.json')).toBe(false);viewer=startReportViewer(bundle);const response=await fetch(viewer.url);expect(response.status).toBe(200);expect(response.headers.get('content-security-policy')).toContain("script-src 'none'");const image=result.report.artifacts[0]!;const imageResponse=await fetch(new URL(image.path,viewer.url));expect(Buffer.from(await imageResponse.arrayBuffer())).toEqual(await readFile(join(result.reportPath,'..',image.path)));
 const browserFlow:Flow={version:1,url:viewer.url,steps:[{op:'assert',id:'report',kind:'text',expected:'App Inspection: unknown',required:true,provenance:'user-approved'}]};const report=await new InspectionService().run(browserFlow,approveFlow(browserFlow,root,'explicit-user'),{checkout:root,artifactRoot:dir,artifactDirectory:join(dir,'viewer-check')});expect(report.status).toBe('passed');expect((await fetch(viewer.url,{headers:{host:'foreign.invalid'}})).status).toBe(403);expect((await fetch(viewer.url,{headers:{origin:'http://foreign.invalid'}})).status).toBe(403);expect((await fetch(viewer.url,{method:'POST'})).status).toBe(405);expect((await fetch(new URL('report.json',viewer.url))).status).toBe(404);expect((await fetch(new URL('../events.jsonl',viewer.url))).status).toBe(404);
 await writeFile(result.reportPath,'<script>tampered</script>');expect(await (await fetch(viewer.url)).text()).not.toContain('tampered');await expect(loadReportBundle(store.directory,store.events,result.report.id)).rejects.toThrow();}
 finally{viewer?.stop();store.close();app.stop(true);await rm(dir,{recursive:true,force:true});}
},20000);

test('report manifest refuses links, traversal and expired evidence before starting a server',async()=>{
 const {symlink,link,unlink}=await import('node:fs/promises');const {createHash}=await import('node:crypto');const dir=await mkdtemp(join(tmpdir(),'mavona-report-boundary-'));const store=new SessionStore(join(dir,'session'),'boundary');const folder=join(store.directory,'artifacts','abc');await mkdir(folder,{recursive:true});const bytes=Buffer.from('<h1>Recorded</h1>');const path=join(folder,'report.html');const outside=join(dir,'outside.html');await writeFile(outside,bytes);const asset={artifactId:'report',name:'report.html',path:'artifacts/abc/report.html',size:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),mediaType:'text/html'};const manifest={version:1,sessionId:store.sessionId,inspectionId:'inspection',assets:[asset]};store.append('inspection.report',{inspectionId:'inspection',manifest:JSON.stringify(manifest)});
 try{await symlink(outside,path);await expect(loadReportBundle(store.directory,store.events,'inspection')).rejects.toThrow();await unlink(path);await link(outside,path);await expect(loadReportBundle(store.directory,store.events,'inspection')).rejects.toThrow();await unlink(path);await writeFile(path,bytes);store.append('artifact.expired',{artifactId:'another-capture',sha256:asset.sha256,provenance:'captured',expiredAt:new Date().toISOString(),reason:'unrelated same bytes'});const loaded=await loadReportBundle(store.directory,store.events,'inspection');expect(loaded.files.get('report.html')).toEqual(bytes);store.append('inspection.report',{inspectionId:'inspection',manifest:JSON.stringify({...manifest,assets:[{...asset,path:'artifacts/abc/../../outside.html'}]})});await expect(loadReportBundle(store.directory,store.events,'inspection')).rejects.toThrow();store.append('inspection.report',{inspectionId:'inspection',manifest:JSON.stringify(manifest)});store.append('artifact.expired',{artifactId:'report',sha256:asset.sha256,provenance:'captured',expiredAt:new Date().toISOString(),reason:'fixture'});await expect(loadReportBundle(store.directory,store.events,'inspection')).rejects.toThrow('expired');}
 finally{store.close();await rm(dir,{recursive:true,force:true});}
});

test('headless report command serves a native-recorded manifest read-only and stops on SIGTERM',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'mavona-report-cli-'));const app=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>new Response('<h1>CLI report</h1>',{headers:{'content-type':'text/html'}})});const command=process.env.MAVONA_TEST_BINARY?[process.env.MAVONA_TEST_BINARY]:[process.execPath,join(import.meta.dir,'../apps/mavona/main.ts')];const flow:Flow={version:1,url:app.url.href,steps:[{op:'observe'},{op:'capture'}]};const path=join(dir,'flow.json');await writeFile(path,JSON.stringify(flow));const {digestFlow}=await import('../packages/app-inspection/service');let viewer:ReturnType<typeof Bun.spawn>|undefined;
 try{const capture=Bun.spawn([...command,'app','run','--root',dir,'--flow',path,'--approve-flow',digestFlow(flow),'--data-dir',join(dir,'data')],{stdout:'pipe',stderr:'pipe'});const result=JSON.parse(await new Response(capture.stdout).text());expect(await capture.exited).toBe(4);const log=join(dir,'data/sessions',result.sessionId,'events.jsonl');const before=await readFile(log);viewer=Bun.spawn([...command,'app','report','--session',result.sessionId,'--inspection',result.report.id,'--data-dir',join(dir,'data')],{stdout:'pipe',stderr:'pipe'});const reader=(viewer.stdout as ReadableStream<Uint8Array>).getReader();const line=await reader.read();const ready=JSON.parse(new TextDecoder().decode(line.value));expect(ready.status).toBe('ready');expect((await fetch(ready.url)).status).toBe(200);expect(await readFile(log)).toEqual(before);viewer.kill('SIGTERM');expect(await viewer.exited).toBe(0);await expect(fetch(ready.url)).rejects.toThrow();await reader.cancel();}
 finally{viewer?.kill();app.stop(true);await rm(dir,{recursive:true,force:true});}
},20000);
