import {test,expect} from 'bun:test';import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {InspectionService,approveFlow,type Flow} from '../packages/app-inspection/service';
for(const browser of ['chromium','firefox','webkit'] as const)test(browser+': bounded DOM/ARIA hints expose selected geometry without private values or hidden ancestors',async()=>{
 const root=await mkdtemp(join(tmpdir(),'mavona-dom-'));const service=new InspectionService();const secret='DOM_SECRET_CANARY';const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>new Response(`<div id=shadow-private data-mavona-private></div><script>document.getElementById('shadow-private').attachShadow({mode:'open'}).innerHTML='<button data-testid=shadow-private>SHADOW_CANARY</button>'</script><main><h1>Orders</h1><label>Access<input type=password value="${secret}"></label><textarea>${secret}</textarea><div hidden><button data-testid=hidden>HIDDEN_CANARY</button></div><section data-mavona-private><button data-testid=private>PRIVATE_CANARY</button></section><p class=redact>SELECTOR_CANARY</p><button aria-label="Save ${secret}" data-testid=save aria-pressed=false onclick="alert('${secret}')">Save</button><button disabled>Unavailable</button>${'<span>Bounded row</span>'.repeat(130)}</main>`,{headers:{'content-type':'text/html'}})});
 const flow:Flow={version:1,url:server.url.href,browser,steps:[{op:'observe'},{op:'observe',locator:{kind:'testId',value:'save'}},{op:'observe',locator:{kind:'testId',value:'hidden'}},{op:'observe',locator:{kind:'testId',value:'private'}},{op:'observe',locator:{kind:'testId',value:'shadow-private'}}]};
 try{const report=await service.run(flow,approveFlow(flow,root,'test'),{artifactDirectory:root,secrets:[secret],redactSelectors:['.redact']});expect(report.observations).toHaveLength(5);const [whole,selected,hidden,privateNode,shadow]=report.observations;expect(whole?.dom?.truncated).toBe(true);expect(whole?.dom?.elements.length).toBeLessThanOrEqual(100);expect(selected?.dom?.elements).toHaveLength(1);expect(selected?.dom?.elements[0]).toMatchObject({tag:'button',role:'button',attributes:{'aria-pressed':'false'},disabled:false});expect(selected?.dom?.elements[0]?.geometry.width).toBeGreaterThan(0);expect(selected?.text).toBe('Save');expect(hidden?.dom?.elements).toHaveLength(0);expect(privateNode?.dom?.elements).toHaveLength(0);expect(hidden?.text).toBe('');expect(shadow?.dom?.elements).toHaveLength(0);for(const canary of [secret,'HIDDEN_CANARY','PRIVATE_CANARY','SELECTOR_CANARY','SHADOW_CANARY','onclick'])expect(JSON.stringify(report)).not.toContain(canary);const ids=whole!.dom!.elements.map(element=>element.id);expect(new Set(ids).size).toBe(ids.length);for(const element of whole!.dom!.elements)if(element.parentId)expect(ids).toContain(element.parentId);expect(report.status).toBe('unknown');}
 finally{await service.stop();server.stop(true);await rm(root,{recursive:true,force:true});}
});

test('observation count budget preserves prior evidence and refuses further collection',async()=>{
 const root=await mkdtemp(join(tmpdir(),'mavona-observation-budget-'));const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>new Response('<p>Bounded</p>',{headers:{'content-type':'text/html'}})});const service=new InspectionService();const flow:Flow={version:1,url:server.url.href,steps:[]};try{await service.start(flow,approveFlow(flow,root,'test'));for(let i=0;i<200;i++)await service.observe();await expect(service.observe()).rejects.toThrow('Observation count budget');expect(service.snapshot().observations).toHaveLength(200);expect(service.snapshot().status).toBe('unknown');}finally{await service.stop();server.stop(true);await rm(root,{recursive:true,force:true});}
},10000);
