import {test,expect} from 'bun:test';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createHash} from 'node:crypto';
import {CompatibleProvider} from '../packages/providers/compatible';import {OpenAIResponsesProvider} from '../packages/providers/openai';import {AnthropicProvider} from '../packages/providers/anthropic';import type {ProviderMessage,ModelCapabilities} from '../packages/providers/types';
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64');
test('all routes serialize only resolved sanitized PNG artifacts and refuse before network on unsupported or changed bytes',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'mavona-images-'));await writeFile(join(dir,'capture.png'),png);let seen:any;let requests=0;
 const server=Bun.serve({hostname:'127.0.0.1',port:0,async fetch(r){seen=await r.json();requests++;const path=new URL(r.url).pathname;return new Response(path.endsWith('/responses')?'data: {"type":"response.completed","response":{"status":"completed"}}\n\n':path.endsWith('/messages')?'data: {"type":"message_start","message":{}}\n\ndata: {"type":"message_delta","delta":{"stop_reason":"end_turn"}}\n\ndata: {"type":"message_stop"}\n\n':'data: {"choices":[{"delta":{},"finish_reason":"stop"}]}\n\ndata: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}});}});
 const hash=createHash('sha256').update(png).digest('hex');const image={type:'image' as const,artifactId:'capture',sha256:hash,mediaType:'image/png' as const,size:png.length,width:1,height:1};const messages:ProviderMessage[]=[{role:'user',content:'',blocks:[{type:'text',text:'Inspect'},image]}];
 const capabilities:ModelCapabilities={streaming:true,tools:true,instructions:true,structuredOutput:false,images:true,locality:'local',source:'provider_metadata',observedAt:new Date().toISOString()};const options={images:{artifactRoot:dir,capabilities,resolveArtifact:async()=>({path:'capture.png',sha256:hash,size:png.length,mediaType:'image/png' as const,redaction:'masked' as const})}};
 try{for(const Class of [CompatibleProvider,OpenAIResponsesProvider,AnthropicProvider]){const connection={id:'stub',baseUrl:`http://127.0.0.1:${server.port}/v1`,locality:'local' as const};const p=new Class(connection,undefined,options);for await(const e of p.stream({model:'stub',messages},new AbortController().signal))void e;expect(JSON.stringify(seen)).toContain(png.toString('base64'));expect(JSON.stringify(seen)).not.toContain(dir);expect(JSON.stringify(seen)).not.toContain('artifactId');
 const unsupported=new Class(connection,undefined,{images:{...options.images,capabilities:{...capabilities,images:false}}});await expect(async()=>{for await(const e of unsupported.stream({model:'stub',messages},new AbortController().signal))void e;}).toThrow('image');}
 expect(requests).toBe(3);await writeFile(join(dir,'capture.png'),Buffer.alloc(png.length));const p=new CompatibleProvider({id:'stub',baseUrl:`http://127.0.0.1:${server.port}/v1`,locality:'local'},undefined,options);await expect(async()=>{for await(const e of p.stream({model:'stub',messages},new AbortController().signal))void e;}).toThrow();expect(requests).toBe(3);
 }finally{server.stop(true);await rm(dir,{recursive:true,force:true});}
});
test('image resolver rejects outside paths, URLs, symlinks, count and dimensions without provider fetch',async()=>{
 const {resolveBlocks}=await import('../packages/providers/images');const {symlink}=await import('node:fs/promises');const dir=await mkdtemp(join(tmpdir(),'mavona-image-policy-'));const outside=await mkdtemp(join(tmpdir(),'mavona-image-outside-'));await writeFile(join(outside,'outside.png'),png);await symlink(join(outside,'outside.png'),join(dir,'link.png'));
 const hash=createHash('sha256').update(png).digest('hex');const image={type:'image' as const,artifactId:'capture',sha256:hash,mediaType:'image/png' as const,size:png.length,width:1,height:1};const connection={id:'stub',baseUrl:'http://localhost:1234/v1',locality:'local' as const};const cap:ModelCapabilities={streaming:true,tools:true,instructions:true,structuredOutput:false,images:true,locality:'local',source:'provider_metadata',observedAt:new Date().toISOString()};
 try{for(const path of [join(outside,'outside.png'),'../escape.png','https://example.com/image.png','link.png'])await expect(resolveBlocks([{role:'user',content:'',blocks:[image]}],connection,{images:{artifactRoot:dir,capabilities:cap,resolveArtifact:async()=>({path,sha256:hash,size:png.length,mediaType:'image/png',redaction:'masked'})}},new AbortController().signal)).rejects.toThrow();
 await expect(resolveBlocks([{role:'user',content:'',blocks:[image,image]}],connection,{images:{artifactRoot:dir,capabilities:cap,maxImages:0,resolveArtifact:async()=>{throw new Error('must refuse before resolution');}}},new AbortController().signal)).rejects.toThrow('count');
 }finally{await rm(dir,{recursive:true,force:true});await rm(outside,{recursive:true,force:true});}
});
