import {test,expect} from 'bun:test';import {prepareRuntimeProbe,decodeRuntimeProbe} from '../packages/rails/runtime-probe';import {readFile} from 'node:fs/promises';
test('runtime request is bounded, test-only and copied privately with no model executable authority',async()=>{
 const probe=await prepareRuntimeProbe('.', ['Order']);try{expect(probe.action.argv.slice(0,4)).toEqual(['ruby','bin/rails','runner','--environment=test']);expect(await readFile(probe.action.argv[4]!,'utf8')).toContain('runtime_observation');expect(JSON.parse(probe.action.argv[5]!)).toEqual({schemaVersion:1,models:['Order']});}finally{await probe.close();}
 await expect(prepareRuntimeProbe('.',['Object;exit'])).rejects.toThrow();
 expect(decodeRuntimeProbe({state:'unknown',durationMs:1,reason:'timeout'}).status).toBe('unknown');expect(decodeRuntimeProbe({state:'passed',durationMs:1,stdout:'not-json'}).status).toBe('unknown');
});
import {mkdtemp,cp,rm} from 'node:fs/promises';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {ToolRuntime} from '../packages/tools/runtime';import {ExecutionPolicy,prepareAction} from '../packages/tools/policy';
test('approved probe observes actual Rails routes and models without granting functional verification',async()=>{
 const root=await mkdtemp(join(tmpdir(),'mavona-runtime-rails-'));await cp(resolve(import.meta.dir,'../fixtures/rails-dogfood'),root,{recursive:true});const policy=new ExecutionPolicy(root);const runtime=new ToolRuntime(root,policy);const signal=new AbortController().signal;
 try{const setup={tool:'run_command' as const,argv:['ruby','bin/rails','db:prepare'],cwd:'.',timeoutMs:30000};policy.approveOnce(await prepareAction(root,setup));expect((await runtime.execute(setup,signal)).state).toBe('passed');const probe=await prepareRuntimeProbe('.',['Order']);try{await expect(runtime.execute(probe.action,signal)).rejects.toThrow();policy.approveOnce(await prepareAction(root,probe.action));const result=await runtime.execute(probe.action,signal);const facts=decodeRuntimeProbe(result);expect(facts.status).toBe('passed');expect(facts.correctness).toBe('unknown');expect(JSON.stringify(facts.routes)).toContain('orders');expect(JSON.stringify(facts.models)).toContain('scheduled_on');expect(facts.environment).toBe('test');}finally{await probe.close();}}finally{await rm(root,{recursive:true,force:true});}
},40000);
import {runTask} from '../packages/agent/loop';import {SessionStore} from '../packages/sessions/store';import type {Provider} from '../packages/providers/types';
for(const approved of [false,true])test(`agent runtime boot ${approved?'approved':'denied'} retains command and verification boundaries`,async()=>{
 const dir=await mkdtemp(join(tmpdir(),'mavona-agent-runtime-')),root=join(dir,'repo');await cp(resolve(import.meta.dir,'../fixtures/rails-dogfood'),root,{recursive:true});await Bun.spawn(['git','init','-q',root]).exited;const policy=new ExecutionPolicy(root),store=new SessionStore(join(dir,'session'),'runtime');let calls=0;
 const provider:Provider={async *stream(request){calls++;if(calls===1)yield{type:'tool.delta',index:0,callId:'runtime',name:'probe_runtime',argumentsDelta:'{"models":[]}'};else{const facts=JSON.parse(request.messages.at(-1)!.content);expect(facts.status).toBe('passed');expect(facts.environment).toBe('test');expect(facts.correctness).toBe('unknown');yield{type:'text.delta',text:'Runtime routes observed; independent checks are still required.'};}yield{type:'completed',finishReason:calls===1?'tool_calls':'stop'};}};
 try{const result=await runTask({root,task:'Inspect order routes',provider,providerId:'fixture',model:'test',capabilities:{streaming:true,tools:true,instructions:true,structuredOutput:false,images:false,locality:'local',source:'bounded_preflight',observedAt:new Date().toISOString()},store,policy,signal:new AbortController().signal,verifiers:[],approveRuntimeProbe:async action=>{expect(action.action.tool).toBe('run_command');return approved;}});expect(calls).toBe(approved?2:1);expect(result.correctness).toBe('unknown');expect(store.events.filter(e=>e.type==='effect.requested')).toHaveLength(approved?1:0);if(approved)expect(store.events.find(e=>e.type==='effect.completed')?.payload.state).toBe('passed');}finally{store.close();await rm(dir,{recursive:true,force:true});}
},40000);
for(const grant of ['absent','[]','["Order"]'])test(`headless runtime grant ${grant} is exact and one-use`,async()=>{
 const dir=await mkdtemp(join(tmpdir(),'mavona-cli-runtime-')),root=join(dir,'repo');await cp(resolve(import.meta.dir,'../fixtures/rails-dogfood'),root,{recursive:true});await Bun.spawn(['git','init','-q',root]).exited;let calls=0;let observed=false;
 const server=Bun.serve({hostname:'127.0.0.1',port:0,async fetch(request){const body=await request.json() as {messages:{role:string;content:string}[]};calls++;if(calls===2)observed=JSON.parse(body.messages.at(-1)!.content).status==='passed';const delta={tool_calls:[{index:0,id:'runtime-'+calls,type:'function',function:{name:'probe_runtime',arguments:'{"models":[]}'}}]};return new Response('data: '+JSON.stringify({choices:[{delta,finish_reason:null}]})+'\n\ndata: '+JSON.stringify({choices:[{delta:{},finish_reason:'tool_calls'}]})+'\n\ndata: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}});}});
 try{const command=process.env.MAVONA_TEST_BINARY?[process.env.MAVONA_TEST_BINARY]:[process.execPath,resolve(import.meta.dir,'../apps/mavona/main.ts')];const child=Bun.spawn([...command,'run','Inspect order routes','--root',root,'--provider','fixture','--model','test','--endpoint',`http://127.0.0.1:${server.port}/v1`,'--locality','local','--trust-model-tools','--data-dir',join(dir,'data'),'--format','jsonl',...(grant==='absent'?[]:['--allow-runtime-probe',grant])],{stdout:'pipe',stderr:'pipe'});const output=await new Response(child.stdout).text();expect(await child.exited).toBe(2);const events=output.trim().split('\n').map(line=>JSON.parse(line));expect(events.at(-1).result.status).toBe('approval_required');expect(events.at(-1).result.correctness).toBe('unknown');expect(calls).toBe(grant==='[]'?2:1);expect(observed).toBe(grant==='[]');expect(events.filter(e=>e.type==='effect.requested')).toHaveLength(grant==='[]'?1:0);}finally{server.stop(true);await rm(dir,{recursive:true,force:true});}
},40000);
