import {test,expect} from 'bun:test';import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {SessionStore} from '../packages/sessions/store';import {listSessions} from '../packages/sessions/lifecycle';import {renameSession,pinSession,sessionMetadata} from '../packages/sessions/metadata';
test('canonical session names and pins preserve stable identity, recorded task and pending effects',async()=>{
 const root=await mkdtemp(join(tmpdir(),'mavona-session-meta-'));const store=new SessionStore(join(root,'stable-id'),'stable-id',['canary-secret']);try{store.append('session.opened',{repository:root});store.append('user.message',{text:'Fix order totals'});store.append('effect.requested',{effectId:'pending',kind:'patch'});renameSession(store,'Order totals canary-secret');pinSession(store,true);expect(sessionMetadata(store.events).title).toBe('Order totals [REDACTED]');expect(sessionMetadata(store.events).pinned).toBe(true);expect(()=>renameSession(store,'\u001b[31munsafe')).toThrow();expect(()=>renameSession(store,' ')).toThrow();expect(()=>renameSession(store,'a'.repeat(121))).toThrow();const row=listSessions(root)[0]!;expect(row.id).toBe('stable-id');expect(row.title).toContain('Order totals');expect(row.taskText).toBe('Fix order totals');expect(row.pendingEffects).toEqual(['pending']);}finally{store.close();await rm(root,{recursive:true,force:true});}
});

test('terminal names, search, pins and archival preserve drafts and require exact archival approval',async()=>{
 const {TuiController}=await import('../packages/tui/controller');const root=await mkdtemp(join(tmpdir(),'mavona-session-meta-tui-'));const store=new SessionStore(join(root,'current'),'current');store.append('session.opened',{repository:root});store.append('user.message',{text:'Fix invoices'});let allowed=false;let controller:InstanceType<typeof TuiController>;controller=new TuiController(root,store,model=>{if(model.approval)queueMicrotask(()=>controller.resolveApproval(allowed));});
 try{controller.draft('retain metadata draft');await controller.command('/rename Invoice correction');await controller.command('/pin-session');await controller.openSessions();controller.filterFiles('Invoice');expect(controller.model.picker?.items).toHaveLength(1);expect(controller.model.picker?.items[0]?.id).toBe('session:current');expect(controller.model.picker?.items[0]?.path).toContain('pinned');controller.closePicker();await controller.command('/archive');expect(sessionMetadata(store.events).archived).toBe(false);allowed=true;await controller.command('/archive');expect(sessionMetadata(store.events).archived).toBe(true);expect(controller.model.draft).toBe('retain metadata draft');await controller.command('/unarchive');await controller.command('/unpin-session');expect(sessionMetadata(store.events)).toMatchObject({pinned:false,archived:false,title:'Invoice correction'});expect(store.events.some(e=>e.type==='task.started'||e.type==='effect.requested')).toBe(false);}
 finally{controller.cancel();store.close();await rm(root,{recursive:true,force:true});}
});

test('headless metadata commands use exact stable session IDs and preserve canonical history',async()=>{
 const root=await mkdtemp(join(tmpdir(),'mavona-session-meta-cli-')),data=join(root,'data');const store=new SessionStore(join(data,'sessions/stable'),'stable');store.append('session.opened',{repository:root});store.append('draft.changed',{text:'retained CLI draft'});store.close();const command=process.env.MAVONA_TEST_BINARY?[process.env.MAVONA_TEST_BINARY]:[process.execPath,join(import.meta.dir,'../apps/mavona/main.ts')];const run=async(args:string[])=>{const child=Bun.spawn([...command,'sessions',...args,'--data-dir',data],{stdout:'pipe',stderr:'pipe'});const [out,err,code]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);return {out,err,code};};
 try{const renamed=await run(['rename','stable','--title','Orders review']);expect(renamed.code).toBe(0);expect(renamed.err).toBe('');expect(JSON.parse(renamed.out)).toMatchObject({id:'stable',title:'Orders review'});expect((await run(['pin','stable'])).code).toBe(0);expect(JSON.parse((await run(['list'])).out).sessions[0]).toMatchObject({id:'stable',title:'Orders review',pinned:true});expect((await run(['rename','stable','--title','x'.repeat(121)])).code).toBe(5);expect((await run(['unpin','stable'])).code).toBe(0);const {readHistory}=await import('../packages/sessions/lifecycle');expect(readHistory(join(data,'sessions/stable'),'stable').state.draft).toBe('retained CLI draft');}
 finally{await rm(root,{recursive:true,force:true});}
});
