import {test,expect} from 'bun:test';import {mkdtempSync,rmSync,readFileSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {SessionStore} from '../packages/sessions/store';import {readHistory,listSessions,resumeSession,forkSession} from '../packages/sessions/lifecycle';import {checkpointSession,readCheckpoint} from '../packages/sessions/checkpoint';
test('read-only catalog, resume, fork and checkpoint preserve pending effect truth and canonical history',()=>{
 const root=mkdtempSync(join(tmpdir(),'mavona-history-'));try{let store=new SessionStore(join(root,'one'),'one');store.append('session.opened',{repository:'/fixture'});store.append('user.message',{text:'requirement'});store.append('effect.requested',{effectId:'pending',kind:'patch'});const cp=checkpointSession(store,'Requirement remains; patch status unknown');expect(readCheckpoint(store.directory)?.id).toBe(cp.id);store.close();
 const before=readFileSync(join(root,'one','events.jsonl'),'utf8');expect(readHistory(join(root,'one'),'one').state.mutationAllowed).toBe(false);expect(readFileSync(join(root,'one','events.jsonl'),'utf8')).toBe(before);expect(listSessions(root)[0]?.id).toBe('one');store=resumeSession(root,'one');expect(store.state.effects.pending).toBe('unknown');store.close();
 const fork=forkSession(root,'one','two');expect(fork.state.effects.pending).toBe('unknown');expect(fork.state.mutationAllowed).toBe(false);expect(fork.state.messages[0]?.text).toBe('requirement');fork.close();expect(listSessions(root)).toHaveLength(2);
 }finally{rmSync(root,{recursive:true,force:true});}
});
test('killed writer releases ownership; resumed pending effects stay unknown',async()=>{
 const root=mkdtempSync(join(tmpdir(),'mavona-crash-'));const module=join(import.meta.dir,'../packages/sessions/store.ts');const child=Bun.spawn([process.execPath,'-e',`import {SessionStore} from ${JSON.stringify(module)};const s=new SessionStore(${JSON.stringify(root)},'crashed');s.append('session.opened',{repository:'/fixture'});s.append('effect.requested',{effectId:'pending',kind:'command'});console.log('ready');setInterval(()=>{},1000);`],{stdout:'pipe',stderr:'pipe'});
 try{const reader=child.stdout.getReader();await reader.read();reader.releaseLock();expect(()=>new SessionStore(root,'crashed')).toThrow('owned');child.kill('SIGKILL');await child.exited;const resumed=new SessionStore(root,'crashed');expect(resumed.state.effects.pending).toBe('unknown');expect(resumed.state.mutationAllowed).toBe(false);resumed.close();}finally{child.kill();await child.exited;rmSync(root,{recursive:true,force:true});}
});
