import {test,expect} from 'bun:test';import {mkdtemp,rm,mkdir} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {SessionStore} from '../packages/sessions/store';import {createSession,readHistory} from '../packages/sessions/lifecycle';import {TuiController} from '../packages/tui/controller';
test('fresh sessions are exclusive and start with empty history and draft',async()=>{const directory=await mkdtemp(join(tmpdir(),'mavona-new-session-')),root=join(directory,'repo'),sessions=join(directory,'sessions');await mkdir(root);const store=createSession(sessions,root,'fresh');try{expect(store.state.draft).toBe('');expect(store.state.messages).toHaveLength(0);expect(store.state.mutationAllowed).toBe(true);expect(()=>createSession(sessions,root,'fresh')).toThrow();}finally{store.close();await rm(directory,{recursive:true,force:true});}});
for(const action of ['new','fork'] as const)test(`terminal ${action} keeps the source draft and acquires a stable destination without inference`,async()=>{
 const directory=await mkdtemp(join(tmpdir(),'mavona-session-create-')),root=join(directory,'repo'),sessions=join(directory,'sessions');await mkdir(root);const store=createSession(sessions,root,'source');store.append('draft.changed',{text:'source draft'});store.append('provider.configured',{configuration:JSON.stringify({provider:'local',model:'test',endpoint:'http://127.0.0.1:9999/v1',locality:'local'})});store.append('effect.requested',{effectId:'unresolved',kind:'command'});let chosen='';const controller=new TuiController(root,store,()=>{},{suspend(){},resume(){},async switchSession(id){chosen=id;const target=new SessionStore(join(sessions,id),id);target.close();}});
 try{await controller.command('/'+action);expect(chosen).not.toBe('');expect(chosen).not.toBe('source');expect(store.state.draft).toBe('source draft');expect(store.state.effects.unresolved).toBe('unknown');const history=readHistory(join(sessions,chosen),chosen);expect(history.state.draft).toBe(action==='new'?'':'source draft');expect(history.state.mutationAllowed).toBe(action==='new');expect(history.events.some(e=>e.type==='provider.configured')).toBe(true);expect(history.events.some(e=>e.type==='task.started')).toBe(false);}
 finally{controller.cancel();store.close();await rm(directory,{recursive:true,force:true});}
});

test('failed destination switch retains current session and exposes the already-created destination',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'mavona-new-session-failure-')),root=join(directory,'repo'),sessions=join(directory,'sessions');await mkdir(root);const store=createSession(sessions,root,'source');const controller=new TuiController(root,store,()=>{},{suspend(){},resume(){},async switchSession(){throw new Error('busy');}});try{controller.draft('preserve on failure');await controller.command('/new');expect(controller.model.draft).toBe('preserve on failure');expect(controller.model.messages.at(-1)?.text).toContain('was created');expect(controller.model.messages.at(-1)?.text).toContain('Current session and draft retained');const {listSessions}=await import('../packages/sessions/lifecycle');expect(listSessions(sessions)).toHaveLength(2);store.append('draft.changed',{text:'still writable'});}finally{store.close();await rm(directory,{recursive:true,force:true});}
});

test('headless new session creates an empty uniquely identified session in the requested checkout',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'mavona-session-new-cli-')),root=join(directory,'repo'),data=join(directory,'data');await mkdir(root);const command=process.env.MAVONA_TEST_BINARY?[process.env.MAVONA_TEST_BINARY]:[process.execPath,join(import.meta.dir,'../apps/mavona/main.ts')];const child=Bun.spawn([...command,'sessions','new','--root',root,'--data-dir',data],{stdout:'pipe',stderr:'pipe'});try{const [out,err,code]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);expect(code).toBe(0);expect(err).toBe('');const result=JSON.parse(out);expect(result.correctness).toBe('unknown');const history=readHistory(join(data,'sessions',result.id),result.id);expect(history.state.draft).toBe('');expect(history.events.map(e=>e.type)).toEqual(['session.opened']);}finally{await rm(directory,{recursive:true,force:true});}
});
