import {test,expect} from 'bun:test';import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {SessionStore} from '../packages/sessions/store';
const command=process.env.MAVONA_TEST_BINARY?[process.env.MAVONA_TEST_BINARY]:[process.execPath,join(import.meta.dir,'../apps/mavona/main.ts')];
test('session CLI inspects exports forks and resumes without replaying effects',async()=>{
 const root=await mkdtemp(join(tmpdir(),'mavona-session-cli-'));const sessions=join(root,'sessions');const store=new SessionStore(join(sessions,'original'),'original');store.append('session.opened',{repository:process.cwd()});store.append('draft.changed',{text:'retained task'});store.append('effect.requested',{effectId:'pending',kind:'command'});store.close();
 const run=async(args:string[])=>{const child=Bun.spawn([...command,...args,'--data-dir',root],{stdout:'pipe',stderr:'pipe'});const text=await new Response(child.stdout).text();expect(await child.exited).toBe(0);return JSON.parse(text);};
 try{
  expect((await run(['sessions','list'])).sessions[0].id).toBe('original');
  expect((await run(['sessions','show','original'])).state.mutationAllowed).toBe(false);
  const exported=await run(['sessions','export','original']);expect(exported.effectReplay).toBe('never');expect(exported.pendingEffects).toEqual(['pending']);
  const fork=await run(['sessions','fork','original']);expect(fork.id).not.toBe('original');expect(fork.mutationAllowed).toBe(false);
  const resumed=await run(['resume','original','--format','json']);expect(resumed.draft).toBe('retained task');expect(resumed.mutationAllowed).toBe(false);
 }finally{await rm(root,{recursive:true,force:true});}
});
test('session CLI explicitly reconciles unknown effects without reporting successful execution',async()=>{
 const {WorktreeLease}=await import('../packages/tools/runtime');const {mkdir}=await import('node:fs/promises');const root=await mkdtemp(join(tmpdir(),'mavona-reconcile-cli-'));const repository=join(root,'repo');await mkdir(repository);await Bun.spawn(['git','init','-q',repository]).exited;const store=new SessionStore(join(root,'sessions','original'),'original');store.append('session.opened',{repository});store.append('effect.requested',{effectId:'interrupted',kind:'command'});store.close();const lease=await WorktreeLease.acquire(repository,'original');lease.beginEffect('interrupted','command');lease.close();
 try{let calls=0;const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(){calls++;return new Response('unexpected',{status:500});}});try{const blocked=Bun.spawn([...command,'run','inspect worktree','--root',repository,'--provider','fixture','--model','test','--endpoint',`http://127.0.0.1:${server.port}/v1`,'--locality','local'],{stdout:'pipe',stderr:'pipe'});const decision=JSON.parse(await new Response(blocked.stdout).text());expect(await blocked.exited).toBe(2);expect(decision.pendingEffects[0]).toMatchObject({owner:'original',effectId:'interrupted'});expect(calls).toBe(0);}finally{server.stop(true);}
 const child=Bun.spawn([...command,'sessions','reconcile','original','--effect','interrupted','--reason','Inspected current files and application state','--data-dir',root],{stdout:'pipe',stderr:'pipe'});const output=JSON.parse(await new Response(child.stdout).text());expect(await child.exited).toBe(0);expect(output).toMatchObject({outcome:'unknown',reconciled:true,verificationFresh:false,mutationAllowed:true});const next=await WorktreeLease.acquire(repository,'next');next.close();}
 finally{await rm(root,{recursive:true,force:true});}
});
test('session CLI adopts only the exact unchanged acceptance review without executing checks',async()=>{
 const {mkdir,writeFile}=await import('node:fs/promises');const {captureRepositoryState}=await import('../packages/tools/repository-state');const {captureAcceptance,makeAcceptanceReview}=await import('../packages/verification/adoption');const root=await mkdtemp(join(tmpdir(),'mavona-adopt-cli-'));const repository=join(root,'repo');await mkdir(join(repository,'test'),{recursive:true});await Bun.spawn(['git','init','-q',repository]).exited;const path=join(repository,'test/order_test.rb');await writeFile(path,'assert_equal 1, order.total');const store=new SessionStore(join(root,'sessions','original'),'original');store.append('session.opened',{repository:await import('node:fs/promises').then(fs=>fs.realpath(repository))});const before=await captureAcceptance(store,await captureRepositoryState(repository),[]);store.append('acceptance.baseline',{snapshot:JSON.stringify(before)});await writeFile(path,'assert_equal 2, order.total');const state=await captureRepositoryState(repository);const review=makeAcceptanceReview(before,await captureAcceptance(store,state,[]),state,[]);store.append('acceptance.review.requested',{review:JSON.stringify(review)});store.close();
 const run=async(id:string)=>{const child=Bun.spawn([...command,'sessions','adopt','original','--review',id,'--reason','Reviewed intended changed expectation','--data-dir',root],{stdout:'pipe',stderr:'pipe'});return {code:await child.exited,stdout:await new Response(child.stdout).text()};};
 try{expect((await run('wrong')).code).not.toBe(0);const accepted=await run(review.id);expect(accepted.code).toBe(0);expect(JSON.parse(accepted.stdout)).toMatchObject({adopted:true,correctness:'unknown',verificationFresh:false});await writeFile(path,'assert true');expect((await run(review.id)).code).not.toBe(0);const reopened=new SessionStore(join(root,'sessions','original'),'original');try{expect(reopened.events.some(event=>event.type==='effect.requested'||event.type==='verification.completed')).toBe(false);}finally{reopened.close();}}
 finally{await rm(root,{recursive:true,force:true});}
});
