import {test,expect} from 'bun:test';import {mkdtemp,mkdir,writeFile,readFile,rm,chmod,stat} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {runTask} from '../packages/agent/loop';import {SessionStore} from '../packages/sessions/store';import {ExecutionPolicy} from '../packages/tools/policy';import {digest} from '../packages/tools/source';import {retainedDeletions,prepareRestoration,restoreSource} from '../packages/tools/recovery';import type {Provider} from '../packages/providers/types';
async function deleted(){const dir=await mkdtemp(join(tmpdir(),'mavona-recovery-')),root=join(dir,'repo');await mkdir(join(root,'config'),{recursive:true});await mkdir(join(root,'app/models'),{recursive:true});await writeFile(join(root,'config/application.rb'),'');const text='# existing user edit\nclass Order; end\n';const path='app/models/order.rb';await writeFile(join(root,path),text);await chmod(join(root,path),0o755);await Bun.spawn(['git','init','-q',root]).exited;const store=new SessionStore(join(dir,'session'),'recovery');let turns=0;const provider:Provider={async *stream(){turns++;if(turns===1)yield{type:'tool.delta',index:0,callId:'delete-order',name:'delete_file',argumentsDelta:JSON.stringify({path,beforeDigest:digest(text)})};yield{type:'completed',finishReason:turns===1?'tool_calls':'stop'};}};await runTask({root,task:'Delete order model',provider,providerId:'fixture',model:'test',capabilities:{streaming:true,tools:true,instructions:true,structuredOutput:false,images:false,locality:'local',source:'user_override',observedAt:new Date().toISOString()},store,policy:new ExecutionPolicy(root),signal:new AbortController().signal,verifiers:[],approve:async()=>true});return {dir,root,store,path,text};}
for(const mode of ['restore','occupied','changed'] as const)test(`retained source ${mode} requires an exact fresh review and never overwrites current changes`,async()=>{
 const {dir,root,store,path,text}=await deleted();try{const entries=retainedDeletions(store.events);expect(entries).toHaveLength(1);const entry=entries[0]!;expect(entry.id).toBe(store.events.find(e=>e.type==='tool.completed')!.eventId);const review=await prepareRestoration(store,entry.id);await expect(restoreSource(store,entry.id,'wrong',new AbortController().signal)).rejects.toThrow();expect(await readFile(join(root,entry.recoveryPath),'utf8')).toBe(text);if(mode==='occupied'){await writeFile(join(root,path),'new user file');await expect(restoreSource(store,entry.id,review.id,new AbortController().signal)).rejects.toThrow();expect(await readFile(join(root,path),'utf8')).toBe('new user file');}else if(mode==='changed'){await writeFile(join(root,entry.recoveryPath),'changed recovery');await expect(restoreSource(store,entry.id,review.id,new AbortController().signal)).rejects.toThrow();}else{const result=await restoreSource(store,entry.id,review.id,new AbortController().signal);expect(result.state).toBe('passed');expect(await readFile(join(root,path),'utf8')).toBe(text);expect((await stat(join(root,path))).mode&0o777).toBe(0o755);expect(store.state.mutationAllowed).toBe(true);expect(store.events.some(e=>e.type==='verification.invalidated')).toBe(true);await expect(prepareRestoration(store,entry.id)).rejects.toThrow();}}
 finally{store.close();await rm(dir,{recursive:true,force:true});}
},20000);

test('terminal recovery picker reviews exact retained source and preserves the composer without inference',async()=>{
 const {TuiController}=await import('../packages/tui/controller');const {dir,root,store,path,text}=await deleted();let reviews=0;let controller:InstanceType<typeof TuiController>;controller=new TuiController(root,store,model=>{if(model.approval){reviews++;expect(model.approval.text).toContain('without replacing');expect(model.approval.text).toContain(path);queueMicrotask(()=>controller.resolveApproval(true));}});
 try{const before=store.events.filter(e=>e.type==='provider.selected').length;controller.draft('unfinished recovery draft');await controller.command('/recover');const item=controller.model.picker!.items[0]!;expect(item.id).toStartWith('recovery:');await controller.pickFile(item.id);expect(reviews).toBe(1);expect(await readFile(join(root,path),'utf8')).toBe(text);expect(controller.model.draft).toBe('unfinished recovery draft');expect(store.events.filter(e=>e.type==='provider.selected')).toHaveLength(before);expect(controller.model.messages.at(-1)?.text).toContain('correctness unknown');}finally{controller.cancel();store.close();await rm(dir,{recursive:true,force:true});}
},20000);

test('headless restoration previews read-only, requires exact approval and restores through the compiled command',async()=>{
 const {rename}=await import('node:fs/promises');const {dir,root,store,path,text}=await deleted();const entry=retainedDeletions(store.events)[0]!;store.close();const data=join(dir,'data');await mkdir(join(data,'sessions'),{recursive:true});await rename(join(dir,'session'),join(data,'sessions','recovery'));const command=process.env.MAVONA_TEST_BINARY?[process.env.MAVONA_TEST_BINARY]:[process.execPath,join(import.meta.dir,'../apps/mavona/main.ts')];const args=['sessions','restore','recovery','--data-dir',data,'--recovery',entry.id];const run=async(extra:string[])=>{const child=Bun.spawn([...command,...args,...extra],{stdout:'pipe',stderr:'pipe'});const [out,err,code]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);return {out,err,code};};
 try{const log=join(data,'sessions/recovery/events.jsonl');const before=await readFile(log);const preview=await run([]);expect(preview.code).toBe(2);expect(preview.err).toBe('');expect(await readFile(log)).toEqual(before);const review=JSON.parse(preview.out).review;expect((await run(['--approve-restore','wrong'])).code).toBe(2);const result=await run(['--approve-restore',review.id]);expect(result.code).toBe(0);expect(result.err).toBe('');expect(JSON.parse(result.out)).toMatchObject({state:'passed',correctness:'unknown'});expect(await readFile(join(root,path),'utf8')).toBe(text);expect((await stat(join(root,path))).mode&0o777).toBe(0o755);expect((await run(['--approve-restore',review.id])).code).toBe(5);}finally{await rm(dir,{recursive:true,force:true});}
},20000);

test('a real competing destination is preserved and unknown restoration requires reconciliation plus a new review',async()=>{
 const {writeFileSync}=await import('node:fs');const {reconcileEffect}=await import('../packages/sessions/reconciliation');const {dir,root,store,path,text}=await deleted();const entry=retainedDeletions(store.events)[0]!;const review=await prepareRestoration(store,entry.id);const append=store.append.bind(store);let injected=false;
 store.append=((...args:Parameters<SessionStore['append']>)=>{const event=append(...args);if(args[0]==='effect.requested'&&!injected){injected=true;writeFileSync(join(root,path),'concurrent user file');}return event;}) as SessionStore['append'];
 try{const result=await restoreSource(store,entry.id,review.id,new AbortController().signal);expect(result.state).toBe('unknown');expect(await readFile(join(root,path),'utf8')).toBe('concurrent user file');expect(await readFile(join(root,entry.recoveryPath),'utf8')).toBe(text);expect(store.state.mutationAllowed).toBe(false);await expect(prepareRestoration(store,entry.id)).rejects.toThrow();store.append=append;await rm(join(root,path));const effect=store.events.findLast(e=>e.type==='source.recovery.completed')!;await reconcileEffect(store,String(effect.payload.effectId),'Inspected both paths; removed the conflicting test file');expect(store.state.mutationAllowed).toBe(true);const fresh=await prepareRestoration(store,entry.id);expect(fresh.id).not.toBe(review.id);await expect(restoreSource(store,entry.id,review.id,new AbortController().signal)).rejects.toThrow();expect((await restoreSource(store,entry.id,fresh.id,new AbortController().signal)).state).toBe('passed');}
 finally{store.append=append;store.close();await rm(dir,{recursive:true,force:true});}
},20000);
