import {expect,test} from 'bun:test';
import {mkdtemp,mkdir,rm,writeFile,chmod} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {SessionStore} from '../packages/sessions/store';
import {TuiController} from '../packages/tui/controller';

test('terminal live inspection captures, pauses for takeover, resumes from fresh state and preserves attached server',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'mavona-live-inspection-')),root=join(directory,'repo');await mkdir(root);await Bun.spawn(['git','init','-q',root]).exited;
 let visits=0;const app=Bun.serve({hostname:'127.0.0.1',port:0,fetch(){visits++;return new Response('<h1>Live inspection</h1>',{headers:{'content-type':'text/html'}});}});const store=new SessionStore(join(directory,'data','sessions','live'),'live');store.append('session.opened',{repository:root});let controller:TuiController;controller=new TuiController(root,store,model=>{if(model.approval)queueMicrotask(()=>controller.resolveApproval(true));});
 try{controller.draft('keep live draft');await controller.command('/inspect-app '+app.url.href);expect(controller.model.messages.at(-1)?.text).toContain('ready');const beforeCapture=visits;await controller.command('/app capture');expect(store.events.some(event=>event.type==='inspection.artifact')).toBe(true);expect(visits).toBeGreaterThanOrEqual(beforeCapture);await controller.command('/app takeover');expect(controller.model.messages.at(-1)?.text).toContain('manual takeover');const artifacts=store.events.filter(event=>event.type==='inspection.artifact').length;await controller.command('/app capture');expect(controller.model.messages.at(-1)?.text).toContain('could not continue');expect(store.events.filter(event=>event.type==='inspection.artifact')).toHaveLength(artifacts);await controller.command('/app resume');expect(controller.model.messages.at(-1)?.text).toContain('fresh observation');expect(store.events.some(event=>event.type==='app_observation')).toBe(true);const operations=store.events.filter(event=>event.type==='inspection.event').map(event=>JSON.parse(String(event.payload.event)).operation);expect(operations).toContain('takeover');expect(operations).toContain('resume');await controller.command('/app stop');expect(controller.model.messages.at(-1)?.text).toContain('Live App Inspection stopped');expect(store.events.some(event=>event.type==='inspection.completed')).toBe(true);expect(controller.model.draft).toBe('keep live draft');expect((await fetch(app.url)).status).toBe(200);}
 finally{controller.cancel();store.close();app.stop(true);await rm(directory,{recursive:true,force:true});}
},20000);

test('terminal reports an occupied start port and records that no browser effect ran',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'mavona-live-occupied-')),root=join(directory,'repo');await mkdir(join(root,'bin'),{recursive:true});await writeFile(join(root,'bin/rails'),'not executed');await Bun.spawn(['git','init','-q',root]).exited;const app=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>new Response('occupied')}),store=new SessionStore(join(directory,'data','sessions','occupied'),'occupied');store.append('session.opened',{repository:root});let controller:TuiController;controller=new TuiController(root,store,model=>{if(model.approval)queueMicrotask(()=>controller.resolveApproval(true));});
 try{await controller.command('/inspect-app start '+app.url.href);expect(controller.model.messages.at(-1)?.text).toContain('Port occupied');const completion=store.events.findLast(event=>event.type==='effect.completed');expect(completion?.payload.state).toBe('failed');expect(store.state.mutationAllowed).toBe(true);}
 finally{controller.cancel();store.close();app.stop(true);await rm(directory,{recursive:true,force:true});}
});

test('terminal starts a reviewed discovered Rails server, shows sanitized logs and stops only its owned process',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'mavona-live-owned-')),root=join(directory,'repo');await mkdir(join(root,'bin'),{recursive:true});await mkdir(join(root,'config'));await writeFile(join(root,'config/application.rb'),'');const script=`#!${process.execPath}\nconst args=process.argv;const port=Number(args[args.indexOf('--port')+1]);console.log('boot token=OWNED_SERVER_CANARY');const server=Bun.serve({hostname:'127.0.0.1',port,fetch:()=>new Response('<h1>Owned Rails server</h1>',{headers:{'content-type':'text/html'}})});process.on('SIGTERM',()=>{server.stop(true);process.exit(0)});await new Promise(()=>{});`;await writeFile(join(root,'bin/rails'),script);await chmod(join(root,'bin/rails'),0o700);await Bun.spawn(['git','init','-q',root]).exited;const reservation=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>new Response('reserved')}),port=reservation.port!;reservation.stop(true);const url=`http://127.0.0.1:${port}/health`,store=new SessionStore(join(directory,'data','sessions','owned'),'owned');store.append('session.opened',{repository:root});let controller:TuiController;controller=new TuiController(root,store,model=>{if(model.approval)queueMicrotask(()=>controller.resolveApproval(true));});
 try{await controller.command('/inspect-app start '+url);expect(controller.model.messages.at(-1)?.text).toContain('owned server');expect((await fetch(url)).status).toBe(200);await Bun.sleep(20);await controller.command('/app logs');expect(controller.model.messages.at(-1)?.text).toContain('[REDACTED]');expect(controller.model.messages.at(-1)?.text).not.toContain('OWNED_SERVER_CANARY');await controller.command('/app stop');await expect(fetch(url)).rejects.toThrow();}
 finally{controller.cancel();store.close();await rm(directory,{recursive:true,force:true});}
},20000);

test('terminal live login save and explicit scoped reuse keep cookie secrets outside session evidence',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'mavona-live-login-')),root=join(directory,'repo');await mkdir(root);await Bun.spawn(['git','init','-q',root]).exited;const canary='LIVE_COOKIE_CANARY';const app=Bun.serve({hostname:'127.0.0.1',port:0,fetch(request){const url=new URL(request.url);if(url.pathname==='/login')return new Response('<h1>Login complete</h1>',{headers:{'content-type':'text/html','set-cookie':`session=${canary}; HttpOnly; SameSite=Lax; Path=/`}});return new Response(request.headers.get('cookie')?.includes(canary)?'<h1>Authenticated</h1>':'<h1>Anonymous</h1>',{headers:{'content-type':'text/html'}});}});const store=new SessionStore(join(directory,'data','sessions','login'),'login');store.append('session.opened',{repository:root});let controller:TuiController;controller=new TuiController(root,store,model=>{if(model.approval)queueMicrotask(()=>controller.resolveApproval(true));});
 try{await controller.command('/inspect-app '+new URL('/login',app.url).href);await controller.command('/app takeover');await controller.command('/app resume');await controller.command('/app save-login 1');const reference=controller.model.messages.at(-1)!.text.match(/[a-f0-9-]{36}/)![0];await controller.command('/app stop');await controller.command('/inspect-app '+app.url.href+' --auth '+reference);expect(controller.model.messages.at(-1)?.text).toContain('reused explicitly');await controller.command('/app takeover');await controller.command('/app resume');const observation=store.events.filter(event=>event.type==='app_observation').at(-1)!;expect(JSON.parse(String(observation.payload.evidence)).text).toContain('Authenticated');await controller.command('/app stop');expect(JSON.stringify(store.events)).not.toContain(canary);}
 finally{controller.cancel();store.close();app.stop(true);await rm(directory,{recursive:true,force:true});}
},20000);
