import {test,expect} from 'bun:test';import {mkdtemp,rm,mkdir} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {SessionStore} from '../packages/sessions/store';import {TuiController} from '../packages/tui/controller';import {runInspection} from '../packages/agent/inspection';import type {Flow} from '../packages/app-inspection/service';
test('terminal inspection drawer projects a real canonical flow without replay and retains the draft',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'mavona-drawer-')),root=join(dir,'repo');await mkdir(root);await Bun.spawn(['git','init','-q',root]).exited;const store=new SessionStore(join(dir,'session'),'drawer');let hits=0;const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(){hits++;return new Response('<h1>Order ready</h1>',{headers:{'content-type':'text/html'}});}});const flow:Flow={version:1,url:server.url.href,steps:[{op:'observe'},{op:'capture'},{op:'assert',id:'heading',kind:'text',expected:'Order ready',required:true,provenance:'model-proposed'}]};const controller=new TuiController(root,store,()=>{});
 try{const result=await runInspection({root,flow,store,signal:new AbortController().signal});const previousHits=hits;controller.draft('unfinished order work');await controller.command('/app');expect(controller.model.inspection?.id).toBe(result.report.id);expect(controller.model.inspection?.text).toContain('Order ready');expect(controller.model.inspection?.text).toContain('model-proposed');expect(controller.model.inspection?.text).toContain('unknown');expect(controller.model.inspection?.text).toContain(result.report.artifacts[0]!.id);expect(controller.model.draft).toBe('unfinished order work');await controller.command('/app history');expect(controller.model.picker?.items[0]?.id).toBe('inspection:'+result.report.id);await controller.pickFile('inspection:'+result.report.id);expect(controller.model.picker).toBeUndefined();expect(controller.model.inspection?.id).toBe(result.report.id);controller.closeInspection();expect(controller.model.inspection).toBeUndefined();expect(hits).toBe(previousHits);expect(store.events.some(e=>e.type==='task.started')).toBe(false);expect(store.events.some(e=>e.type==='inspection.summary')).toBe(true);}
 finally{controller.cancel();store.close();server.stop(true);await rm(dir,{recursive:true,force:true});}
},20000);

test('drawer retains unknown malformed evidence, identifies expiry and strips terminal controls',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'mavona-drawer-records-'));const store=new SessionStore(dir,'history');const controller=new TuiController(dir,store,()=>{});try{await controller.command('/app');expect(controller.model.inspection?.text).toContain('No recorded');store.append('app_observation',{inspectionId:'old',observationId:'o',evidence:'broken'});store.append('inspection.artifact',{inspectionId:'old',artifactId:'image',managedPath:'artifacts/image.png',evidence:JSON.stringify({id:'image',sha256:'a'.repeat(64),redaction:'masked'})});store.append('artifact.expired',{artifactId:'image',sha256:'a'.repeat(64),provenance:'captured',expiredAt:new Date().toISOString(),reason:'test'});store.append('app_assertion',{inspectionId:'old',checkId:'c',evidence:JSON.stringify({id:'c',status:'passed',provenance:'model-proposed',detail:'\x1b[31mHostile\x1b[0m'})});await controller.command('/app');expect(controller.model.inspection?.text).toContain('expired');expect(controller.model.inspection?.text).toContain('Current verification: unknown');expect(controller.model.inspection?.text).not.toContain('\x1b');expect(controller.model.inspection?.text).toContain('Hostile');}finally{controller.cancel();store.close();await rm(dir,{recursive:true,force:true});}
});
