import {test,expect} from 'bun:test';import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {SessionStore} from '../packages/sessions/store';import {TuiController} from '../packages/tui/controller';import type {Flow} from '../packages/app-inspection/service';
test('terminal custom connection, model picker and actual approved agent browser flow preserve truth',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'mavona-tui-model-')),root=join(dir,'repo');await mkdir(join(root,'config'),{recursive:true});await mkdir(join(root,'app/models'),{recursive:true});await writeFile(join(root,'config/application.rb'),'');await writeFile(join(root,'app/models/order.rb'),'class Order\nend\n');await Bun.spawn(['git','init','-q',root]).exited;
 let appHits=0,calls=0,discovery=0,reviewed=0;const app=Bun.serve({hostname:'127.0.0.1',port:0,fetch(){appHits++;return new Response('<h1>Order ready</h1>',{headers:{'content-type':'text/html'}});}});const flow:Flow={version:1,url:app.url.href,steps:[{op:'observe'},{op:'assert',id:'order',kind:'text',expected:'Order ready',required:true,provenance:'user-approved'}]};
 const model=Bun.serve({hostname:'127.0.0.1',port:0,async fetch(request){if(new URL(request.url).pathname.endsWith('/models')){discovery++;expect(request.method).toBe('GET');return Response.json({data:[{id:'test-b'},{id:'test-a'}]});}const body=await request.json() as {messages:{role:string;content:string}[]};calls++;const tool=calls===1?{name:'mavona_capability_probe',arguments:JSON.stringify({ok:true})}:calls===2?{name:'inspect_app',arguments:JSON.stringify({flow:JSON.stringify(flow)})}:undefined;if(calls===1)expect(JSON.stringify(body)).not.toContain(root);const delta=tool?{tool_calls:[{index:0,id:'tool-'+calls,type:'function',function:tool}]}:{content:'Inspected order; no independent repository check was configured.'};return new Response('data: '+JSON.stringify({choices:[{delta,finish_reason:null}]})+'\n\ndata: '+JSON.stringify({choices:[{delta:{},finish_reason:tool?'tool_calls':'stop'}]})+'\n\ndata: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}});}});
 const store=new SessionStore(join(dir,'session'),'terminal-models');let controller:TuiController;controller=new TuiController(root,store,next=>{if(next.approval){reviewed++;expect(next.approval.text).toContain('model-proposed');queueMicrotask(()=>controller.resolveApproval(true));}});
 try{await controller.submit('/connect');expect(controller.model.picker?.items).toHaveLength(4);await controller.pickFile('subscription');expect(controller.model.messages.at(-1)?.text).toContain('subscription_agent_loop_unsupported');expect(calls).toBe(0);await controller.submit(`/connect fixture test-b ${model.url.href}v1 local`);expect(controller.model.connection).toContain('LOCAL');expect(calls).toBe(0);await controller.submit('/models');expect(discovery).toBe(1);expect(calls).toBe(0);controller.draft('unfinished order task');const choice=controller.model.picker?.items.find(item=>item.path==='test-a');expect(choice).toBeDefined();await controller.pickFile(choice!.id);expect(controller.model.connection).toContain('test-a');expect(controller.model.draft).toBe('unfinished order task');expect(calls).toBe(0);await controller.submit('Inspect order behavior');expect(calls).toBe(3);expect(reviewed).toBe(1);expect(appHits).toBeGreaterThan(0);expect(controller.model.messages.at(-1)?.text).toContain('correctness unknown');expect(store.events.some(event=>event.type==='app_observation')).toBe(true);const reopened=new TuiController(root,store,()=>{});expect(reopened.model.connection).toContain('test-a');await reopened.submit('/disconnect');const disconnected=new TuiController(root,store,()=>{});expect(disconnected.model.connection).toBeUndefined();disconnected.cancel();reopened.cancel();}
 finally{controller.cancel();store.close();model.stop(true);app.stop(true);await rm(dir,{recursive:true,force:true});}
},20000);
test('rejected endpoint credentials are not persisted and do not replace explicit locality',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'mavona-tui-endpoint-'));const store=new SessionStore(join(dir,'session'),'endpoint');const controller=new TuiController(dir,store,()=>{});try{await controller.submit('/connect fixture test http://127.0.0.1:12345/v1 local');const original=controller.model.connection;await controller.submit('/connect fixture test http://USER_CANARY:PASSWORD_CANARY@127.0.0.1:12345/v1 local');expect(controller.model.connection).toBe(original);await controller.submit('/connect fixture test http://example.invalid/v1 local');expect(controller.model.connection).toBe(original);expect(JSON.stringify(store.events)).not.toContain('PASSWORD_CANARY');expect(JSON.stringify(store.events)).not.toContain('USER_CANARY');expect(store.events.filter(event=>event.type==='provider.configured')).toHaveLength(1);}finally{controller.cancel();store.close();await rm(dir,{recursive:true,force:true});}
});
