import {isKnown,type Envelope} from '../protocol/events';
export interface InspectionDrawer {id:string|null;text:string}
const clean=(value:unknown,limit=2048)=>String(value??'unknown').replace(/\x1b\[[0-?]*[ -/]*[@-~]/g,'').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f-\u009f\u202a-\u202e\u2066-\u2069]/g,'').slice(0,limit);
function parsed(value:unknown):Record<string,unknown>{if(typeof value!=='string'||value.length>1024*1024)return {};try{const data:unknown=JSON.parse(value);return data&&typeof data==='object'&&!Array.isArray(data)?data as Record<string,unknown>:{};}catch{return {};}}
const objects=(value:unknown):Record<string,unknown>[]=>Array.isArray(value)?value.filter(item=>item&&typeof item==='object'&&!Array.isArray(item)):[];
const status=(value:unknown)=>['passed','failed','unknown'].includes(String(value))?String(value):'unknown';
export function inspectionChoices(events:readonly Envelope[]){const found=new Map<string,{id:string;path:string}>();for(let index=events.length-1;index>=0;index--){const event=events[index]!;if(!isKnown(event)||!('inspectionId' in event.payload)||typeof event.payload.inspectionId!=='string')continue;const id=event.payload.inspectionId;if(found.has(id))continue;found.set(id,{id:'inspection:'+id,path:clean(id,128)+' · '+(event.type==='inspection.completed'?status(event.payload.status):'partial; liveness unknown')});if(found.size>=100)break;}return [...found.values()];}
export function inspectionDrawer(events:readonly Envelope[],id?:string):InspectionDrawer {
 const selected=id??inspectionChoices(events)[0]?.id.slice('inspection:'.length);if(!selected)return {id:null,text:'No recorded inspections. Use /app run FLOW_PATH to review and run a saved flow.\nBrowser access requires approval; viewing this drawer makes no requests.'};
 const relevant=events.filter(event=>isKnown(event)&&'inspectionId' in event.payload&&event.payload.inspectionId===selected);if(!relevant.length)throw new Error('Unknown inspection identity');const bounded=relevant.slice(-2000);const completed=bounded.findLast(event=>event.type==='inspection.completed');const summary=parsed(bounded.findLast(event=>event.type==='inspection.summary')?.payload.summary);
 const checks=bounded.filter(event=>event.type==='app_assertion').map(event=>parsed(event.payload.evidence));const captures=bounded.filter(event=>event.type==='inspection.artifact');const observations=bounded.filter(event=>event.type==='app_observation').slice(-2).map(event=>parsed(event.payload.evidence));
 const lines=['Inspection '+clean(selected,128),'Recorded result: '+status(completed?.payload.status)+' · '+(completed?'completed':'partial; browser liveness unknown'),'Current verification: unknown. This view never reruns browser actions.',relevant.length>bounded.length?'Older evidence omitted from this bounded drawer.':'','Required and diagnostic checks · latest 20'];
 for(const check of checks.slice(-20))lines.push(`${clean(check.id,100)} · ${status(check.status)} · ${clean(check.provenance,100)}${check.required?' · required':''}\n${clean(check.detail,300)}`);if(!checks.length)lines.push('No recorded assertions; correctness unknown.');
 lines.push('\nCaptures · latest 10 · text fallback; availability unchecked unless expired');for(const event of captures.slice(-10)){const artifact=parsed(event.payload.evidence);const expired=events.some(item=>item.type==='artifact.expired'&&item.payload.artifactId===event.payload.artifactId&&item.payload.sha256===artifact.sha256);lines.push(`${clean(event.payload.artifactId,100)} · ${expired?'expired':clean(artifact.redaction,100)}\nSHA256 ${clean(artifact.sha256,64)}\n${clean(event.payload.managedPath,300)}`);}if(!captures.length)lines.push('No canonical capture records available.');
 lines.push('\nObserved page content · latest 2 · untrusted');for(const observation of observations)lines.push(clean(observation.url,300)+'\n'+clean(observation.text,2000));
 const diagnostics=objects(summary.diagnostics);if(diagnostics.length){lines.push('\nDiagnostics');for(const item of diagnostics.slice(-10))lines.push(clean(item.kind,100)+': '+clean(item.message,500));}
 const network=summary.network&&typeof summary.network==='object'?summary.network as Record<string,unknown>:{};const requests=objects(network.requests);if(requests.length){lines.push('\nRecent requests · timing does not verify functionality');for(const request of requests.slice(-5))lines.push(`${clean(request.method,16)} ${clean(request.url,200)} · HTTP ${clean(request.status,3)} · ${clean(request.outcome,16)}`);}
 lines.push('\nLocal report: '+clean(completed?.payload.reportPath,512),'Images and model judgements do not establish correctness.');return {id:selected,text:lines.join('\n')};
}
