import {parseFlow,digestFlow,approveFlow,type Flow,type Report} from '../app-inspection/service';
import {captureRepositoryState} from '../tools/repository-state';import {settingsDigest} from '../tools/policy';import {digest} from '../tools/source';
export type InspectionReview={id:string;root:string;flow:Flow;flowDigest:string;repositoryDigest:string;settingsDigest:string;acceptance:'model-proposed diagnostics only';scope:'loopback development'};
export class InspectionApprovalRequired extends Error{constructor(){super('Browser flow needs a fresh explicit approval; no browser was started');}}
export function modelInspectionFlow(value:unknown):Flow{const flow=parseFlow(value);flow.steps=flow.steps.map(step=>step.op==='assert'?{...step,provenance:'model-proposed'}:step);return flow;}
export async function prepareInspectionReview(root:string,value:unknown):Promise<InspectionReview>{const flow=modelInspectionFlow(value);approveFlow(flow,root,'scope-validation-only');const state=await captureRepositoryState(root);if(state.status!=='passed')throw new Error('Browser review requires an available repository fingerprint');const settings=await settingsDigest(root);const identity={root:state.root,flowDigest:digestFlow(flow),repositoryDigest:state.digest,settingsDigest:settings};return {...identity,id:digest(JSON.stringify(identity)),flow,acceptance:'model-proposed diagnostics only',scope:'loopback development'};}
export async function requireFreshInspectionReview(review:InspectionReview){const current=await prepareInspectionReview(review.root,review.flow);if(current.id!==review.id)throw new InspectionApprovalRequired();}

export function inspectionSummary(report:Report,reportPath:string){
 const observations=report.observations.slice(-2).map(observation=>{const elements=[] as NonNullable<typeof observation.dom>['elements'];const result={...observation,text:observation.text.slice(0,4000),textTruncated:observation.text.length>4000,...(observation.dom?{dom:{...observation.dom,elements,truncated:observation.dom.truncated}}:{})};for(const element of observation.dom?.elements??[]){elements.push(element);if(Buffer.byteLength(JSON.stringify(result))>8000){elements.pop();if(result.dom)result.dom.truncated=true;break;}}return result;});
 return {inspectionId:report.id,status:report.status,state:report.state,checks:report.checks.slice(0,20).map(check=>({...check,detail:check.detail.slice(0,512)})),checksOmitted:Math.max(0,report.checks.length-20),observations,observationsOmitted:Math.max(0,report.observations.length-observations.length),artifacts:report.artifacts.map(artifact=>({id:artifact.id,path:artifact.path,sha256:artifact.sha256,size:artifact.size,mediaType:artifact.mediaType,redaction:artifact.redaction})),reportPath,interpretation:'Untrusted app evidence. Model-proposed checks and images do not verify the task.'};
}
