import {join,relative} from 'node:path';import {readSource,digest} from '../tools/source';import type {RepositoryInspection} from '../rails/discovery';import type {TaskRouting} from '../rails/routing';
export interface Criterion {path:string;digest:string}
export interface VerifierCandidate {id:string;argv:string[];cwd:string;required:boolean;provenance:'repository';timeoutMs:number;scope:string[];rationale:string;criteria:Criterion[];execution:'approval_required'}
export interface VerifierSelection {status:'selected'|'unknown';verifiers:VerifierCandidate[];reason?:string}
const record=(value:unknown):value is Record<string,unknown>=>!!value&&typeof value==='object'&&!Array.isArray(value);
async function configuration(root:string,path:string){const seen=new Set<string>();const entries:Record<string,unknown>={};const criteria:Criterion[]=[];
 const visit=async(file:string,depth:number):Promise<void>=>{if(depth>8||seen.size>=32)throw new Error('Verification configuration include limit');if(seen.has(file))return;seen.add(file);let source;try{source=await readSource(root,file,256*1024);}catch(error){if(file===path&&(error as NodeJS.ErrnoException).code==='ENOENT')return;throw error;}criteria.push({path:source.path,digest:source.digest});const parsed=Bun.YAML.parse(source.text) as unknown;if(!record(parsed))throw new Error('Configuration must be a mapping');
  const includes=parsed.include;if(includes!==undefined){if(!Array.isArray(includes)||!includes.every(value=>typeof value==='string'))throw new Error('Configuration includes must be paths');for(const include of includes)await visit(include,depth+1);}
  if(parsed.verification!==undefined){if(!record(parsed.verification))throw new Error('Verification must be a mapping');for(const [name,value] of Object.entries(parsed.verification)){if(!/^[a-z][a-z0-9_-]{0,63}$/.test(name))throw new Error('Invalid verifier identity');entries[name]=value;}}
 };await visit(path,0);return {entries,criteria};}
export async function selectVerifiers(inspection:RepositoryInspection,routing:TaskRouting):Promise<VerifierSelection>{
 if(inspection.status!=='selected'||inspection.selectedRoot===null||routing.status!=='PLAN_READY')return {status:'unknown',verifiers:[],reason:'Select a bounded Rails task first'};
 const root=inspection.repository,cwd=inspection.selectedRoot;const global=await configuration(root,'.mavona.yml');const local=cwd==='.'?undefined:await configuration(root,join(cwd,'.mavona.yml'));const configured={entries:{...global.entries,...local?.entries},criteria:[...global.criteria,...local?.criteria??[]]};const files=inspection.files.map(path=>({path,local:relative(join(root,cwd),join(root,path))}));const testFiles=files.filter(file=>/^(?:test\/.*_test\.rb|spec\/.*_spec\.rb)$/.test(file.local));const nominated=new Set(routing.candidates.filter(candidate=>candidate.nominated).map(candidate=>candidate.path));const focused=testFiles.filter(file=>nominated.has(file.path));
 if(Object.keys(configured.entries).length>32)throw new Error('Configured verifier count limit');
 const candidates:Omit<VerifierCandidate,'id'|'criteria'|'execution'|'provenance'>[]=[];
 for(const [name,value] of Object.entries(configured.entries).sort(([a],[b])=>a<b?-1:1)){
  if(!record(value)||!Array.isArray(value.command)||!value.command.length||value.command.length>64||!value.command.every(arg=>typeof arg==='string'&&arg.length<16384&&!arg.includes('\0')))throw new Error('Configured verification requires an argument array');
  if(value.required!==undefined&&typeof value.required!=='boolean')throw new Error('Verifier required must be boolean');const timeoutMs=value.timeoutMs??60000;if(!Number.isSafeInteger(timeoutMs)||Number(timeoutMs)<1||Number(timeoutMs)>300000)throw new Error('Verifier timeout limit');
  candidates.push({argv:value.command,cwd,required:value.required!==false,timeoutMs:Number(timeoutMs),scope:testFiles.map(file=>file.path),rationale:'Configured verification: '+name});
 }
 if(!candidates.length){
  for(const framework of ['minitest','rspec']){if(!inspection.facts.testFrameworks.includes(framework))continue;const prefix=framework==='minitest'?'test/':'spec/';const selected=focused.filter(file=>file.local.startsWith(prefix));const narrow=selected.length>0&&selected.length<=30;const argv=framework==='minitest'?['bin/rails','test']:['bundle','exec','rspec'];if(narrow)argv.push(...selected.map(file=>file.local));candidates.push({argv,cwd,required:true,timeoutMs:60000,scope:(narrow?selected:testFiles.filter(file=>file.local.startsWith(prefix))).map(file=>file.path),rationale:narrow?'Task-evidenced corresponding '+framework+' checks':'Broader '+framework+' suite; no bounded corresponding test path'});}
 }
 if(!candidates.length)return {status:'unknown',verifiers:[],reason:'No configured or evidenced repository checks'};
 const output:VerifierCandidate[]=[];let bytes=0;const cached=new Map<string,Criterion>();
 for(const candidate of candidates){const helpers=files.filter(file=>/^(?:test\/test_helper\.rb|spec\/(?:spec|rails)_helper\.rb|\.rspec|Rakefile)$/.test(file.local)).map(file=>file.path);const paths=[...new Set([...candidate.scope,...helpers])];if(paths.length>1000)return {status:'unknown',verifiers:[],reason:'Verification criteria exceed bounded inspection; configure a narrower scope'};const criteria=[...configured.criteria];for(const path of paths){let criterion=cached.get(path);if(!criterion){const source=await readSource(root,path,256*1024);bytes+=Buffer.byteLength(source.text);if(bytes>8*1024*1024)return {status:'unknown',verifiers:[],reason:'Verification criteria byte budget exceeded'};criterion={path:source.path,digest:source.digest};cached.set(path,criterion);}criteria.push(criterion);}output.push({...candidate,id:'verifier_'+digest(JSON.stringify({root,cwd,argv:candidate.argv,scope:candidate.scope})).slice(0,16),provenance:'repository',criteria,execution:'approval_required'});}
 return {status:'selected',verifiers:output};
}
export async function criteriaUnchanged(root:string,criteria:readonly Criterion[]):Promise<boolean>{for(const criterion of criteria){try{if((await readSource(root,criterion.path,256*1024)).digest!==criterion.digest)return false;}catch{return false;}}return true;}
