import {realpath,lstat} from 'node:fs/promises';import {constants,closeSync,writeSync,fsyncSync,fstatSync} from 'node:fs';import {isAbsolute,dirname,basename,join,relative} from 'node:path';
import {AnchoredFiles} from '../tools/anchored-files';import {mutationScope} from '../tools/mutation-path';import {readBoundedFile} from './files';import {digest} from '../tools/source';
export interface PublicationIO {write(fd:number,bytes:Buffer,offset:number,length:number,position:number):number}
export async function prepareExportDestination(directory:string,destination:string,extension:'.json'|'.tar.gz'){
 if(!isAbsolute(destination)||!destination.endsWith(extension)||destination.includes('\0'))throw new Error('Choose a new absolute '+extension+' destination');const parent=await realpath(dirname(destination)),target=join(parent,basename(destination));const storage=await realpath(basename(dirname(directory))==='sessions'?dirname(directory):directory);const rel=relative(storage,target);if(!rel||!rel.startsWith('..')&&!isAbsolute(rel))throw new Error('Export outside session storage');
 for(let path=parent;;path=dirname(path)){try{await lstat(join(path,'.git'));throw new Error('Export destination must be outside Git worktrees');}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}if(dirname(path)===path)break;}
 return {destination:target,parent,scope:await mutationScope(parent,basename(target),true)};
}
export async function publishExport(prepared:Awaited<ReturnType<typeof prepareExportDestination>>,bytes:Buffer,exportId:string,signal:AbortSignal,io:PublicationIO={write:writeSync}){
 const temporary='.mavona-export-'+exportId+'.tmp';let files:AnchoredFiles|undefined,parent:ReturnType<AnchoredFiles['parent']>|undefined,target:ReturnType<AnchoredFiles['parent']>|undefined,fd:number|undefined;
 try{signal.throwIfAborted();const fresh=await mutationScope(prepared.parent,basename(prepared.destination),true);if(JSON.stringify(fresh)!==JSON.stringify(prepared.scope)||await realpath(prepared.parent)!==prepared.parent)throw new Error('Export destination changed');files=new AnchoredFiles(prepared.parent,prepared.scope);parent=files.parent(temporary);target=files.parent(basename(prepared.destination));fd=files.open(parent,constants.O_CREAT|constants.O_EXCL|constants.O_WRONLY,0o600);let offset=0;while(offset<bytes.length){signal.throwIfAborted();const count=io.write(fd,bytes,offset,Math.min(65536,bytes.length-offset),offset);if(count<=0)throw new Error('Export write made no progress');offset+=count;}fsyncSync(fd);const written=fstatSync(fd);signal.throwIfAborted();files.move(parent,target);const current=readBoundedFile(prepared.destination,Math.max(1,bytes.length)),final=await lstat(prepared.destination);if(final.ino!==written.ino||final.dev!==written.dev||digest(current)!==digest(bytes)||await realpath(prepared.parent)!==prepared.parent)throw new Error('Export changed during publication');return {status:'passed' as const,path:prepared.destination,sha256:digest(bytes),size:bytes.length};}
 catch{return {status:'unknown' as const,path:prepared.destination,temporaryPath:join(prepared.parent,temporary),reason:'Export interrupted or destination changed. Inspect these paths; no automatic retry or overwrite.'};}
 finally{if(fd!==undefined)closeSync(fd);target?.close();parent?.close();files?.close();}
}
