import {readSessionBytes} from './files';
import {readdirSync,existsSync,mkdirSync,writeFileSync,renameSync,openSync,fsyncSync,closeSync} from 'node:fs';import {join} from 'node:path';import {createHash} from 'node:crypto';
import {decode,type Envelope} from '../protocol/events';import {replay} from '../domain/task';import {SessionStore} from './store';
export function sessionPath(root:string,id:string):string{if(!/^[\w-]+$/.test(id)||id==='.'||id==='..')throw new Error('Invalid session ID');return join(root,id);}
export function readHistory(directory:string,id:string){const bytes=readSessionBytes(directory);const boundary=bytes.lastIndexOf(10)+1;const events:Envelope[]=[];const seen=new Map<string,string>();for(const line of new TextDecoder('utf-8',{fatal:true}).decode(bytes.subarray(0,boundary)).split('\n').filter(Boolean)){const event=decode(JSON.parse(line));if(event.sessionId!==id)throw new Error('Session identity mismatch');const encoded=JSON.stringify(event);const prior=seen.get(event.eventId);if(prior){if(prior!==encoded)throw new Error('Conflicting event identity');continue;}if(event.sequence!==events.length+1)throw new Error('Session sequence gap');seen.set(event.eventId,encoded);events.push(event);}return {id,events,state:replay(events),trailingBytes:bytes.length-boundary,sha256:createHash('sha256').update(bytes.subarray(0,boundary)).digest('hex')};}
export function listSessions(root:string){if(!existsSync(root))return [];return readdirSync(root,{withFileTypes:true}).filter(d=>d.isDirectory()&&/^[\w-]+$/.test(d.name)).map(d=>{try{const h=readHistory(sessionPath(root,d.name),d.name);return {id:d.name,repository:h.state.repository,lastActivity:h.events.at(-1)?.timestamp??null,events:h.events.length,pendingEffects:Object.entries(h.state.effects).filter(([,v])=>v==='unknown').map(([k])=>k),archived:h.events.filter(e=>e.type==='session.archived').at(-1)?.payload.archived===true,status:h.state.unsupported?'unsupported':h.trailingBytes?'recovery_needed':'readable',error:null};}catch{return {id:d.name,repository:null,lastActivity:null,events:0,pendingEffects:[],archived:false,status:'corrupt',error:'Session history unreadable'};}}).sort((a,b)=>(b.lastActivity??'').localeCompare(a.lastActivity??'')||a.id.localeCompare(b.id));}
export function resumeSession(root:string,id:string,secrets:readonly string[]=[]){const dir=sessionPath(root,id);if(!existsSync(join(dir,'events.jsonl')))throw new Error('Session not found');const store=new SessionStore(dir,id,secrets);try{store.append('session.resumed',{sourceSequence:store.events.length});return store;}catch(e){store.close();throw e;}}
export function forkSession(root:string,sourceId:string,newId:string,secrets:readonly string[]=[]){const source=readHistory(sessionPath(root,sourceId),sourceId);if(source.state.unsupported||source.trailingBytes)throw new Error('Reconcile source history before fork');const directory=sessionPath(root,newId);mkdirSync(directory,{mode:0o700});const ids=new Map(source.events.map(e=>[e.eventId,Bun.randomUUIDv7()]));const copied=source.events.map(e=>({...e,sessionId:newId,eventId:ids.get(e.eventId)!,...(e.causedBy?{causedBy:ids.get(e.causedBy)??e.causedBy}:{})}));atomicJSONL(join(directory,'events.jsonl'),copied);const store=new SessionStore(directory,newId,secrets);try{store.append('session.forked',{sourceSessionId:sourceId,sourceSequence:source.events.length,sourceHash:source.sha256});return store;}catch(e){store.close();throw e;}}
export function atomicJSONL(path:string,values:readonly unknown[]):void{const temporary=path+'.'+Bun.randomUUIDv7()+'.tmp';writeFileSync(temporary,values.map(v=>JSON.stringify(v)).join('\n')+'\n',{mode:0o600,flag:'wx'});const fd=openSync(temporary,'r');try{fsyncSync(fd);}finally{closeSync(fd);}renameSync(temporary,path);}
export function exportSession(root:string,id:string){const history=readHistory(sessionPath(root,id),id);return {format:'mavona-session-export',version:1,sessionId:id,exportedAt:new Date().toISOString(),throughSequence:history.events.length,canonicalHash:history.sha256,pendingEffects:Object.entries(history.state.effects).filter(([,v])=>v==='unknown').map(([effectId])=>effectId),authentication:'excluded',effectReplay:'never',events:history.events};}
