import {readdirSync,lstatSync,readFileSync,realpathSync,unlinkSync,existsSync} from 'node:fs';import {join,relative,resolve,isAbsolute} from 'node:path';import {createHash} from 'node:crypto';import {SessionStore} from './store';
export const retentionDefaults={warningBytes:2*1024**3,hardBytes:5*1024**3,archiveAfterDays:30,expireAfterDays:90} as const;
export function diskUsage(root:string){const totals={metadata:0,screenshots:0,video:0,traces:0,other:0,total:0};let count=0;const actualRoot=realpathSync(root);function visit(path:string,depth:number){if(depth>30)throw new Error('Retention scan depth limit');const before=lstatSync(path);if(!before.isDirectory()||before.isSymbolicLink())throw new Error('Retention directory unavailable or symlink refused');const canonical=realpathSync(path),rel=relative(actualRoot,canonical);if(rel.startsWith('..')||isAbsolute(rel))throw new Error('Retention directory escaped storage');for(const entry of readdirSync(path,{withFileTypes:true})){if(++count>100000)throw new Error('Retention scan entry limit');const p=join(path,entry.name);const metadata=lstatSync(p);if(metadata.isSymbolicLink())continue;if(metadata.isDirectory()){visit(p,depth+1);continue;}if(!metadata.isFile())continue;const size=metadata.size;if(!Number.isSafeInteger(size)||size<0)throw new Error('Invalid storage size');const kind=/\.(png|jpe?g|webp)$/i.test(entry.name)?'screenshots':/\.(webm|mp4)$/i.test(entry.name)?'video':/\.zip$/i.test(entry.name)?'traces':/\.(jsonl?|sqlite)(-(wal|shm))?$/.test(entry.name)?'metadata':'other';totals[kind]+=size;totals.total+=size;if(!Number.isSafeInteger(totals.total))throw new Error('Storage total exceeds safe integer');}const after=lstatSync(path);if(after.isSymbolicLink()||before.dev!==after.dev||before.ino!==after.ino||realpathSync(path)!==canonical)throw new Error('Storage directory changed during scan');}visit(root,0);return totals;}
export function checkCaptureBudget(currentBytes:number,incomingBytes:number,limits:{warningBytes:number;hardBytes:number}=retentionDefaults){if(![currentBytes,incomingBytes,limits.warningBytes,limits.hardBytes].every(n=>Number.isSafeInteger(n)&&n>=0)||limits.hardBytes===0)throw new Error('Invalid artifact budget');const projected=currentBytes+incomingBytes;return {state:projected>=limits.hardBytes?'blocked' as const:projected>=Math.min(limits.warningBytes,limits.hardBytes*0.8)?'warning' as const:'allowed' as const,projectedBytes:projected,hardBytes:limits.hardBytes,requiredCheckAtLimit:'unknown' as const};}
export function archiveOffer(lastActivityMs:number,pinned:boolean,active:boolean,now=Date.now()):boolean{return !pinned&&!active&&now-lastActivityMs>=retentionDefaults.archiveAfterDays*86400000;}
export interface RetainedArtifact {id:string;path:string;sha256:string;provenance:string;createdAt:string}
function artifactPath(root:string,a:RetainedArtifact):string {const base=resolve(root);const path=resolve(base,a.path);const rel=relative(base,path);if(!rel||rel.startsWith('..')||isAbsolute(rel)||!a.id||!/^[a-f0-9]{64}$/.test(a.sha256))throw new Error('Invalid artifact containment');if(!existsSync(path))return path;const actual=realpathSync(path),actualRoot=realpathSync(root),realRel=relative(actualRoot,actual);if(realRel.startsWith('..')||isAbsolute(realRel)||lstatSync(path).isSymbolicLink()||!lstatSync(path).isFile())throw new Error('Artifact containment changed');return path;}
export function artifactAvailability(store:SessionStore,a:RetainedArtifact):'available'|'expired'|'unavailable'{if(store.events.some(e=>e.type==='artifact.expired'&&e.payload.artifactId===a.id&&e.payload.sha256===a.sha256))return 'expired';try{const p=artifactPath(store.directory,a);if(!existsSync(p))return 'unavailable';return createHash('sha256').update(readFileSync(p)).digest('hex')===a.sha256?'available':'unavailable';}catch{return 'unavailable';}}
export function expireArtifact(store:SessionStore,a:RetainedArtifact,policy:{optIn:boolean;pinned:boolean;now:number;reason?:string}):void{if(!policy.optIn)throw new Error('Artifact expiry requires explicit opt-in');if(policy.pinned)throw new Error('Do not expire pinned session artifacts');const age=policy.now-Date.parse(a.createdAt);if(!Number.isFinite(age)||age<retentionDefaults.expireAfterDays*86400000)throw new Error('Artifact retention period has not elapsed');const path=artifactPath(store.directory,a);if(artifactAvailability(store,a)!=='available')throw new Error('Artifact unavailable or already expired');store.append('artifact.expired',{artifactId:a.id,sha256:a.sha256,provenance:a.provenance,expiredAt:new Date(policy.now).toISOString(),reason:policy.reason??'Explicit retention policy'});unlinkSync(path);}
