import {buildInputs,requireCurrentBuild} from '../packages/distribution/build-inputs';
import {mkdtemp,mkdir,readFile,writeFile,copyFile,chmod,rm} from 'node:fs/promises';import {resolve,join} from 'node:path';import {tmpdir} from 'node:os';import {dependencyInventory} from '../packages/distribution/inventory';import {digest} from '../packages/tools/source';
const root=resolve(import.meta.dir,'..');const args=process.argv.slice(2);if(args.length!==2||args[0]!=='--output')throw new Error('Use bun scripts/package.ts --output /absolute/new-directory');const output=resolve(args[1]!);const target=process.platform+'-'+process.arch;if(!['darwin-arm64','darwin-x64','linux-arm64','linux-x64'].includes(target))throw new Error('Unsupported native packaging target');
const command=async(argv:string[])=>{const child=Bun.spawn(argv,{cwd:root,env:{PATH:'/usr/bin:/bin',LANG:'C.UTF-8'},stdout:'pipe',stderr:'pipe'});const [stdout,stderr,code]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);if(code!==0)throw new Error('Packaging command failed: '+argv[0]+' '+stderr.slice(0,500));return stdout;};
if(process.platform==='linux')await command(['getconf','GNU_LIBC_VERSION']);
const inventory=await dependencyInventory(root);const version=inventory.project.version;if(!/^\d+\.\d+\.\d+(?:[-.][a-zA-Z0-9.-]+)?$/.test(version))throw new Error('Invalid version');const binary=join(root,'dist/mavona');const observedVersion=(await command([binary,'--version'])).trim();if(!observedVersion.includes('mavona '+version))throw new Error('Binary version mismatch');const binaryHash=digest(await readFile(binary));
const inputs=await buildInputs(root);const built=requireCurrentBuild(JSON.parse(await readFile(join(root,'dist/build-info.json'),'utf8')),inputs,target,binaryHash);const created=new Date().toISOString().replace(/\.\d{3}Z$/,'Z');const name='mavona-'+version+'-'+target;await mkdir(output);const staging=await mkdtemp(join(tmpdir(),'mavona-package-'));
try{const directory=join(staging,name);await mkdir(directory);await copyFile(binary,join(directory,'mavona'));await chmod(join(directory,'mavona'),0o755);for(const file of ['LICENSE','README.md'])await copyFile(join(root,file),join(directory,file));for(const file of ['install.sh','uninstall.sh']){await copyFile(join(root,'distribution',file),join(directory,file));await chmod(join(directory,file),0o755);}
 const sbom={spdxVersion:'SPDX-2.3',dataLicense:'CC0-1.0',SPDXID:'SPDXRef-DOCUMENT',name,documentNamespace:'https://spdx.org/spdxdocs/'+name+'-'+crypto.randomUUID(),creationInfo:{created,creators:['Tool: Mavona-local-packager-1']},comment:'Installed npm runtime/build dependency inventory and Bun runtime. Embedded third-party internals of Bun are not independently enumerated; this inventory is not a completeness or vulnerability attestation.',packages:[...inventory.packages,{SPDXID:'SPDXRef-Bun',name:'bun',versionInfo:Bun.version,downloadLocation:'NOASSERTION',filesAnalyzed:false,licenseConcluded:'NOASSERTION',licenseDeclared:'MIT',copyrightText:'NOASSERTION'}],relationships:[{spdxElementId:'SPDXRef-DOCUMENT',relationshipType:'DESCRIBES',relatedSpdxElement:'SPDXRef-Mavona'},...inventory.relationships,{spdxElementId:'SPDXRef-Mavona',relationshipType:'DEPENDS_ON',relatedSpdxElement:'SPDXRef-Bun'}]};
 const provenance={schemaVersion:1,buildId:crypto.randomUUID(),created,target,version,bun:Bun.version,...inputs,builtAt:built.builtAt,binarySha256:binaryHash,startupObserved:observedVersion,signature:'not signed',notarization:'not performed',releaseAcceptance:'implementing; see docs/RELEASE_ACCEPTANCE.md',unavailableOptionalPackages:inventory.unavailableOptional};
 await writeFile(join(directory,'BINARY_SHA256'),binaryHash+'\n');await writeFile(join(directory,'TARGET'),target+'\n');await writeFile(join(directory,'sbom.spdx.json'),JSON.stringify(sbom,null,2)+'\n');await writeFile(join(directory,'provenance.json'),JSON.stringify(provenance,null,2)+'\n');await writeFile(join(directory,'THIRD_PARTY_NOTICES.txt'),inventory.notices+'\n');await copyFile(join(root,'docs/RELEASE_ACCEPTANCE.md'),join(directory,'RELEASE_ACCEPTANCE.md'));
 await command(['tar','-czf',join(output,name+'.tar.gz'),'-C',staging,name]);const archiveHash=digest(await readFile(join(output,name+'.tar.gz')));await writeFile(join(output,'SHA256SUMS'),archiveHash+'  '+name+'.tar.gz\n');await copyFile(join(directory,'provenance.json'),join(output,'provenance.json'));await copyFile(join(directory,'sbom.spdx.json'),join(output,'sbom.spdx.json'));
 const formula=`# Input only: replace the URL after authorized publication; this artifact is unsigned.\nclass Mavona < Formula\n  desc "Rails-specific coding harness"\n  homepage "https://github.com/Doppp/mavona"\n  url "REPLACE_WITH_AUTHORIZED_ARTIFACT_URL/${name}.tar.gz"\n  version "${version}"\n  sha256 "${archiveHash}"\n  license "MIT"\n  def install\n    odie \"This artifact is ${target} only\" unless ${process.platform==='darwin'?'OS.mac?':'OS.linux?'} && Hardware::CPU.arch == :${process.arch==='arm64'?'arm64':'x86_64'}\n    bin.install "mavona"\n  end\n  test do\n    assert_match "mavona ${version}", shell_output("#{bin}/mavona --version")\n  end\nend\n`;await writeFile(join(output,'mavona.rb.in'),formula);console.log(JSON.stringify({output,target,archive:name+'.tar.gz',sha256:archiveHash,packages:sbom.packages.length,sourceDirty:provenance.sourceDirty,signed:false}));
}finally{await rm(staging,{recursive:true,force:true});}
