import {open,realpath} from 'node:fs/promises';import {constants} from 'node:fs';import {join} from 'node:path';
import {parseArguments,single} from './options';import {dataDirectory} from './run';
import {parseFlow,digestFlow,doctor,approveFlow} from '../app-inspection/service';
import {SessionStore} from '../sessions/store';import {runInspection} from '../agent/inspection';
import {createHash} from 'node:crypto';
export async function readFlow(path:string){const file=await open(path,constants.O_RDONLY|constants.O_NOFOLLOW);try{const metadata=await file.stat();if(!metadata.isFile()||metadata.size>1024*1024)throw new Error('Flow exceeds file budget');const bytes=Buffer.alloc(1024*1024+1);const {bytesRead}=await file.read(bytes,0,bytes.length,0);if(bytesRead>1024*1024)throw new Error('Flow exceeds file budget');return parseFlow(JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes.subarray(0,bytesRead))));}finally{await file.close();}}
export async function appCommand(raw:string[]):Promise<number>{
 const operation=raw[0];const args=parseArguments(raw.slice(1),['flow','url','root','data-dir','format','approve-flow','browser','trace-file','profile','color-scheme','reduced-motion','session','inspection','destination','approve-export','approve-rerun','before','after'],['summary','headed','dry-run','trace','video','start-server']);
 if(args.positionals.length)throw new Error('Unexpected browser arguments');
 if(operation==='compare'){const session=single(args,'session'),before=single(args,'before'),after=single(args,'after');if(!session||!before||!after)throw new Error('Use app compare --session ID --before CAPTURE_ID --after CAPTURE_ID');const {sessionPath,readHistory}=await import('../sessions/lifecycle');const directory=sessionPath(join(single(args,'data-dir',dataDirectory())!,'sessions'),session);const history=readHistory(directory,session);const {compareRecordedCaptures,startComparisonViewer}=await import('../app-inspection/comparison');const pair=await compareRecordedCaptures(directory,history.events,before,after);if(args.flags.has('summary')){console.log(JSON.stringify({schemaVersion:1,...pair.summary},null,2));return 4;}const viewer=startComparisonViewer(pair);console.log(JSON.stringify({schemaVersion:1,status:'ready',comparison:pair.summary,url:viewer.url,stop:'Ctrl+C'}));await new Promise<void>(resolve=>{const stop=()=>{process.off('SIGINT',stop);process.off('SIGTERM',stop);viewer.stop();resolve();};process.on('SIGINT',stop);process.on('SIGTERM',stop);});return 0;}
 if(operation==='rerun'){const session=single(args,'session'),inspection=single(args,'inspection');if(!session||!inspection)throw new Error('Use app rerun --session ID --inspection ID');const {sessionPath,readHistory}=await import('../sessions/lifecycle');const directory=sessionPath(join(single(args,'data-dir',dataDirectory())!,'sessions'),session);const history=readHistory(directory,session);const {prepareRerun,rerunInspection}=await import('../app-inspection/rerun');const review=await prepareRerun({events:history.events},inspection);if(single(args,'approve-rerun')!==review.id){console.log(JSON.stringify({schemaVersion:1,status:'approval_required',review},null,2));return 2;}const store=new SessionStore(directory,session);const controller=new AbortController();const cancel=()=>controller.abort();process.on('SIGINT',cancel);process.on('SIGTERM',cancel);try{const result=await rerunInspection(store,inspection,review.id,controller.signal);console.log(JSON.stringify(result));return result.exitCode;}finally{process.off('SIGINT',cancel);process.off('SIGTERM',cancel);store.close();}}
 if(operation==='export'){const session=single(args,'session'),inspection=single(args,'inspection'),destination=single(args,'destination');if(!session||!inspection||!destination)throw new Error('Use app export --session ID --inspection ID --destination /new/file.tar.gz');const {sessionPath,readHistory}=await import('../sessions/lifecycle');const directory=sessionPath(join(single(args,'data-dir',dataDirectory())!,'sessions'),session);const history=readHistory(directory,session);const {prepareReportExport,exportReport}=await import('../app-inspection/export');const review=await prepareReportExport(directory,history.events,inspection,destination);if(single(args,'approve-export')!==review.id){console.log(JSON.stringify({schemaVersion:1,status:'approval_required',review},null,2));return 2;}const store=new SessionStore(directory,session);const controller=new AbortController();const cancel=()=>controller.abort();process.on('SIGINT',cancel);process.on('SIGTERM',cancel);try{const result=await exportReport(store,inspection,destination,review.id,controller.signal);console.log(JSON.stringify({schemaVersion:1,...result}));return result.status==='passed'?0:4;}finally{process.off('SIGINT',cancel);process.off('SIGTERM',cancel);store.close();}}
 if(operation==='report'){const session=single(args,'session'),inspection=single(args,'inspection');if(!session||!inspection)throw new Error('Use app report --session ID --inspection ID');const {sessionPath,readHistory}=await import('../sessions/lifecycle');const directory=sessionPath(join(single(args,'data-dir',dataDirectory())!,'sessions'),session);const history=readHistory(directory,session);const {loadReportBundle,startReportViewer}=await import('../app-inspection/report-viewer');const viewer=startReportViewer(await loadReportBundle(directory,history.events,inspection));console.log(JSON.stringify({schemaVersion:1,status:'ready',url:viewer.url,scope:'immutable local inspection report',stop:'Ctrl+C'}));await new Promise<void>(resolve=>{const stop=()=>{process.off('SIGINT',stop);process.off('SIGTERM',stop);viewer.stop();resolve();};process.on('SIGINT',stop);process.on('SIGTERM',stop);});return 0;}
 if(operation==='replay'){const path=single(args,'trace-file');if(!path)throw new Error('Use app replay --trace-file PATH');const {startTraceViewer}=await import('../app-inspection/viewer');const viewer=await startTraceViewer(path);console.log(JSON.stringify({schemaVersion:1,status:'ready',url:viewer.url,scope:'local offline trace replay',stop:'Ctrl+C'}));await new Promise<void>(resolve=>{const stop=()=>{process.off('SIGINT',stop);process.off('SIGTERM',stop);viewer.stop();resolve();};process.on('SIGINT',stop);process.on('SIGTERM',stop);});return 0;}
 if(operation==='install'){const {browserInstall}=await import('./browser-install');return browserInstall(single(args,'browser','chromium')!,args.flags.has('dry-run'));}
 if(operation==='doctor'){console.log(JSON.stringify({schemaVersion:1,engines:await doctor()},null,2));return 0;}
 if(operation!=='run'&&operation!=='inspect')throw new Error('Use app doctor, app run --flow PATH, or app inspect --url URL');
 const root=await realpath(single(args,'root',process.cwd())!);const format=single(args,'format','json');if(format!=='json'&&format!=='jsonl')throw new Error('Unsupported inspection output format');
 const path=single(args,'flow');const url=single(args,'url');if(operation==='run'&&!path||operation==='inspect'&&!url)throw new Error('Inspection flow or URL required');
 const flow=path?await readFlow(path):parseFlow({version:1,url,headed:args.flags.has('headed'),steps:[{op:'observe'},{op:'capture'}]});
 const profile=single(args,'profile'),browser=single(args,'browser'),scheme=single(args,'color-scheme'),motion=single(args,'reduced-motion');Object.assign(flow,parseFlow({...flow,...(profile?{profile}:{}),...(browser?{browser}:{}),...(scheme?{colorScheme:scheme}:{}),...(motion?{reducedMotion:motion}:{})}));
 for(const kind of ['trace','video'] as const)if(args.flags.has(kind))flow.evidence={...flow.evidence,[kind]:true};
 if(args.flags.has('headed'))flow.headed=true;const grant=approveFlow(flow,root,'explicit-user'),startOwned=args.flags.has('start-server');if(startOwned&&operation!=='inspect')throw new Error('--start-server is supported with app inspect');const {discoverBootCommands,startServer,spawnOwnedServer,ServerUnavailableError}=await import('../app-inspection/lifecycle');const boot=startOwned?(await discoverBootCommands(root,flow.url))[0]:undefined;if(startOwned&&!boot)throw new Error('No Rails boot command discovered');const approvalDigest=boot?createHash('sha256').update(JSON.stringify({flowDigest:digestFlow(flow),server:{ownership:'owned',argv:boot}})).digest('hex'):digestFlow(flow),approved=single(args,'approve-flow');
 if(approved!==approvalDigest){console.log(JSON.stringify({schemaVersion:1,status:'approval_required',correctness:'unknown',approval:{flowDigest:approvalDigest,browserFlowDigest:grant.flowDigest,checkout:root,origins:grant.origins,flow,server:boot?{ownership:'owned',argv:boot}:{ownership:'attached',url:flow.url},warning:'Browser navigation and actions can mutate the development application. Starting executes the displayed Rails argv in test mode. Review the complete scope, then pass its exact digest with --approve-flow.'}},null,2));return 2;}
 const id=Bun.randomUUIDv7();const store=new SessionStore(join(single(args,'data-dir',dataDirectory())!,'sessions',id),id);store.append('session.opened',{repository:root});
 const controller=new AbortController();const cancel=()=>controller.abort();process.on('SIGINT',cancel);process.on('SIGTERM',cancel);
 try{const result=await runInspection({root,flow,...(path?{flowPath:path}:{}),store,signal:controller.signal,...(boot?{server:()=>startServer(flow.url,()=>spawnOwnedServer(root,boot),{signal:controller.signal})}:{}),onEvent:event=>{if(format==='jsonl')console.log(JSON.stringify(event));}});console.log(JSON.stringify(format==='jsonl'?{schemaVersion:1,type:'inspection.result',result}:result));return result.exitCode;}catch(error){if(!(error instanceof ServerUnavailableError))throw error;const result={schemaVersion:1,status:'unavailable',correctness:'unknown',reason:error.message,server:boot?{ownership:'owned'}:{ownership:'attached'}};console.log(JSON.stringify(format==='jsonl'?{schemaVersion:1,type:'inspection.result',result}:result));return 4;}
 finally{store.close();process.off('SIGINT',cancel);process.off('SIGTERM',cancel);}
}
