import {join} from 'node:path';
import {parseArguments,single} from './options';
import {dataDirectory} from './run';
import {createSession,listSessions,sessionPath,readHistory,exportSession,forkSession,resumeSession} from '../sessions/lifecycle';
export async function sessionCommand(raw:string[],resume=false):Promise<number>{
 const args=parseArguments(raw,['data-dir','format','effect','reason','review','recovery','approve-restore','approve-dispose','title','root'],[]);const format=single(args,'format','json');if(format!=='json')throw new Error('Session output supports json');
 const root=join(single(args,'data-dir',dataDirectory())!,'sessions');const operation=resume?'resume':args.positionals.shift()??'list';
 const id=args.positionals.shift();if(args.positionals.length)throw new Error('Unexpected session arguments');
 if(operation==='list'){if(id)throw new Error('List takes no session ID');console.log(JSON.stringify({schemaVersion:1,sessions:listSessions(root)},null,2));return 0;}
 if(operation==='new'){if(id)throw new Error('New session assigns its own stable ID');const store=createSession(root,single(args,'root',process.cwd())!);try{console.log(JSON.stringify({schemaVersion:1,id:store.sessionId,repository:store.state.repository,correctness:'unknown',effectReplay:'never'}));return 0;}finally{store.close();}}
 if(!id)throw new Error('Session ID required');
 if(operation==='storage'){const {storageStatus}=await import('../sessions/storage');console.log(JSON.stringify(storageStatus(sessionPath(root,id),single(args,'data-dir',dataDirectory())!),null,2));}
 else if(operation==='recovery'){const history=readHistory(sessionPath(root,id),id);const {retainedDeletions}=await import('../tools/recovery');console.log(JSON.stringify({schemaVersion:1,recoveries:retainedDeletions(history.events),availability:'not checked until preview'},null,2));}
 else if(operation==='restore'){const recovery=single(args,'recovery');if(!recovery)throw new Error('Use sessions restore ID --recovery COMPLETION_EVENT_ID');const directory=sessionPath(root,id);const history=readHistory(directory,id);const {SessionStore}=await import('../sessions/store');const {prepareRestoration,restoreSource}=await import('../tools/recovery');const review=await prepareRestoration({events:history.events},recovery);if(single(args,'approve-restore')!==review.id){console.log(JSON.stringify({schemaVersion:1,status:'approval_required',review},null,2));return 2;}const store=new SessionStore(directory,id);const controller=new AbortController();const cancel=()=>controller.abort();process.on('SIGINT',cancel);process.on('SIGTERM',cancel);try{const result=await restoreSource(store,recovery,review.id,controller.signal);console.log(JSON.stringify({schemaVersion:1,...result}));return result.state==='passed'?0:4;}finally{process.off('SIGINT',cancel);process.off('SIGTERM',cancel);store.close();}}
 else if(operation==='dispose'){const recovery=single(args,'recovery');if(!recovery)throw new Error('Use sessions dispose ID --recovery COMPLETION_EVENT_ID');const directory=sessionPath(root,id);const history=readHistory(directory,id);const {SessionStore}=await import('../sessions/store');const {prepareDisposal,disposeSource}=await import('../tools/disposal');const review=await prepareDisposal({events:history.events},recovery);if(single(args,'approve-dispose')!==review.id){console.log(JSON.stringify({schemaVersion:1,status:'approval_required',review},null,2));return 2;}const store=new SessionStore(directory,id);const controller=new AbortController();const cancel=()=>controller.abort();process.on('SIGINT',cancel);process.on('SIGTERM',cancel);try{const result=await disposeSource(store,recovery,review.id,controller.signal);console.log(JSON.stringify({schemaVersion:1,...result}));return result.state==='passed'?0:4;}finally{process.off('SIGINT',cancel);process.off('SIGTERM',cancel);store.close();}}
 else if(operation==='rename'||operation==='pin'||operation==='unpin'){const {renameSession,pinSession}=await import('../sessions/metadata');const title=single(args,'title');if(operation==='rename'&&!title)throw new Error('Use sessions rename ID --title TITLE');const {SessionStore}=await import('../sessions/store');const directory=sessionPath(root,id);readHistory(directory,id);const store=new SessionStore(directory,id);try{const metadata=operation==='rename'?renameSession(store,title!):pinSession(store,operation==='pin');console.log(JSON.stringify({schemaVersion:1,id,...metadata}));}finally{store.close();}}
 else if(operation==='show'){const history=readHistory(sessionPath(root,id),id);console.log(JSON.stringify({schemaVersion:1,...history},null,2));}
 else if(operation==='export')console.log(JSON.stringify(exportSession(root,id),null,2));
 else if(operation==='fork'){const store=forkSession(root,id,Bun.randomUUIDv7());try{console.log(JSON.stringify({schemaVersion:1,id:store.sessionId,mutationAllowed:store.state.mutationAllowed,source:id}));}finally{store.close();}}
 else if(operation==='adopt'){const reviewId=single(args,'review'),reason=single(args,'reason');if(!reviewId||!reason)throw new Error('Use sessions adopt ID --review REVIEW_SHA256 --reason reviewed-criteria');const store=resumeSession(root,id);try{const {adoptRecordedAcceptance}=await import('../verification/adoption');await adoptRecordedAcceptance(store,reviewId,reason);console.log(JSON.stringify({schemaVersion:1,id,reviewId,adopted:true,correctness:'unknown',verificationFresh:false}));}finally{store.close();}}
 else if(operation==='reconcile'){const effect=single(args,'effect'),reason=single(args,'reason');if(!effect||!reason)throw new Error('Use sessions reconcile ID --effect EFFECT_ID --reason inspected-current-state');const store=resumeSession(root,id);try{const {reconcileEffect}=await import('../sessions/reconciliation');console.log(JSON.stringify({schemaVersion:1,id,...await reconcileEffect(store,effect,reason)}));}finally{store.close();}}
 else if(operation==='resume'){
  const store=resumeSession(root,id);
  if(process.stdin.isTTY&&!args.values.has('format')){try{const {startTui}=await import('../tui/start');await startTui(store);}catch(error){store.close();throw error;}}
  else {try{console.log(JSON.stringify({schemaVersion:1,id,...store.state,effectReplay:'never',verificationFresh:false}));}finally{store.close();}}
 }else if(operation==='archive'||operation==='unarchive'){
  const store=resumeSession(root,id);try{store.append('session.archived',{archived:operation==='archive'});console.log(JSON.stringify({schemaVersion:1,id,archived:operation==='archive'}));}finally{store.close();}
 }else throw new Error('Unknown session operation');
 return 0;
}
