import {constants} from 'node:fs';
import {open,realpath,stat} from 'node:fs/promises';
import {relative} from 'node:path';
import type {Envelope} from '../protocol/events';
import type {SessionStore} from '../sessions/store';
import {containedPath,digest,readSource} from '../tools/source';
import {compareImages,type CaptureConditions} from './images';
import {loadRecordedCapture} from './comparison';

export type VisualBaselineConfig={version:1;checkId:string;baselinePath:string;baselineSha256:string;conditions:CaptureConditions;maxChangedPixelRatio:number;channelTolerance?:number;required:boolean};
const object=(value:unknown):Record<string,unknown>=>{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Expected visual baseline object');return value as Record<string,unknown>;};
const exact=(value:Record<string,unknown>,keys:string[])=>{for(const key of Object.keys(value))if(!keys.includes(key))throw new Error('Unknown visual baseline field: '+key);};
function parseConditions(value:unknown):CaptureConditions{const raw=object(value);exact(raw,['engine','viewport','fixtureRevision','fontsDigest','captureSettingsDigest']);const viewport=object(raw.viewport);exact(viewport,['width','height']);for(const item of [raw.engine,raw.fixtureRevision,raw.fontsDigest,raw.captureSettingsDigest])if(typeof item!=='string'||!item||item.length>256)throw new Error('Invalid visual capture conditions');for(const item of [viewport.width,viewport.height])if(!Number.isInteger(item)||Number(item)<1||Number(item)>16000)throw new Error('Invalid visual viewport');return {engine:raw.engine as string,viewport:{width:viewport.width as number,height:viewport.height as number},fixtureRevision:raw.fixtureRevision as string,fontsDigest:raw.fontsDigest as string,captureSettingsDigest:raw.captureSettingsDigest as string};}
export function parseVisualBaseline(value:unknown):VisualBaselineConfig{const raw=object(value);exact(raw,['version','checkId','baselinePath','baselineSha256','conditions','maxChangedPixelRatio','channelTolerance','required']);if(raw.version!==1||typeof raw.checkId!=='string'||!/^[A-Za-z0-9_.:-]{1,120}$/.test(raw.checkId)||typeof raw.baselinePath!=='string'||!raw.baselinePath||raw.baselinePath.length>4096||typeof raw.baselineSha256!=='string'||!/^[a-f0-9]{64}$/.test(raw.baselineSha256)||typeof raw.required!=='boolean'||typeof raw.maxChangedPixelRatio!=='number'||!Number.isFinite(raw.maxChangedPixelRatio)||raw.maxChangedPixelRatio<0||raw.maxChangedPixelRatio>1)throw new Error('Invalid visual baseline configuration');if(raw.channelTolerance!==undefined&&(!Number.isInteger(raw.channelTolerance)||Number(raw.channelTolerance)<0||Number(raw.channelTolerance)>255))throw new Error('Invalid visual baseline threshold');return {version:1,checkId:raw.checkId,baselinePath:raw.baselinePath,baselineSha256:raw.baselineSha256,conditions:parseConditions(raw.conditions),maxChangedPixelRatio:raw.maxChangedPixelRatio,...(raw.channelTolerance!==undefined?{channelTolerance:raw.channelTolerance as number}:{}),required:raw.required};}
async function readBaseline(root:string,path:string){const canonicalRoot=await realpath(root),canonical=await containedPath(canonicalRoot,path),file=await open(canonical,constants.O_RDONLY|constants.O_NOFOLLOW);try{const before=await file.stat();if(!before.isFile()||before.nlink!==1||before.size<24||before.size>100*1024*1024)throw new Error('Invalid visual baseline file');const bytes=Buffer.alloc(Number(before.size));let offset=0;while(offset<bytes.length){const result=await file.read(bytes,offset,bytes.length-offset,offset);if(!result.bytesRead)break;offset+=result.bytesRead;}const after=await file.stat(),current=await stat(canonical);if(offset!==bytes.length||before.dev!==after.dev||before.ino!==after.ino||before.size!==after.size||before.mtimeMs!==after.mtimeMs||current.dev!==before.dev||current.ino!==before.ino||await realpath(root)!==canonicalRoot)throw new Error('Visual baseline changed while reading');return {path:relative(canonicalRoot,canonical),bytes,sha256:digest(bytes)};}finally{await file.close();}}
export async function prepareBaselineReview(input:{root:string;directory:string;events:readonly Envelope[];captureId:string;configPath:string}){const configSource=await readSource(input.root,input.configPath,64*1024),config=parseVisualBaseline(JSON.parse(configSource.text)),baseline=await readBaseline(input.root,config.baselinePath),capture=await loadRecordedCapture(input.directory,input.events,input.captureId);if(baseline.sha256!==config.baselineSha256)throw new Error('Configured baseline digest changed');const review={version:1 as const,scope:'read-only deterministic visual baseline comparison',repository:await realpath(input.root),config:{path:configSource.path,sha256:configSource.digest,value:config},baseline:{path:baseline.path,sha256:baseline.sha256,size:baseline.bytes.length},capture:{id:capture.id,inspectionId:capture.inspectionId,sha256:capture.sha256,conditions:capture.artifact.captureConditions??null}};return {...review,id:digest(JSON.stringify(review))};}
export async function evaluateBaseline(store:SessionStore,root:string,captureId:string,configPath:string,approvedId:string){const review=await prepareBaselineReview({root,directory:store.directory,events:store.events,captureId,configPath});if(review.id!==approvedId)throw new Error('Visual baseline requires exact fresh review approval');if(store.events.some(event=>event.type==='app_assertion'&&event.payload.inspectionId===review.capture.inspectionId&&event.payload.checkId===review.config.value.checkId))throw new Error('Visual baseline check identity already recorded for this inspection');const capture=await loadRecordedCapture(store.directory,store.events,captureId),conditions=capture.artifact.captureConditions as CaptureConditions|undefined;const baseline=await readBaseline(root,review.config.value.baselinePath);const result=compareImages(baseline.bytes,capture.bytes,review.config.value.conditions,conditions??{engine:'unknown',viewport:{width:0,height:0},fixtureRevision:'unknown',fontsDigest:'unknown',captureSettingsDigest:'unknown'},{reviewedBy:review.id,maxChangedPixelRatio:review.config.value.maxChangedPixelRatio,...(review.config.value.channelTolerance!==undefined?{channelTolerance:review.config.value.channelTolerance}:{})});const check={id:review.config.value.checkId,inspectionId:capture.inspectionId,status:result.status,provenance:'configured-repository',required:review.config.value.required,detail:JSON.stringify({reason:result.reason,reviewId:review.id,config:review.config.path,baseline:review.baseline,capture:review.capture,changedPixels:result.changedPixels??null,totalPixels:result.totalPixels??null,changedPixelRatio:result.changedPixelRatio??null,threshold:review.config.value.maxChangedPixelRatio})};store.append('app_assertion',{inspectionId:capture.inspectionId,checkId:check.id,evidence:JSON.stringify(check)});return {schemaVersion:1,reviewId:review.id,check,comparison:{status:result.status,reason:result.reason,changedPixels:result.changedPixels??null,totalPixels:result.totalPixels??null,changedPixelRatio:result.changedPixelRatio??null,baselineDigest:result.baselineDigest??null,actualDigest:result.actualDigest??null},correctness:result.status};}
