import type {Envelope} from '../protocol/events';import {digest} from '../tools/source';
import {loadReportBundle,startReportViewer,type ReportBundle} from './report-viewer';import {measureImageDifference,renderComparisonView} from './images';
async function capture(directory:string,events:readonly Envelope[],id:string){
 const matches=events.filter(e=>e.schemaVersion===1&&e.type==='inspection.artifact'&&e.payload.artifactId===id);if(matches.length!==1)throw new Error('Capture identity missing or ambiguous');const event=matches[0]!;const artifact=JSON.parse(String(event.payload.evidence)) as Record<string,unknown>;if(artifact.id!==id||artifact.inspectionId!==event.payload.inspectionId||artifact.mediaType!=='image/png'||artifact.provenance!=='captured'||artifact.redaction!=='masked')throw new Error('Only recorded masked captures can be compared');
 const bundle=await loadReportBundle(directory,events,String(event.payload.inspectionId));const asset=bundle.manifest.assets.find(item=>item.artifactId===id);if(!asset||asset.sha256!==artifact.sha256||asset.path!==event.payload.managedPath||asset.mediaType!=='image/png')throw new Error('Capture manifest mismatch');const bytes=bundle.files.get(asset.name)!;if(bytes.length<24||bytes.readUInt32BE(16)*bytes.readUInt32BE(20)>8000000)throw new Error('Comparison capture pixel budget exceeded');return {eventId:event.eventId,sessionId:event.sessionId,id,inspectionId:String(event.payload.inspectionId),sha256:asset.sha256,bytes};
}
export async function compareRecordedCaptures(directory:string,events:readonly Envelope[],beforeId:string,afterId:string){
 if(beforeId===afterId)throw new Error('Choose two distinct capture identities');const before=await capture(directory,events,beforeId),after=await capture(directory,events,afterId);if(before.sessionId!==after.sessionId)throw new Error('Capture sessions differ');const measured=measureImageDifference(before.bytes,after.bytes);const id=digest(JSON.stringify([before.eventId,after.eventId]));const reference=(item:typeof before)=>({id:item.id,inspectionId:item.inspectionId,sha256:item.sha256});const summary={id,status:'unknown' as const,comparability:'unknown' as const,reason:'Fixture, fonts and capture conditions have not been established as comparable; no reviewed baseline is selected.',before:reference(before),after:reference(after),...(measured.changedPixels!==undefined?{changedPixels:measured.changedPixels,totalPixels:measured.totalPixels,changedPixelRatio:measured.changedPixelRatio}:{}),measurementReason:measured.reason,correctness:'unknown' as const};
 const files=new Map<string,Buffer>([['before.png',before.bytes],['after.png',after.bytes]]);if(measured.difference)files.set('difference.png',measured.difference);const html=renderComparisonView(before.bytes,after.bytes,{...measured,status:'unknown',reason:summary.reason},{assets:{before:'before.png',after:'after.png',...(measured.difference?{difference:'difference.png'}:{})},description:`Before ${before.id} SHA256 ${before.sha256}. After ${after.id} SHA256 ${after.sha256}. Raw pixel counts are diagnostic; functional and accessibility verification remain unknown.`});files.set('report.html',Buffer.from(html));
 const bundle:ReportBundle={manifest:{version:1,sessionId:before.sessionId,inspectionId:id,assets:[...files].map(([name,bytes])=>({artifactId:name==='before.png'?before.id:name==='after.png'?after.id:id+':'+name,name,path:name,sha256:digest(bytes),size:bytes.length,mediaType:name.endsWith('.html')?'text/html':'image/png',redaction:'masked'}))},files};return {summary,bundle};
}
export function startComparisonViewer(pair:Awaited<ReturnType<typeof compareRecordedCaptures>>){return startReportViewer(pair.bundle);}
export function comparisonChoices(events:readonly Envelope[]){return events.filter(e=>e.schemaVersion===1&&e.type==='inspection.artifact'&&typeof e.payload.artifactId==='string'&&/^[a-f0-9-]{1,128}$/.test(e.payload.artifactId)).slice(-100).reverse().map(event=>({id:'capture:'+String(event.payload.artifactId),path:String(event.payload.artifactId)+' · inspection '+JSON.stringify(event.payload.inspectionId)}));}
