import {prepareExportDestination,publishExport} from '../sessions/export-publication';
import {realpath} from 'node:fs/promises';import {dirname,basename} from 'node:path';
import {loadReportBundle} from './report-viewer';import {mutationScope,type MutationScope} from '../tools/mutation-path';import {digest} from '../tools/source';import type {Envelope} from '../protocol/events';import type {SessionStore} from '../sessions/store';
export interface ExportReview {id:string;inspectionId:string;destination:string;format:'tar.gz';files:{redaction:string;artifactId:string;name:string;sha256:string;size:number}[];totalBytes:number;parentIdentity:MutationScope['rootIdentity'];scope:'local portable evidence; excludes report JSON and authentication state; no upload'}
async function plan(directory:string,events:readonly Envelope[],inspectionId:string,destination:string){
 const target=await prepareExportDestination(directory,destination,'.tar.gz');const {parent,scope}=target;const bundle=await loadReportBundle(directory,events,inspectionId);const files=bundle.manifest.assets.map(({artifactId,name,sha256,size,redaction})=>({artifactId,name,sha256,size,redaction:redaction??'unknown'}));const value={inspectionId,destination:target.destination,format:'tar.gz' as const,files,totalBytes:files.reduce((sum,file)=>sum+file.size,0),parentIdentity:scope.rootIdentity,scope:'local portable evidence; excludes report JSON and authentication state; no upload' as const};return {bundle,scope,parent,review:{id:digest(JSON.stringify(value)),...value}};
}
export async function prepareReportExport(directory:string,events:readonly Envelope[],inspectionId:string,destination:string):Promise<ExportReview>{return (await plan(directory,events,inspectionId,destination)).review;}
export async function exportReport(store:SessionStore,inspectionId:string,destination:string,approvedId:string,signal:AbortSignal){
 signal.throwIfAborted();const prepared=await plan(store.directory,store.events,inspectionId,destination);if(prepared.review.id!==approvedId)throw new Error('Export requires exact fresh preview approval');const portable={version:1,inspectionId,assets:prepared.review.files,scope:prepared.review.scope};const bytes=Buffer.from(await new Bun.Archive({...Object.fromEntries(prepared.bundle.files),'manifest.json':JSON.stringify(portable,null,2)},{compress:'gzip'}).bytes());if(bytes.length>129*1024*1024)throw new Error('Export archive byte budget');signal.throwIfAborted();const current=await mutationScope(prepared.parent,basename(prepared.review.destination),true);if(JSON.stringify(current)!==JSON.stringify(prepared.scope)||await realpath(dirname(destination))!==prepared.parent)throw new Error('Export destination changed');
 const exportId=Bun.randomUUIDv7();store.append('inspection.export.requested',{inspectionId,exportId,review:JSON.stringify(prepared.review)});const result=await publishExport({destination:prepared.review.destination,parent:prepared.parent,scope:prepared.scope},bytes,exportId,signal);store.append('inspection.export.completed',{inspectionId,exportId,status:result.status,result:JSON.stringify(result)});return result;
}
