import {realpath,lstat} from 'node:fs/promises';import {constants,closeSync,writeSync,fsyncSync,fstatSync} from 'node:fs';import {resolve,dirname,basename,join,relative,isAbsolute} from 'node:path';
import {loadReportBundle} from './report-viewer';import {AnchoredFiles} from '../tools/anchored-files';import {mutationScope,type MutationScope} from '../tools/mutation-path';import {readBoundedFile} from '../sessions/files';import {digest} from '../tools/source';import type {Envelope} from '../protocol/events';import type {SessionStore} from '../sessions/store';
export interface ExportReview {id:string;inspectionId:string;destination:string;format:'tar.gz';files:{redaction:string;artifactId:string;name:string;sha256:string;size:number}[];totalBytes:number;parentIdentity:MutationScope['rootIdentity'];scope:'local portable evidence; excludes report JSON and authentication state; no upload'}
async function plan(directory:string,events:readonly Envelope[],inspectionId:string,destination:string){
 if(!isAbsolute(destination)||!destination.endsWith('.tar.gz')||destination.includes('\0'))throw new Error('Choose a new absolute .tar.gz destination');const parent=await realpath(dirname(destination));const target=join(parent,basename(destination));const session=await realpath(directory);const rel=relative(session,target);if(!rel||!rel.startsWith('..')&&!isAbsolute(rel))throw new Error('Export outside session storage');
 for(let path=parent;;path=dirname(path)){try{await lstat(join(path,'.git'));throw new Error('Export destination must be outside Git worktrees');}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}if(dirname(path)===path)break;}
 const scope=await mutationScope(parent,basename(target),true);const bundle=await loadReportBundle(directory,events,inspectionId);const files=bundle.manifest.assets.map(({artifactId,name,sha256,size,redaction})=>({artifactId,name,sha256,size,redaction:redaction??'unknown'}));const value={inspectionId,destination:target,format:'tar.gz' as const,files,totalBytes:files.reduce((sum,file)=>sum+file.size,0),parentIdentity:scope.rootIdentity,scope:'local portable evidence; excludes report JSON and authentication state; no upload' as const};return {bundle,scope,parent,review:{id:digest(JSON.stringify(value)),...value}};
}
export async function prepareReportExport(directory:string,events:readonly Envelope[],inspectionId:string,destination:string):Promise<ExportReview>{return (await plan(directory,events,inspectionId,destination)).review;}
export async function exportReport(store:SessionStore,inspectionId:string,destination:string,approvedId:string,signal:AbortSignal){
 signal.throwIfAborted();const prepared=await plan(store.directory,store.events,inspectionId,destination);if(prepared.review.id!==approvedId)throw new Error('Export requires exact fresh preview approval');const portable={version:1,inspectionId,assets:prepared.review.files,scope:prepared.review.scope};const bytes=Buffer.from(await new Bun.Archive({...Object.fromEntries(prepared.bundle.files),'manifest.json':JSON.stringify(portable,null,2)},{compress:'gzip'}).bytes());if(bytes.length>129*1024*1024)throw new Error('Export archive byte budget');signal.throwIfAborted();const current=await mutationScope(prepared.parent,basename(prepared.review.destination),true);if(JSON.stringify(current)!==JSON.stringify(prepared.scope)||await realpath(dirname(destination))!==prepared.parent)throw new Error('Export destination changed');
 const exportId=Bun.randomUUIDv7(),temporary='.mavona-export-'+exportId+'.tmp';store.append('inspection.export.requested',{inspectionId,exportId,review:JSON.stringify(prepared.review)});let files:AnchoredFiles|undefined;let parent:ReturnType<AnchoredFiles['parent']>|undefined;let target:ReturnType<AnchoredFiles['parent']>|undefined;let fd:number|undefined;
 try{files=new AnchoredFiles(prepared.parent,prepared.scope);parent=files.parent(temporary);target=files.parent(basename(prepared.review.destination));fd=files.open(parent,constants.O_CREAT|constants.O_EXCL|constants.O_WRONLY,0o600);let offset=0;while(offset<bytes.length){signal.throwIfAborted();offset+=writeSync(fd,bytes,offset,Math.min(65536,bytes.length-offset),offset);}fsyncSync(fd);const written=fstatSync(fd);signal.throwIfAborted();files.move(parent,target);const current=readBoundedFile(prepared.review.destination,Math.max(1,bytes.length));const final=await lstat(prepared.review.destination);if(final.ino!==written.ino||final.dev!==written.dev||digest(current)!==digest(bytes)||await realpath(dirname(destination))!==prepared.parent)throw new Error('Export changed during publication');const result={status:'passed' as const,path:prepared.review.destination,sha256:digest(bytes),size:bytes.length};store.append('inspection.export.completed',{inspectionId,exportId,status:result.status,result:JSON.stringify(result)});return result;
 }catch{const result={status:'unknown' as const,path:prepared.review.destination,temporaryPath:join(prepared.parent,temporary),reason:'Export interrupted or destination changed. Inspect these paths; no automatic retry or overwrite.'};store.append('inspection.export.completed',{inspectionId,exportId,status:result.status,result:JSON.stringify(result)});return result;
 }finally{if(fd!==undefined)closeSync(fd);target?.close();parent?.close();files?.close();}
}
