import { PNG } from 'pngjs';
import { createHash, randomUUID } from 'node:crypto';
import type { Status } from './service';
export type CaptureConditions={engine:string;viewport:{width:number;height:number};fixtureRevision:string;fontsDigest:string;captureSettingsDigest:string};
export type BaselinePolicy={reviewedBy:string;maxChangedPixelRatio:number;channelTolerance?:number};
export type Comparison={status:Status;reason:string;changedPixels?:number;totalPixels?:number;changedPixelRatio?:number;difference?:Buffer;baselineDigest?:string;actualDigest?:string};
function decode(input:Buffer){if(input.length<24||input.length>100*1024*1024||!input.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))throw new Error('Expected bounded PNG image');const width=input.readUInt32BE(16),height=input.readUInt32BE(20);if(!width||!height||width*height>16000000)throw new Error('PNG pixel budget exceeded');return PNG.sync.read(input,{checkCRC:true});}
const digest=(value:Buffer)=>createHash('sha256').update(value).digest('hex');
export function normalizePng(input:Buffer){const decoded=decode(input);const bytes=PNG.sync.write(decoded);return {id:randomUUID(),bytes,sha256:digest(bytes),width:decoded.width,height:decoded.height,provenance:'imported' as const,runtimeProvenance:'unknown' as const,redaction:'unreviewed' as const};}
/** Baselines are caller-supplied reviewed evidence; this function never writes or adopts one. */
export function compareImages(baseline:Buffer|undefined,actual:Buffer,before:CaptureConditions,after:CaptureConditions,policy?:BaselinePolicy):Comparison{
 if(!baseline||!policy?.reviewedBy)return {status:'unknown',reason:'Missing reviewed baseline or explicit comparison policy'};
 if(!Number.isFinite(policy.maxChangedPixelRatio)||policy.maxChangedPixelRatio<0||policy.maxChangedPixelRatio>1||!Number.isInteger(policy.channelTolerance??0)||(policy.channelTolerance??0)<0||(policy.channelTolerance??0)>255)throw new Error('Invalid explicit visual threshold');
 if(Object.values(before).some(v=>v===''||v==='unknown')||Object.values(after).some(v=>v===''||v==='unknown')||JSON.stringify(before)!==JSON.stringify(after))return {status:'unknown',reason:'Capture conditions or fixture state are missing or not comparable'};
 try{const a=decode(baseline),b=decode(actual);if(a.width!==b.width||a.height!==b.height)return {status:'unknown',reason:'Image dimensions are not comparable'};const difference=new PNG({width:a.width,height:a.height});let changedPixels=0;for(let i=0;i<a.data.length;i+=4){let changed=false;for(let channel=0;channel<4;channel++)if(Math.abs(a.data[i+channel]!-b.data[i+channel]!)>(policy.channelTolerance??0))changed=true;if(changed){changedPixels++;difference.data[i]=255;difference.data[i+1]=0;difference.data[i+2]=90;difference.data[i+3]=255;}else{difference.data[i]=b.data[i]!;difference.data[i+1]=b.data[i+1]!;difference.data[i+2]=b.data[i+2]!;difference.data[i+3]=90;}}
 const totalPixels=a.width*a.height,changedPixelRatio=changedPixels/totalPixels;return {status:changedPixelRatio<=policy.maxChangedPixelRatio?'passed':'failed',reason:'Deterministic pixel comparison; functional and accessibility outcomes remain separate',changedPixels,totalPixels,changedPixelRatio,difference:PNG.sync.write(difference),baselineDigest:digest(baseline),actualDigest:digest(actual)};
 }catch{return {status:'unknown',reason:'Image decoding failed or image budget exceeded'};}
}

/** Self-contained local review: before/after, optional overlay and deterministic difference. */
export function renderComparisonView(before:Buffer,after:Buffer,comparison:Comparison):string{
 const left=normalizePng(before),right=normalizePng(after);const png=(bytes:Buffer)=>'data:image/png;base64,'+bytes.toString('base64');const escape=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>Mavona visual comparison</title><style>body{font:16px system-ui;background:#101820;color:#eff3f5;margin:2rem}img{max-width:100%;height:auto}.pair{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.overlay{position:relative;max-width:${Math.max(left.width,right.width)}px}.overlay img+img{position:absolute;inset:0;opacity:.5}.overlay{display:none}#overlay:checked~.overlay{display:block}#overlay:checked~.pair{display:none}label{display:inline-block;padding:1rem}figure{margin:1rem 0}</style></head><body><h1>Visual comparison: ${escape(comparison.status)}</h1><p>${escape(comparison.reason)}</p><p>${comparison.changedPixels??'unknown'} changed pixels / ${comparison.totalPixels??'unknown'} total. Functional and accessibility outcomes are separate.</p><input id="overlay" type="checkbox"><label for="overlay">Overlay captures at 50%</label><div class="pair"><figure><figcaption>Before</figcaption><img alt="Before" src="${png(left.bytes)}"></figure><figure><figcaption>After</figcaption><img alt="After" src="${png(right.bytes)}"></figure></div><div class="overlay"><img alt="Before overlay" src="${png(left.bytes)}"><img alt="After overlay at 50 percent" src="${png(right.bytes)}"></div>${comparison.difference?`<h2>Deterministic difference</h2><img alt="Changed pixels highlighted" src="${png(normalizePng(comparison.difference).bytes)}">`:''}</body></html>`;
}
