import { access } from 'node:fs/promises';
import { join } from 'node:path';
import { createConnection } from 'node:net';
export type OwnedServer = {stop:()=>Promise<void>;logs?:()=>string[]};
export type ServerHandle = {url:string;ownership:'attached'|'owned';stop:()=>Promise<void>;logs:()=>string[]};
function localUrl(input:string):URL{const url=new URL(input);if(!['http:','https:'].includes(url.protocol)||!['127.0.0.1','localhost','[::1]'].includes(url.hostname)||url.username||url.password)throw new Error('Server target must be an explicit loopback URL');return url;}
async function occupied(url:URL):Promise<boolean>{return new Promise(resolve=>{const socket=createConnection({host:url.hostname.replace(/^\[|\]$/g,''),port:Number(url.port)||(url.protocol==='https:'?443:80)});const finish=(value:boolean)=>{socket.destroy();resolve(value);};socket.once('connect',()=>finish(true));socket.once('error',()=>finish(false));socket.setTimeout(500,()=>finish(false));});}
async function healthy(url:URL){try{const response=await fetch(url,{redirect:'manual',signal:AbortSignal.timeout(1000)});await response.body?.cancel();return response.status<500;}catch{return false;}}
export async function discoverBootCommands(checkout:string):Promise<string[][]>{try{await access(join(checkout,'bin','rails'));return [['bin/rails','server','--environment','test','--binding','127.0.0.1']];}catch{return [];}}
/** The caller supplies a separately approved spawn capability. Parsing configuration never creates it. */
export async function startServer(urlInput:string,approvedSpawn:(()=>Promise<OwnedServer>)|undefined,options:{healthTimeoutMs?:number;signal?:AbortSignal}={}):Promise<ServerHandle>{const url=localUrl(urlInput);if(!approvedSpawn)throw new Error('approval-required: server boot executes application code');if(await occupied(url))throw new Error('Port occupied; select explicit attach instead');const owned=await approvedSpawn();let stopped=false;const stop=async()=>{if(!stopped){stopped=true;await owned.stop();}};const end=Date.now()+Math.max(1,Math.min(options.healthTimeoutMs??15000,60000));try{while(Date.now()<end){if(options.signal?.aborted)throw new Error('Server startup cancelled');if(await healthy(url))return {url:url.href,ownership:'owned',stop,logs:()=>owned.logs?.()??[]};await new Promise(resolve=>setTimeout(resolve,50));}throw new Error('Server health timeout');}catch(error){await stop();throw error;}}
export async function attachServer(urlInput:string):Promise<ServerHandle>{const url=localUrl(urlInput);if(!await healthy(url))throw new Error('Attached server unavailable');return {url:url.href,ownership:'attached',stop:async()=>{},logs:()=>[]};}
