import { access } from 'node:fs/promises';
import { join } from 'node:path';
import { createConnection } from 'node:net';
import {spawn} from 'node:child_process';
export type OwnedServer = {stop:()=>Promise<void>;logs?:()=>string[]};
export type ServerHandle = {url:string;ownership:'attached'|'owned';stop:()=>Promise<void>;logs:()=>string[]};
export class ServerUnavailableError extends Error{}
function localUrl(input:string):URL{const url=new URL(input);if(!['http:','https:'].includes(url.protocol)||!['127.0.0.1','localhost','[::1]'].includes(url.hostname)||url.username||url.password)throw new Error('Server target must be an explicit loopback URL');return url;}
async function occupied(url:URL):Promise<boolean>{return new Promise(resolve=>{const socket=createConnection({host:url.hostname.replace(/^\[|\]$/g,''),port:Number(url.port)||(url.protocol==='https:'?443:80)});const finish=(value:boolean)=>{socket.destroy();resolve(value);};socket.once('connect',()=>finish(true));socket.once('error',()=>finish(false));socket.setTimeout(500,()=>finish(false));});}
async function healthy(url:URL){try{const response=await fetch(url,{redirect:'manual',signal:AbortSignal.timeout(1000)});await response.body?.cancel();return response.status<500;}catch{return false;}}
export async function discoverBootCommands(checkout:string,urlInput='http://127.0.0.1:3000'):Promise<string[][]>{const url=localUrl(urlInput),port=String(Number(url.port)||(url.protocol==='https:'?443:80));try{await access(join(checkout,'bin','rails'));return [['bin/rails','server','--environment','test','--binding','127.0.0.1','--port',port]];}catch{return [];}}
function cleanLog(input:string){return input.replace(/\u001b\[[0-?]*[ -/]*[@-~]/g,'').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f-\u009f]/g,'').replace(/([?&](?:password|token|secret|key)?)=[^\s&]*/gi,'$1=[REDACTED]').replace(/\b(password|token|secret|authorization|cookie|api[_-]?key)(\s*[:=]\s*)[^\s]+/gi,'$1$2[REDACTED]');}
/** Run only an argv already covered by the caller's exact approval. */
export async function spawnOwnedServer(checkout:string,argv:string[]):Promise<OwnedServer>{if(!argv.length||argv.length>32||argv.some(value=>!value||value.length>4096||value.includes('\0')))throw new Error('Invalid approved server command');const cwd=await import('node:fs/promises').then(fs=>fs.realpath(checkout));const child=spawn(argv[0]!,argv.slice(1),{cwd,detached:process.platform!=='win32',env:{PATH:process.env.PATH??'/usr/bin:/bin',LANG:'C.UTF-8',RAILS_ENV:'test',RACK_ENV:'test',NODE_ENV:'test'},stdio:['ignore','pipe','pipe']});const lines:string[]=[];let bytes=0,stopped=false;const capture=(prefix:string,chunk:Buffer)=>{if(bytes>=64*1024)return;const text=cleanLog(chunk.subarray(0,64*1024-bytes).toString('utf8'));bytes+=Buffer.byteLength(text);for(const line of text.split(/\r?\n/))if(line&&lines.length<200)lines.push(prefix+line.slice(0,2000));};child.stdout.on('data',(chunk:Buffer)=>capture('',chunk));child.stderr.on('data',(chunk:Buffer)=>capture('stderr: ',chunk));const exited=new Promise<void>((resolve,reject)=>{child.once('error',()=>reject(new Error('Approved server command could not start')));child.once('close',()=>resolve());});return {logs:()=>[...lines],stop:async()=>{if(stopped)return;stopped=true;if(child.exitCode!==null)return;try{process.kill(process.platform==='win32'?child.pid!:-child.pid!,'SIGTERM');}catch{}if(await Promise.race([exited.then(()=>true),new Promise<false>(resolve=>setTimeout(()=>resolve(false),1000))]))return;try{process.kill(process.platform==='win32'?child.pid!:-child.pid!,'SIGKILL');}catch{}await exited.catch(()=>{});}};}
/** The caller supplies a separately approved spawn capability. Parsing configuration never creates it. */
export async function startServer(urlInput:string,approvedSpawn:(()=>Promise<OwnedServer>)|undefined,options:{healthTimeoutMs?:number;signal?:AbortSignal|undefined}={}):Promise<ServerHandle>{const url=localUrl(urlInput);if(!approvedSpawn)throw new Error('approval-required: server boot executes application code');if(await occupied(url))throw new ServerUnavailableError('Port occupied; select explicit attach instead');const owned=await approvedSpawn();let stopped=false;const stop=async()=>{if(!stopped){stopped=true;await owned.stop();}};const end=Date.now()+Math.max(1,Math.min(options.healthTimeoutMs??15000,60000));try{while(Date.now()<end){if(options.signal?.aborted)throw new Error('Server startup cancelled');if(await healthy(url))return {url:url.href,ownership:'owned',stop,logs:()=>owned.logs?.()??[]};await new Promise(resolve=>setTimeout(resolve,50));}throw new Error('Server health timeout');}catch(error){await stop();throw error;}}
export async function attachServer(urlInput:string):Promise<ServerHandle>{const url=localUrl(urlInput);if(!await healthy(url))throw new ServerUnavailableError('Attached server unavailable');return {url:url.href,ownership:'attached',stop:async()=>{},logs:()=>[]};}
