import {randomUUID,createHash} from 'node:crypto';import {realpath} from 'node:fs/promises';import {resolve,relative,isAbsolute,join,dirname} from 'node:path';
import {readBoundedFile,sessionDirectory} from '../sessions/files';import type {Envelope} from '../protocol/events';import type {Report} from './service';
export interface ReportAsset {artifactId:string;name:string;path:string;sha256:string;size:number;mediaType:string}
export interface ReportManifest {version:1;sessionId:string;inspectionId:string;assets:ReportAsset[]}
export interface ReportBundle {manifest:ReportManifest;files:Map<string,Buffer>}
const mime:Record<string,string>={html:'text/html',png:'image/png',zip:'application/zip',webm:'video/webm',txt:'text/plain'};
const hash=(bytes:Buffer)=>createHash('sha256').update(bytes).digest('hex');
export function reportManifest(sessionDirectory:string,sessionId:string,report:Report,reportPath:string,html:Buffer):ReportManifest {
 const assets:ReportAsset[]=[];const add=(artifactId:string,name:string,sha256:string,size:number)=>assets.push({artifactId,name,path:relative(sessionDirectory,join(dirname(reportPath),name)),sha256,size,mediaType:mime[name.split('.').at(-1)!]!});add(report.id+':html','report.html',hash(html),html.length);for(const image of report.artifacts)add(image.id,image.path,image.sha256,image.size);for(const download of report.downloads??[])add(download.id,download.path,download.sha256,download.size);if(report.trace.status==='passed')add(report.trace.path.slice(0,-4),report.trace.path,report.trace.sha256,report.trace.size);if(report.video?.status==='passed')add(report.video.path.slice(0,-5),report.video.path,report.video.sha256,report.video.size);return {version:1,sessionId,inspectionId:report.id,assets};
}
function validate(value:unknown,event:Envelope):ReportManifest{if(!value||typeof value!=='object')throw new Error('Missing report manifest');const record=value as ReportManifest;if(record.version!==1||record.sessionId!==event.sessionId||record.inspectionId!==event.payload.inspectionId||!Array.isArray(record.assets)||!record.assets.length||record.assets.length>64)throw new Error('Invalid report manifest');let bytes=0;const names=new Set<string>();const ids=new Set<string>();let directory:string|undefined;for(const asset of record.assets){if(!asset||typeof asset.artifactId!=='string'||!asset.artifactId||asset.artifactId.length>128||ids.has(asset.artifactId)||typeof asset.name!=='string'||!(asset.name==='report.html'||/^[a-f0-9-]+\.(png|zip|webm|txt)$/.test(asset.name))||typeof asset.path!=='string'||!/^artifacts\/[a-f0-9-]+\//.test(asset.path)||asset.path!==join(dirname(asset.path),asset.name)||!/^artifacts\/[a-f0-9-]+$/.test(dirname(asset.path))||names.has(asset.name)||!Number.isSafeInteger(asset.size)||asset.size<0||! /^[a-f0-9]{64}$/.test(asset.sha256)||asset.mediaType!==mime[asset.name.split('.').at(-1)!])throw new Error('Invalid managed report asset');directory??=dirname(asset.path);if(directory!==dirname(asset.path))throw new Error('Mixed report directories');ids.add(asset.artifactId);names.add(asset.name);bytes+=asset.size;if(bytes>128*1024*1024)throw new Error('Report bundle byte budget');}if(!names.has('report.html'))throw new Error('Report HTML missing');return structuredClone(record);}
export async function loadReportBundle(directory:string,events:readonly Envelope[],inspectionId:string):Promise<ReportBundle>{
 const event=events.findLast(item=>item.schemaVersion===1&&item.type==='inspection.report'&&item.payload.inspectionId===inspectionId);if(!event||typeof event.payload.manifest!=='string'||event.payload.manifest.length>65536)throw new Error('No recorded immutable report manifest');const manifest=validate(JSON.parse(event.payload.manifest),event);sessionDirectory(directory);const root=resolve(directory),realRoot=await realpath(root);const files=new Map<string,Buffer>();
 for(const asset of manifest.assets){if(events.some(item=>item.type==='artifact.expired'&&item.payload.artifactId===asset.artifactId&&item.payload.sha256===asset.sha256))throw new Error('Report contains expired evidence');const path=resolve(root,asset.path);const inside=(base:string,target:string)=>{const rel=relative(base,target);return !!rel&&!rel.startsWith('..')&&!isAbsolute(rel);};if(!inside(root,path))throw new Error('Report asset outside session');const before=await realpath(path);if(!inside(realRoot,before))throw new Error('Report asset escaped session');const bytes=readBoundedFile(path,Math.max(1,asset.size));if(bytes.length!==asset.size||hash(bytes)!==asset.sha256||await realpath(path)!==before||await realpath(root)!==realRoot)throw new Error('Report asset changed');files.set(asset.name,bytes);}
 return {manifest,files};
}
export function startReportViewer(bundle:ReportBundle){const files=new Map([...bundle.files].map(([name,bytes])=>[name,Buffer.from(bytes)]));const assets=new Map(bundle.manifest.assets.map(asset=>[asset.name,{...asset}]));const prefix='/'+randomUUID()+'/';let origin='';const headers={'Content-Security-Policy':"default-src 'none'; script-src 'none'; connect-src 'none'; img-src 'self'; media-src 'self'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'",'X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Cache-Control':'no-store','Cross-Origin-Resource-Policy':'same-origin'};const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(request){const url=new URL(request.url);if(request.headers.get('host')!==new URL(origin).host||request.headers.get('origin')&&request.headers.get('origin')!==origin)return new Response('Forbidden',{status:403,headers});if(!['GET','HEAD'].includes(request.method))return new Response('Method not allowed',{status:405,headers});if(!url.pathname.startsWith(prefix))return new Response('Not found',{status:404,headers});const name=url.pathname.slice(prefix.length),asset=assets.get(name),bytes=files.get(name);if(!asset||!bytes)return new Response('Not found',{status:404,headers});return new Response(request.method==='HEAD'?null:new Uint8Array(bytes),{headers:{...headers,'Content-Type':asset.mediaType,...(['application/zip','text/plain'].includes(asset.mediaType)?{'Content-Disposition':`attachment; filename="${name}"`}:{})}});}});origin=server.url.origin;return {url:origin+prefix+'report.html',stop:()=>server.stop(true)};}
