import {INSPECTION_PROFILES,inspectionProfile,type ProfileName,type ProfileEvidence} from './profiles';
import {MaskedVideo,type VideoReport} from './video';
import {ConstrainedTrace,type TraceReport} from './trace';
import { normalizePng } from './images';
import { AuthenticationStore, type AuthenticationReference } from './authentication';
import { createPolicyProxy } from './network';
import { chromium, firefox, webkit, type Browser, type BrowserContext, type Page, type Frame, type Locator } from 'playwright';
import { createHash, randomUUID } from 'node:crypto';
import { access, mkdir, realpath, writeFile, readFile, stat } from 'node:fs/promises';
import { resolve, join, relative, dirname, basename } from 'node:path';
import { platform } from 'node:os';
export type Status = 'passed'|'failed'|'unknown';
export type Engine = 'chromium'|'firefox'|'webkit';
export type SemanticLocator = {kind:'role'|'label'|'text'|'testId';value:string;name?:string};
export type Action = 'tap'|'click'|'dblclick'|'hover'|'fill'|'select'|'check'|'uncheck'|'press'|'navigate'|'back'|'forward'|'reload'|'scroll'|'wait'|'select-page'|'select-frame'|'main-frame'|'new-tab'|'upload'|'download'|'drag';
export type Step = {op:'observe'}|{op:'act';action:Action;locator?:SemanticLocator;value?:string;revision?:number;opensPageId?:string;destination?:SemanticLocator;dialog?:{type:'alert'|'confirm'|'prompt';decision:'accept'|'dismiss';promptReference?:string}}|{op:'capture';fullPage?:boolean;locator?:SemanticLocator;region?:{x:number;y:number;width:number;height:number}}|{op:'assert';id:string;kind:'text'|'url'|'visible'|'hidden'|'value';expected?:string;locator?:SemanticLocator;provenance:'configured-repository'|'model-proposed'|'user-approved'|'protected-grader';required:boolean};
export type Flow = {profile?:ProfileName;evidence?:{trace?:boolean;video?:boolean};version:1;url:string;browser?:Engine;headed?:boolean;viewport?:{width:number;height:number};colorScheme?:'light'|'dark';reducedMotion?:'reduce'|'no-preference';steps:Step[]};
export type Grant = {flowDigest:string;checkout:string;approvedBy:string;origins:string[];actions:Action[];stepDigests:string[];expiresAt:number;revoked?:boolean};
export type Check = {id:string;status:Status;provenance:string;required:boolean;detail:string};
export type Diagnostic = {id:string;kind:'console-error'|'page-exception'|'failed-request'|'http-error'|'blocked-request'|'blocked-websocket'|'dialog';message:string;timestamp:string};
export type Observation = {frameId?:string;id:string;pageId:string;revision:number;url:string;title:string;text:string;timestamp:string;untrusted:true};
export type Artifact = {profile?:ProfileEvidence;id:string;path:string;sha256:string;size:number;mediaType:'image/png';provenance:'captured'|'imported';redaction:'masked'|'unreviewed';url:string;timestamp:string;browser:string;viewport:{width:number;height:number}|null;os:string};
export type InspectionEvent={version:1;id:string;inspectionId:string;stepId:string;phase:'intent'|'result';operation:Step['op']|'annotation'|'import';action?:Action;status:Status;timestamp:string;durationMs?:number};
export type Surface={pageId:string;frameId:string;url:string;closed:boolean;mainFrame:boolean};
export type ManagedDownload={id:string;path:string;sha256:string;size:number;mediaType:'text/plain';redaction:'sanitized'};
export type UploadReference={reference:string;path:string;sha256:string};
export type Annotation={id:string;artifactId:string;text:string;region?:{x:number;y:number;width:number;height:number};provenance:'user'|'model-interpretation';timestamp:string};
export type Report = {profile?:ProfileEvidence;video?:VideoReport;annotations?:Annotation[];surfaces?:Surface[];downloads?:ManagedDownload[];recording?:{path:string;sha256:string;size:number;rawPlaywright:false};version:1;events:InspectionEvent[];id:string;status:Status;state:string;reason?:string;checks:Check[];observations:Observation[];diagnostics:Diagnostic[];artifacts:Artifact[];limits:typeof DEFAULT_LIMITS;authentication?:AuthenticationReference;trace:TraceReport};
export const DEFAULT_LIMITS={actions:40,durationMs:300000,actionTimeoutMs:15000,images:10,artifactBytes:100*1024*1024};
const engines={chromium,firefox,webkit};
const actions:Action[]=['tap','click','dblclick','hover','fill','select','check','uncheck','press','navigate','back','forward','reload','scroll','wait','select-page','select-frame','main-frame','new-tab','upload','download','drag'];
function object(value:unknown):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Expected object');return value as Record<string,unknown>;}
function keys(o:Record<string,unknown>,allowed:string[]){for(const key of Object.keys(o))if(!allowed.includes(key))throw new Error(`Unknown inspection field: ${key}`);}
function string(value:unknown):string{if(typeof value!=='string'||value.length>10000)throw new Error('Expected bounded string');return value;}
function locator(value:unknown):SemanticLocator{const o=object(value);keys(o,['kind','value','name']);if(!['role','label','text','testId'].includes(String(o.kind)))throw new Error('Unsupported locator');return {kind:o.kind as SemanticLocator['kind'],value:string(o.value),...(o.name!==undefined?{name:string(o.name)}:{})};}
export function parseFlow(value:unknown):Flow{
 const o=object(value);keys(o,['version','url','browser','headed','viewport','colorScheme','reducedMotion','steps','evidence','profile']);
 if(o.version!==1||!Array.isArray(o.steps)||o.steps.length>100)throw new Error('Invalid flow version or steps');const url=string(o.url);new URL(url);
 if(o.browser!==undefined&&!['chromium','firefox','webkit'].includes(String(o.browser)))throw new Error('Unknown browser');if(o.headed!==undefined&&typeof o.headed!=='boolean')throw new Error('Invalid headed mode');
 if(o.profile!==undefined&&(typeof o.profile!=='string'||!Object.hasOwn(INSPECTION_PROFILES,o.profile)||o.viewport!==undefined))throw new Error('Unknown profile or conflicting viewport override');
 if(o.viewport!==undefined){const v=object(o.viewport);keys(v,['width','height']);for(const n of [v.width,v.height])if(typeof n!=='number'||!Number.isInteger(n)||n<100||n>4000)throw new Error('Invalid viewport');}
 if(o.colorScheme!==undefined&&!['light','dark'].includes(String(o.colorScheme)))throw new Error('Invalid color scheme');if(o.reducedMotion!==undefined&&!['reduce','no-preference'].includes(String(o.reducedMotion)))throw new Error('Invalid motion setting');
 if(o.evidence!==undefined){const evidence=object(o.evidence);keys(evidence,['trace','video']);for(const value of Object.values(evidence))if(typeof value!=='boolean')throw new Error('Invalid evidence setting');}
 const ids=new Set<string>();for(const raw of o.steps){const s=object(raw);if(s.op==='observe'){keys(s,['op']);continue;}if(s.op==='act'){keys(s,['op','action','locator','value','revision','opensPageId','destination','dialog']);if(!actions.includes(s.action as Action))throw new Error('Unsupported action');if(s.value!==undefined)string(s.value);if(s.opensPageId!==undefined){if(s.action!=='click'||!/^[A-Za-z0-9_-]{1,80}$/.test(string(s.opensPageId)))throw new Error('Invalid popup identity');}if(s.destination!==undefined){if(s.action!=='drag')throw new Error('Destination requires drag');locator(s.destination);}if(s.dialog!==undefined){const d=object(s.dialog);keys(d,['type','decision','promptReference']);if(!['click','press'].includes(String(s.action))||!['alert','confirm','prompt'].includes(String(d.type))||!['accept','dismiss'].includes(String(d.decision)))throw new Error('Invalid scoped dialog decision');if(d.promptReference!==undefined)string(d.promptReference);}if(s.revision!==undefined&&(!Number.isInteger(s.revision)||Number(s.revision)<0))throw new Error('Invalid observation revision');}
 else if(s.op==='capture'){keys(s,['op','fullPage','locator','region']);if(s.fullPage!==undefined&&typeof s.fullPage!=='boolean')throw new Error('Invalid fullPage');if(s.region!==undefined){const r=object(s.region);keys(r,['x','y','width','height']);for(const key of ['x','y','width','height'])if(typeof r[key]!=='number'||!Number.isFinite(r[key])||Number(r[key])<(key==='x'||key==='y'?0:1))throw new Error('Invalid region');}}
 else if(s.op==='assert'){keys(s,['op','id','kind','expected','locator','provenance','required']);const id=string(s.id);if(ids.has(id))throw new Error('Duplicate check ID');ids.add(id);if(!['text','url','visible','hidden','value'].includes(String(s.kind))||!['configured-repository','model-proposed','user-approved','protected-grader'].includes(String(s.provenance))||typeof s.required!=='boolean')throw new Error('Invalid assertion');if(s.expected!==undefined)string(s.expected);}
 else throw new Error('Unsupported operation');if(s.locator!==undefined)locator(s.locator);
 }
 return structuredClone(o) as Flow;
}
export function digestFlow(flow:Flow):string{return createHash('sha256').update(JSON.stringify(parseFlow(flow))).digest('hex');}
function loopback(url:URL){return url.hostname==='localhost'||url.hostname==='[::1]'||/^127\.(?:\d{1,3}\.){2}\d{1,3}$/.test(url.hostname);}
export function approveFlow(flow:Flow,checkout:string,approvedBy:string):Grant{const u=new URL(flow.url);if(!['http:','https:'].includes(u.protocol)||!loopback(u)||u.username||u.password)throw new Error('Only explicit loopback development origins are supported');return {flowDigest:digestFlow(flow),checkout:resolve(checkout),approvedBy,origins:[u.origin],actions:[...new Set(flow.steps.filter(s=>s.op==='act').map(s=>s.action))],stepDigests:flow.steps.map(step=>createHash('sha256').update(JSON.stringify(step)).digest('hex')),expiresAt:Date.now()+3600000};}
export function aggregateChecks(checks:readonly {status:Status}[]):Status{return checks.some(c=>c.status==='failed')?'failed':!checks.length||checks.some(c=>c.status==='unknown')?'unknown':'passed';}
export async function doctor(){return Promise.all((['chromium','firefox','webkit'] as const).map(async browser=>{const executablePath=engines[browser].executablePath();let available=true;try{await access(executablePath);}catch{available=false;}return {browser,available,executablePath,platform:platform(),status:available?'installed':'unavailable',installCommand:['mavona','app','install','--browser',browser],downloadSize:'unknown',standaloneVerified:false};}));}
export class InspectionService{
 private closing:Promise<void>|undefined;private video:MaskedVideo|undefined;private trace:ConstrainedTrace|undefined;private cancelled=false;private pages=new Map<string,Page>();private frameIds=new Map<Frame,string>();private frameAliases=new Map<string,Frame>();private frame:Frame|undefined;private pendingPageId:string|undefined;private pendingDialog:Extract<Step,{op:'act'}>['dialog'];private expectedDownload=false;private uploads:UploadReference[]=[];private secretInputs:Record<string,string>={};private recording:{approved:boolean;includeObservations:boolean}|undefined;private authExpiresAt=Infinity;private proxy:Awaited<ReturnType<typeof createPolicyProxy>>|undefined;private browser:Browser|undefined;private context:BrowserContext|undefined;private page:Page|undefined;private flow:Flow|undefined;private grant:Grant|undefined;private secrets:string[]=[];private selectors:string[]=[];private revision=0;private actionCount=0;private started=0;private bytes=0;private artifactDirectory='';private artifactRoot='';private eventSink:((event:InspectionEvent)=>Promise<void>)|undefined;private observedMutation=-1;private pageId:string=randomUUID();private report:Report=this.fresh();
 private fresh():Report{return {version:1,events:[],id:randomUUID(),status:'unknown',state:'idle',checks:[],observations:[],diagnostics:[],artifacts:[],limits:{...DEFAULT_LIMITS},trace:{status:'unknown',reason:'Trace recording not requested.'}};}
 private sanitize(input:string,limit=20000):string{let s=input;for(const secret of this.secrets)if(secret)s=s.split(secret).join('[REDACTED]');s=s.replace(/\u001b\[[0-?]*[ -/]*[@-~]/g,'').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f-\u009f]/g,'').replace(/\b(?:authorization|proxy-authorization)\s*[:=]\s*(?:(?:Bearer|Basic)\s+)?[^\s\r\n]+/gi,'Authorization: [REDACTED]').replace(/\b(?:cookie|set-cookie)\s*[:=][^\r\n]+/gi,'Cookie: [REDACTED]');return s.replace(/(password|token|secret|authorization|cookie|api[_-]?key)(\s*[:=]\s*)(?:"[^"]*"|'[^']*'|[^\s&"'<>]+)/gi,'$1$2[REDACTED]').slice(0,limit);}
 private url(input:string){try{const u=new URL(input);u.username='';u.password='';for(const key of [...u.searchParams.keys()])u.searchParams.set(key,'[REDACTED]');u.hash='';return this.sanitize(u.href);}catch{return '[invalid URL]';}}
 private diagnostic(kind:Diagnostic['kind'],message:string){if(this.report.diagnostics.length<200)this.report.diagnostics.push({id:randomUUID(),kind,message:this.sanitize(message),timestamp:new Date().toISOString()});}
 private authorized(){if(this.cancelled)throw new Error('Inspection cancelled');if(!this.flow||!this.grant||this.grant.revoked||this.grant.expiresAt<=Date.now()||digestFlow(this.flow)!==this.grant.flowDigest)throw new Error('approval-required: missing, expired, revoked or changed flow approval');if(Date.now()>=this.authExpiresAt)throw new Error('Authentication reuse expired');if(Date.now()-this.started>DEFAULT_LIMITS.durationMs)throw new Error('Flow duration budget exhausted');}
 private allowed(input:string){try{const u=new URL(input);const origin=u.protocol==='ws:'?'http://'+u.host:u.protocol==='wss:'?'https://'+u.host:u.origin;return !!this.grant&&!this.grant.revoked&&this.grant.expiresAt>Date.now()&&this.authExpiresAt>Date.now()&&this.grant.origins.includes(origin)&&loopback(u)&&!u.username&&!u.password;}catch{return false;}}
 private target(spec:SemanticLocator):Locator{if(!this.page)throw new Error('Browser unavailable');const surface=this.frame??this.page;if(spec.kind==='label')return surface.getByLabel(spec.value,{exact:true});if(spec.kind==='text')return surface.getByText(spec.value,{exact:true});if(spec.kind==='testId')return surface.getByTestId(spec.value);return surface.getByRole(spec.value as Parameters<Page['getByRole']>[0],{...(spec.name!==undefined?{name:spec.name,exact:true}:{})});}
 async start(input:Flow,grant?:Grant,options:{artifactRoot?:string;artifactDirectory?:string;uploads?:UploadReference[];secretInputs?:Record<string,string>;recording?:{approved:boolean;includeObservations:boolean};secrets?:string[];redactSelectors?:string[];checkout?:string;authentication?:{store:AuthenticationStore;referenceId:string;reuseApproved:boolean};onEvent?:(event:InspectionEvent)=>Promise<void>}={}):Promise<Report>{
 if(this.context)throw new Error('Inspection already active');this.cancelled=false;this.authExpiresAt=Infinity;this.pages.clear();this.frameIds.clear();this.frameAliases.clear();this.frame=undefined;this.pendingPageId='main';this.pageId='main';this.uploads=options.uploads??[];this.secretInputs=options.secretInputs??{};this.recording=options.recording;this.report=this.fresh();this.flow=parseFlow(input);this.grant=grant;this.started=Date.now();this.actionCount=0;this.revision=0;this.bytes=0;this.secrets=[...(options.secrets??[]),...Object.values(this.secretInputs)];this.selectors=options.redactSelectors??[];this.eventSink=options.onEvent;this.report.state='starting';this.report.profile=inspectionProfile(this.flow);
 try{this.authorized();if(options.checkout&&await realpath(options.checkout)!==await realpath(grant!.checkout))throw new Error('approval-required: checkout changed');if(!this.allowed(input.url))throw new Error('approval-required: target origin');this.artifactRoot=resolve(options.artifactRoot??grant!.checkout);this.artifactDirectory=resolve(options.artifactDirectory??(options.artifactRoot?join(this.artifactRoot,this.report.id):join(grant!.checkout,'.mavona','inspection',this.report.id)));await this.artifactContainment();await mkdir(this.artifactDirectory,{recursive:true,mode:0o700});await this.artifactContainment();
 const authentication=options.authentication?await options.authentication.store.load(options.authentication.referenceId,{checkout:grant!.checkout,origin:new URL(input.url).origin,reuseApproved:options.authentication.reuseApproved,artifactRoot:this.artifactRoot}):undefined;if(authentication){this.authExpiresAt=authentication.reference.expiresAt;this.report.authentication=authentication.reference;this.secrets.push(...authentication.state.cookies.map(c=>c.value),...authentication.state.origins.flatMap(o=>o.localStorage.map(v=>v.value)));}
 const engine=input.browser??'chromium';this.proxy=await createPolicyProxy(url=>this.allowed(url),url=>this.diagnostic('blocked-request',this.url(url)));this.browser=await engines[engine].launch({headless:!input.headed,proxy:{server:this.proxy.url},...(engine==='chromium'?{args:['--proxy-bypass-list=<-loopback>']}:{})});this.context=await this.browser.newContext({...(authentication?{storageState:authentication.state}:{}),serviceWorkers:'block',acceptDownloads:this.flow.steps.some(step=>step.op==='act'&&step.action==='download'),viewport:this.report.profile.viewport,deviceScaleFactor:this.report.profile.deviceScaleFactor,hasTouch:this.report.profile.hasTouch,isMobile:this.report.profile.isMobile,colorScheme:this.report.profile.colorScheme,reducedMotion:this.report.profile.reducedMotion});this.context.setDefaultTimeout(DEFAULT_LIMITS.actionTimeoutMs);if(this.flow.evidence?.trace)this.trace=await ConstrainedTrace.start(this.context);if(this.flow.evidence?.video)this.video=new MaskedVideo();
 await this.context.addInitScript(() => { const state = window as unknown as { __mavonaMutation:number };state.__mavonaMutation=0;new MutationObserver(()=>{state.__mavonaMutation++;}).observe(document,{subtree:true,childList:true,attributes:true,characterData:true}); });
 await this.context.route('**/*',async route=>{if(!this.allowed(route.request().url())){this.diagnostic('blocked-request',this.url(route.request().url()));await route.abort('blockedbyclient');}else await route.continue();});
 await this.context.routeWebSocket('**/*',socket=>{if(!this.allowed(socket.url())){this.diagnostic('blocked-websocket',this.url(socket.url()));socket.close();}else socket.connectToServer();});
 this.context.on('page',page=>{const id=this.pendingPageId??randomUUID();this.pendingPageId=undefined;this.pages.set(id,page);this.frameIds.set(page.mainFrame(),id+':main');page.on('frameattached',frame=>this.frameIds.set(frame,randomUUID()));page.on('console',msg=>{if(msg.type()==='error')this.diagnostic('console-error',msg.text());});page.on('pageerror',err=>this.diagnostic('page-exception',err.message));page.on('requestfailed',req=>this.diagnostic('failed-request',this.url(req.url())));page.on('response',res=>{if(res.status()>=400)this.diagnostic('http-error',`${res.status()} ${this.url(res.url())}`);});page.on('dialog',dialog=>{const decision=this.pendingDialog;this.pendingDialog=undefined;if(decision&&decision.type===dialog.type()){this.diagnostic('dialog',`Scoped ${decision.type} ${decision.decision}`);if(decision.decision==='accept')void dialog.accept(decision.promptReference?this.secretInputs[decision.promptReference]:undefined);else void dialog.dismiss();}else{this.diagnostic('dialog','Dialog dismissed by default effect policy');void dialog.dismiss();}});page.on('framenavigated',()=>{this.revision++;});page.on('download',download=>{if(this.expectedDownload){this.expectedDownload=false;return;}void download.cancel();this.diagnostic('blocked-request','Download denied by scope');});});
 this.page=await this.context.newPage();await this.page.goto(input.url,{waitUntil:'domcontentloaded'});this.report.profile.status='passed';this.report.profile.reason='Browser context started with requested emulation; functional assertions remain separate';this.report.state='ready';await this.videoFrame();return this.snapshot();
 }catch(error){this.report.reason=this.sanitize(String(error));this.report.state='awaiting approval';await this.close();return this.snapshot();}
 }
 async observe():Promise<Observation>{this.authorized();if(!this.page)throw new Error('Browser unavailable');
 // Traverse rendered text without cloning private/form/script data into an evidence surface.
 const text=await (this.frame??this.page).locator('body').evaluate((body,selectors)=>{const result:string[]=[];let length=0;const visit=(node:Node)=>{if(length>=20000)return;if(node.nodeType===Node.TEXT_NODE){const value=node.textContent??'';const range=document.createRange();range.selectNodeContents(node);if(value.trim()&&[...range.getClientRects()].some(r=>r.width>0&&r.height>0)){result.push(value.trim());length+=value.length;}return;}if(!(node instanceof Element))return;if(node.matches('input,textarea,select,script,style,noscript,template,[hidden],[data-mavona-private]')||selectors.some(s=>node.matches(s)))return;const style=getComputedStyle(node);if(style.display==='none'||style.visibility==='hidden'||style.visibility==='collapse'||style.opacity==='0'||style.contentVisibility==='hidden')return;for(const child of node.childNodes)visit(child);};visit(body);return result.join('\n').slice(0,20000);},this.selectors);

 this.observedMutation=await (this.frame??this.page).evaluate(()=>(window as unknown as {__mavonaMutation:number}).__mavonaMutation);
 const observation:Observation={id:randomUUID(),pageId:this.pageId,frameId:this.frameIds.get(this.frame??this.page.mainFrame())??this.pageId+':main',revision:++this.revision,url:this.url((this.frame??this.page).url()),title:this.sanitize(await this.page.title()),text:this.sanitize(text),timestamp:new Date().toISOString(),untrusted:true};this.report.observations.push(observation);return observation;
 }
 async act(step:Extract<Step,{op:'act'}>):Promise<void>{
  this.authorized();parseFlow({...this.flow!,steps:[step]});const requested={...step};delete requested.revision;
  if(!this.grant?.stepDigests.includes(createHash('sha256').update(JSON.stringify(requested)).digest('hex')))throw new Error('approval-required: action arguments outside approved flow');
  if(this.report.state==='manual takeover')throw new Error('Browser under manual takeover');
  if(!this.page||!this.grant?.actions.includes(step.action))throw new Error('approval-required: action outside scope');
  if(step.revision!==undefined&&(step.revision!==this.revision||this.observedMutation!==await (this.frame??this.page).evaluate(()=>(window as unknown as {__mavonaMutation:number}).__mavonaMutation)))throw new Error('Stale observation: observe again');
  if(++this.actionCount>DEFAULT_LIMITS.actions)throw new Error('Action budget exhausted');
  const target=step.locator?this.target(step.locator):undefined;if(target&&await target.count()!==1)throw new Error('Ambiguous or missing locator: observe again');
  if(step.dialog?.promptReference&&!Object.hasOwn(this.secretInputs,step.dialog.promptReference))throw new Error('approval-required: unknown prompt secret reference');
  if(step.opensPageId&&this.pages.has(step.opensPageId))throw new Error('Page identity already exists');
  this.report.state='running';this.pendingDialog=step.dialog;
  try{
   switch(step.action){
    case 'select-page':{const page=this.pages.get(step.value??'');if(!page||page.isClosed()||!this.allowed(page.url()))throw new Error('Unknown, closed or out-of-scope page');this.page=page;this.pageId=step.value!;this.frame=undefined;break;}
    case 'select-frame':{const handle=await target?.elementHandle();const frame=target?await handle?.contentFrame():this.frameAliases.get(step.value??'')??[...this.frameIds].find(([,id])=>id===step.value)?.[0];await handle?.dispose();if(!frame||frame.isDetached())throw new Error('Locator is not a live frame');await frame.waitForLoadState('domcontentloaded');if(!this.allowed(frame.url()))throw new Error('Frame outside approved origin');if(step.value){const existing=this.frameAliases.get(step.value);if(existing&&existing!==frame)throw new Error('Frame alias identity changed');this.frameAliases.set(step.value,frame);}if(!this.frameIds.has(frame))this.frameIds.set(frame,randomUUID());this.frame=frame;break;}
    case 'main-frame':this.frame=undefined;break;
    case 'new-tab':{const url=new URL(step.value??'',this.flow!.url);if(!this.allowed(url.href))throw new Error('approval-required: tab origin');const page=await this.context!.newPage();await page.goto(url.href,{waitUntil:'domcontentloaded'});this.page=page;this.pageId=[...this.pages].find(([,candidate])=>candidate===page)![0];this.frame=undefined;break;}
    case 'navigate':{const u=new URL(step.value??'',(this.frame??this.page).url());if(!this.allowed(u.href))throw new Error('approval-required: navigation origin');await (this.frame??this.page).goto(u.href,{waitUntil:'domcontentloaded'});break;}
    case 'back':await this.page.goBack();this.frame=undefined;break;
    case 'forward':await this.page.goForward();this.frame=undefined;break;
    case 'reload':await this.page.reload();this.frame=undefined;break;
    case 'wait':{const ms=Number(step.value??'0');if(!Number.isFinite(ms)||ms<0||ms>DEFAULT_LIMITS.actionTimeoutMs)throw new Error('Invalid bounded wait');await this.page.waitForTimeout(ms);break;}
    case 'scroll':await this.page.mouse.wheel(0,Math.min(2000,Math.max(-2000,Number(step.value)||0)));break;
    case 'upload':{
     if(!target)throw new Error('Upload locator required');const reference=this.uploads.find(file=>file.reference===step.value);if(!reference)throw new Error('approval-required: unknown upload reference');
     const root=await realpath(this.grant.checkout),path=resolve(reference.path);const lexical=relative(resolve(this.grant.checkout),path);const actual=await realpath(path),physical=relative(root,actual);for(const rel of [lexical,physical])if(rel==='..'||rel.startsWith('../')||rel.startsWith('/'))throw new Error('Upload escapes checkout');const metadata=await stat(actual);if(!metadata.isFile()||metadata.size>20*1024*1024)throw new Error('Upload file budget exceeded');const buffer=await readFile(actual);if(createHash('sha256').update(buffer).digest('hex')!==reference.sha256)throw new Error('approval-required: upload content changed');await target.setInputFiles({name:basename(path),mimeType:'application/octet-stream',buffer});break;
    }
    case 'download':{
     if(!target||step.value!=='text')throw new Error('Only scoped sanitized text downloads are supported');this.expectedDownload=true;
     const [download]=await Promise.all([this.page.waitForEvent('download',{timeout:DEFAULT_LIMITS.actionTimeoutMs}),target.click()]);
     try{const path=await download.path();if(!path)throw new Error('Download unavailable');const metadata=await stat(path);if(metadata.size>1024*1024)throw new Error('Download exceeds sanitized text budget');const raw=await readFile(path);const text=new TextDecoder('utf-8',{fatal:true}).decode(raw);const bytes=Buffer.from(this.sanitize(text,1024*1024));if(this.bytes+bytes.length>DEFAULT_LIMITS.artifactBytes)throw new Error('Artifact budget exhausted');const id=randomUUID(),managedPath=id+'.txt';await this.artifactContainment();await writeFile(join(this.artifactDirectory,managedPath),bytes,{mode:0o600,flag:'wx'});this.bytes+=bytes.length;(this.report.downloads??=[]).push({id,path:managedPath,sha256:createHash('sha256').update(bytes).digest('hex'),size:bytes.length,mediaType:'text/plain',redaction:'sanitized'});}finally{await download.delete();}break;
    }
    case 'drag':{if(!target||!step.destination)throw new Error('Drag requires source and destination locators');const destination=this.target(step.destination);if(await destination.count()!==1)throw new Error('Ambiguous drag destination');await target.dragTo(destination);break;}
    default:{if(!target)throw new Error('Semantic locator required');switch(step.action){
     case 'click':if(step.opensPageId){this.pendingPageId=step.opensPageId;const [popup]=await Promise.all([this.page.waitForEvent('popup',{timeout:DEFAULT_LIMITS.actionTimeoutMs}),target.click()]);await popup.waitForLoadState('domcontentloaded');if(this.pages.get(step.opensPageId)!==popup||!this.allowed(popup.url()))throw new Error('Popup identity or origin changed');}else await target.click();break;
     case 'tap':await target.tap();break;case 'dblclick':await target.dblclick();break;case 'hover':await target.hover();break;case 'fill':if(await target.getAttribute('type')==='password'&&step.value)this.secrets.push(step.value);await target.fill(step.value??'');break;case 'select':await target.selectOption(step.value??'');break;case 'check':await target.check();break;case 'uncheck':await target.uncheck();break;case 'press':await target.press(step.value??'');break;
    }}
   }
   if(this.cancelled)throw new Error('Inspection cancelled');if(step.dialog&&this.pendingDialog)throw new Error('Expected scoped dialog did not appear');this.revision++;this.report.state='ready';
  }finally{this.pendingDialog=undefined;this.pendingPageId=undefined;this.expectedDownload=false;}
 }
 async assert(step:Extract<Step,{op:'assert'}>):Promise<Check>{this.authorized();const check:Check={id:step.id,status:'unknown',provenance:step.provenance,required:step.required,detail:'Not run'};
 try{if(!this.page)throw new Error('Browser unavailable');let passed=false;const target=step.locator?this.target(step.locator):undefined;switch(step.kind){case 'text':await (this.frame??this.page).getByText(step.expected??'',{exact:false}).first().waitFor({state:'visible'});passed=(await this.observe()).text.replace(/\s+/g,' ').includes((step.expected??'').replace(/\s+/g,' '));break;case 'url':passed=(this.frame??this.page).url()===new URL(step.expected??'',this.flow!.url).href;break;case 'visible':if(!target)throw new Error('Locator required');passed=await target.count()===1&&await target.isVisible();break;case 'hidden':if(!target)throw new Error('Locator required');passed=await target.count()===0||await target.isHidden();break;case 'value':if(!target)throw new Error('Locator required');passed=await target.inputValue()===step.expected;break;}check.status=step.provenance==='model-proposed'?'unknown':passed?'passed':'failed';check.detail=step.provenance==='model-proposed'?'Diagnostic assertion requires acceptance adoption':passed?'Runtime assertion passed':'Runtime assertion failed';}catch(error){check.detail=this.sanitize(String(error));}this.report.checks.push(check);return check;
 }
 async capture(step:Extract<Step,{op:'capture'}>={op:'capture'}):Promise<Artifact>{this.authorized();if(!this.page||!this.browser)throw new Error('Browser unavailable');if(this.report.artifacts.length>=DEFAULT_LIMITS.images)throw new Error('Image budget exhausted');const mask=this.page.frames().flatMap(frame=>[frame.locator('input,textarea,select,[data-mavona-private]'),...this.selectors.map(s=>frame.locator(s)),...this.secrets.filter(Boolean).map(s=>frame.getByText(s,{exact:false}))]);const target=step.locator?this.target(step.locator):this.frame?this.frame.locator('body'):this.page;const bytes=await target.screenshot({type:'png',animations:'disabled',mask,...(!step.locator?{fullPage:step.fullPage??false,...(step.region?{clip:step.region}:{})}:{})});if(this.bytes+bytes.length>DEFAULT_LIMITS.artifactBytes)throw new Error('Artifact budget exhausted');const id=randomUUID();const path=id+'.png';await this.artifactContainment();await writeFile(join(this.artifactDirectory,path),bytes,{mode:0o600,flag:'wx'});this.bytes+=bytes.length;const artifact:Artifact={...(this.report.profile?{profile:structuredClone(this.report.profile)}:{}),id,path,sha256:createHash('sha256').update(bytes).digest('hex'),size:bytes.length,mediaType:'image/png',provenance:'captured',redaction:'masked',url:this.url(this.page.url()),timestamp:new Date().toISOString(),browser:this.browser.version(),viewport:this.page.viewportSize(),os:platform()};this.report.artifacts.push(artifact);if(this.trace){const png=normalizePng(bytes);this.trace.persistFrame(this.page,bytes,png.width,png.height);}return artifact;}
 async importImage(input:Buffer,options:{approved:boolean}):Promise<Artifact>{this.authorized();if(!options.approved)throw new Error('approval-required: import image');if(this.report.artifacts.length>=DEFAULT_LIMITS.images)throw new Error('Image budget exhausted');const imported=normalizePng(input);if(this.bytes+imported.bytes.length>DEFAULT_LIMITS.artifactBytes)throw new Error('Artifact budget exhausted');await this.artifactContainment();const path=imported.id+'.png';await writeFile(join(this.artifactDirectory,path),imported.bytes,{mode:0o600,flag:'wx'});this.bytes+=imported.bytes.length;const artifact:Artifact={id:imported.id,path,sha256:imported.sha256,size:imported.bytes.length,mediaType:'image/png',provenance:'imported',redaction:'unreviewed',url:'unknown',timestamp:new Date().toISOString(),browser:'unknown',viewport:null,os:'unknown'};this.report.artifacts.push(artifact);await this.record({version:1,id:randomUUID(),inspectionId:this.report.id,stepId:randomUUID(),operation:'import',phase:'result',status:'unknown',timestamp:new Date().toISOString()});return artifact;}
 async annotate(artifactId:string,input:{text:string;region?:Annotation['region'];provenance:'user'|'model-interpretation'}):Promise<Annotation>{this.authorized();if((this.report.annotations?.length??0)>=100)throw new Error('Annotation budget exhausted');const artifact=this.report.artifacts.find(a=>a.id===artifactId);if(!artifact)throw new Error('Unknown original artifact');if(!['user','model-interpretation'].includes(input.provenance)||typeof input.text!=='string'||input.text.length>1000)throw new Error('Invalid annotation');if(input.region){const {x,y,width,height}=input.region;if([x,y,width,height].some(n=>!Number.isFinite(n))||x<0||y<0||width<=0||height<=0)throw new Error('Invalid annotation region');const image=normalizePng(await readFile(join(this.artifactDirectory,artifact.path)));if(x+width>image.width||y+height>image.height)throw new Error('Annotation region outside image');}const annotation:Annotation={id:randomUUID(),artifactId,text:this.sanitize(input.text),...(input.region?{region:input.region}:{}),provenance:input.provenance,timestamp:new Date().toISOString()};(this.report.annotations??=[]).push(annotation);await this.record({version:1,id:randomUUID(),inspectionId:this.report.id,stepId:annotation.id,operation:'annotation',phase:'result',status:'unknown',timestamp:annotation.timestamp});return annotation;}
 async saveAuthentication(store:AuthenticationStore,options:{approved:boolean;expiresAt:number}){this.authorized();if(!options.approved)throw new Error('approval-required: authentication persistence');if(!this.context)throw new Error('Browser unavailable');const reference=await store.save(await this.context.storageState(),{checkout:this.grant!.checkout,origin:new URL(this.flow!.url).origin,expiresAt:options.expiresAt,artifactRoot:this.artifactRoot});this.report.authentication=reference;return reference;}
 async takeover(){this.authorized();if(!this.page||!this.flow?.headed)throw new Error('Takeover requires a headed browser');this.report.state='manual takeover';await this.page.bringToFront();}
 async resume(){this.authorized();if(this.report.state!=='manual takeover')throw new Error('Not under takeover');await this.observe();this.report.state='ready';}
 private async artifactContainment(){const root=await realpath(this.artifactRoot);const inside=(path:string)=>{const rel=relative(root,path);if(rel==='..'||rel.startsWith('../')||rel.startsWith('..\\')||rel.startsWith('/'))throw new Error('Artifact directory escapes checkout');};const lexical=relative(this.artifactRoot,this.artifactDirectory);if(lexical==='..'||lexical.startsWith('../')||lexical.startsWith('..\\')||lexical.startsWith('/'))throw new Error('Artifact directory escapes checkout');let ancestor=this.artifactDirectory;for(;;){try{inside(await realpath(ancestor));break;}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;const parent=dirname(ancestor);if(parent===ancestor)throw error;ancestor=parent;}}}
 private async finishRecording(){if(!this.recording?.approved)return;const projection={version:1,inspectionId:this.report.id,events:this.report.events,observations:this.recording.includeObservations?this.report.observations:[],artifacts:this.report.artifacts,annotations:this.report.annotations??[],downloads:this.report.downloads??[],diagnostics:this.report.diagnostics,status:this.report.status};const bytes=Buffer.from(JSON.stringify(projection));if(this.bytes+bytes.length>DEFAULT_LIMITS.artifactBytes)throw new Error('Recording artifact budget exhausted');const path=randomUUID()+'.json';await this.artifactContainment();await writeFile(join(this.artifactDirectory,path),bytes,{mode:0o600,flag:'wx'});this.bytes+=bytes.length;this.report.recording={path,sha256:createHash('sha256').update(bytes).digest('hex'),size:bytes.length,rawPlaywright:false};}
 /** Trusted embedded viewer verification uses a separate context and enforcing proxy. Target app contexts still block service workers. */
 async verifyTraceViewer(url:string){const parsed=new URL(url);if(parsed.protocol!=='http:'||parsed.hostname!=='127.0.0.1'||!/^\/[a-f0-9-]+\/index\.html$/.test(parsed.pathname))throw new Error('Expected owned local viewer URL');const remoteRequests:string[]=[];const proxy=await createPolicyProxy(value=>new URL(value).origin===parsed.origin,value=>remoteRequests.push(value));let browser:Browser|undefined;try{browser=await chromium.launch({headless:true,proxy:{server:proxy.url},args:['--proxy-bypass-list=<-loopback>']});const context=await browser.newContext({serviceWorkers:'allow'});await context.route('**/*',async route=>{if(new URL(route.request().url()).origin!==parsed.origin){remoteRequests.push(route.request().url());await route.abort();}else await route.continue();});const page=await context.newPage();await page.goto(url);await page.getByText('Frame.click',{exact:false}).first().waitFor({timeout:15000});const frame=page.locator('.film-strip-frame').first();await frame.waitFor({state:'visible',timeout:15000});const framesVisible=await frame.evaluate(async element=>{const value=getComputedStyle(element).backgroundImage;const url=value.match(/^url\(["']?(.*?)["']?\)$/)?.[1];if(!url)return false;const image=new Image();image.src=url;await image.decode();return image.naturalWidth>0&&image.naturalHeight>0;});return {actionsVisible:true,framesVisible,remoteRequests};}finally{await browser?.close();await proxy.stop();}}
 private async videoFrame(){if(!this.video||!this.page)return;const mask=this.page.frames().flatMap(frame=>[frame.locator('input,textarea,select,[data-mavona-private]'),...this.selectors.map(selector=>frame.locator(selector)),...this.secrets.filter(Boolean).map(secret=>frame.getByText(secret,{exact:false}))]);this.video.add(await this.page.screenshot({type:'jpeg',quality:80,animations:'disabled',mask}));}
 private close():Promise<void>{if(this.closing)return this.closing;this.closing=(async()=>{try{if(this.video){const video=this.video;this.video=undefined;await this.artifactContainment();this.report.video=await video.finish(this.artifactDirectory,DEFAULT_LIMITS.artifactBytes-this.bytes);if(this.report.video.status==='passed')this.bytes+=this.report.video.size;}if(this.trace){const trace=this.trace;this.trace=undefined;await this.artifactContainment();this.report.trace=await trace.finish(this.artifactDirectory,DEFAULT_LIMITS.artifactBytes-this.bytes);if(this.report.trace.status==='passed')this.bytes+=this.report.trace.size;}}finally{await this.context?.close().catch(()=>{});await this.browser?.close().catch(()=>{});this.context=undefined;this.browser=undefined;this.page=undefined;await this.proxy?.stop();this.proxy=undefined;}})().finally(()=>{this.closing=undefined;});return this.closing;}
 async stop(cancelled=true){if(cancelled){this.cancelled=true;this.report.state='cancelled';this.report.status='unknown';}await this.close();return this.snapshot();}
 snapshot():Report{this.report.surfaces=[...this.pages].flatMap(([pageId,page])=>[...this.frameIds].filter(([frame])=>frame.page()===page).map(([frame,frameId])=>({pageId,frameId,url:this.url(frame.url()),closed:page.isClosed()||frame.isDetached(),mainFrame:frame===page.mainFrame()})));return structuredClone(this.report);}
 private async record(event:InspectionEvent){this.report.events.push(event);await this.eventSink?.(structuredClone(event));}
 async run(input:Flow,grant?:Grant,options:Parameters<InspectionService['start']>[2]={}):Promise<Report>{await this.start(input,grant,options);if(!this.page){for(const step of this.flow!.steps)if(step.op==='assert')this.report.checks.push({id:step.id,status:'unknown',required:step.required,provenance:step.provenance,detail:'Not run; inspection unavailable or unapproved'});return this.snapshot();}try{for(const step of this.flow!.steps){this.authorized();const stepId=randomUUID(),begin=Date.now();const event:InspectionEvent={version:1,id:randomUUID(),inspectionId:this.report.id,stepId,phase:'intent',operation:step.op,...(step.op==='act'?{action:step.action}:{}),status:'unknown',timestamp:new Date().toISOString()};await this.record(event);if(step.op==='observe')await this.observe();else if(step.op==='act'){if(step.locator)await this.target(step.locator).waitFor({state:'attached'});const observation=await this.observe();try{await this.act({...step,revision:observation.revision});}catch(error){if(!(error instanceof Error)||!error.message.startsWith('Stale observation'))throw error;const fresh=await this.observe();await this.act({...step,revision:fresh.revision});}}else if(step.op==='capture')await this.capture(step);else await this.assert(step);await this.videoFrame();await this.record({...event,id:randomUUID(),phase:'result',status:step.op==='assert'?this.report.checks.at(-1)!.status:'passed',timestamp:new Date().toISOString(),durationMs:Date.now()-begin});}this.report.status=aggregateChecks(this.report.checks.filter(c=>c.required));this.report.state=this.cancelled?'cancelled':'completed';}catch(error){this.report.reason=this.sanitize(String(error));this.report.state=this.cancelled?'cancelled':'failed';this.report.status='unknown';}finally{for(const step of this.flow!.steps)if(step.op==='assert'&&!this.report.checks.some(c=>c.id===step.id))this.report.checks.push({id:step.id,status:'unknown',required:step.required,provenance:step.provenance,detail:'Not run; interrupted or unavailable'});if(this.report.checks.some(c=>c.required&&c.status==='failed'))this.report.status='failed';try{await this.finishRecording();}catch(error){this.report.reason=this.sanitize(String(error));if(this.report.status==='passed')this.report.status='unknown';}finally{await this.close();}}return this.snapshot();}
}
