declare module '*codeMirrorModule-BbkfBe3n.js' {const path:string;export default path;}
declare module '*defaultSettingsView-Ds6CBOo0.js' {const path:string;export default path;}
declare module '*urlMatch-L3liM589.js' {const path:string;export default path;}
declare module '*xtermModule-DywYcAf8.js' {const path:string;export default path;}
declare module '*codeMirrorModule.-QdMvsKi.css' {const path:string;export default path;}
declare module '*codicon.DCmgc-ay.ttf' {const path:string;export default path;}
declare module '*defaultSettingsView.Bqk9acqE.css' {const path:string;export default path;}
declare module '*index.B4cLoZK3.js' {const path:string;export default path;}
declare module '*index.B_TqY17P.css' {const path:string;export default path;}
declare module '*index.html' {const path:string;export default path;}
declare module '*manifest.webmanifest' {const path:string;export default path;}
declare module '*playwright-logo.svg' {const path:string;export default path;}
declare module '*snapshot.B_Jk1wbt.js' {const path:string;export default path;}
declare module '*snapshot.html' {const path:string;export default path;}
declare module '*sw.bundle.js' {const path:string;export default path;}
declare module '*uiMode.CU5KtEkS.js' {const path:string;export default path;}
declare module '*uiMode.CyMfwkXJ.css' {const path:string;export default path;}
declare module '*uiMode.html' {const path:string;export default path;}
declare module '*xtermModule.kHJ-D0s7.css' {const path:string;export default path;}
declare module '*playwright-core/LICENSE' {const path:string;export default path;}
declare module '*playwright-core/NOTICE' {const path:string;export default path;}
