import {randomUUID} from 'node:crypto';
import {open,mkdtemp,writeFile,rm} from 'node:fs/promises';import {constants} from 'node:fs';
import {tmpdir} from 'node:os';import {join} from 'node:path';
import {viewerAssets} from './viewer-assets';
import {validateTraceArchive} from './trace';
/** Serves a single immutable trace and pinned upstream assets; no filesystem URL API exists. */
export async function startTraceViewer(path:string){
 const handle=await open(path,constants.O_RDONLY|constants.O_NOFOLLOW);let trace:Buffer;
 try{const metadata=await handle.stat();if(!metadata.isFile()||metadata.nlink!==1||metadata.size>64*1024*1024)throw new Error('Trace file exceeds replay policy');const bytes=Buffer.alloc(metadata.size+1);let length=0;while(length<bytes.length){const read=await handle.read(bytes,length,bytes.length-length,null);if(!read.bytesRead)break;length+=read.bytesRead;}if(length!==metadata.size)throw new Error('Trace changed while reading');trace=bytes.subarray(0,length);const after=await handle.stat();if(after.size!==metadata.size||after.mtimeMs!==metadata.mtimeMs||after.ctimeMs!==metadata.ctimeMs)throw new Error('Trace changed while loading');}finally{await handle.close();}
 const temporary=await mkdtemp(join(tmpdir(),'mavona-trace-replay-'));try{const snapshot=join(temporary,'trace.zip');await writeFile(snapshot,trace,{mode:0o600,flag:'wx'});await validateTraceArchive(snapshot);}finally{await rm(temporary,{recursive:true,force:true});}
 const prefix='/'+randomUUID()+'/';let origin='';
 const headers={'Content-Security-Policy':"default-src 'none'; script-src 'self' 'unsafe-inline'; worker-src 'self' blob:; connect-src 'self' blob:; img-src 'self' data: blob:; media-src 'self' blob:; style-src 'self' 'unsafe-inline'; font-src 'self'; frame-src 'self' blob:; manifest-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'",'X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Cache-Control':'no-store'};
 const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(request){const url=new URL(request.url);if(request.headers.get('host')!==new URL(origin).host||request.headers.get('origin')&&request.headers.get('origin')!==origin)return new Response('Forbidden',{status:403,headers});if(!['GET','HEAD'].includes(request.method))return new Response('Method not allowed',{status:405,headers});if(!url.pathname.startsWith(prefix))return new Response('Not found',{status:404,headers});const name=url.pathname.slice(prefix.length);if(name==='trace.zip')return new Response(request.method==='HEAD'?null:new Uint8Array(trace),{headers:{...headers,'Content-Type':'application/zip'}});const asset=viewerAssets.get(name);if(!asset)return new Response('Not found',{status:404,headers});const type=name==='LICENSE'||name==='NOTICE'?'text/plain':name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':name.endsWith('.html')?'text/html':name.endsWith('.svg')?'image/svg+xml':name.endsWith('.ttf')?'font/ttf':'application/json';return new Response(request.method==='HEAD'?null:Bun.file(asset),{headers:{...headers,'Content-Type':type}});}});origin=server.url.origin;const url=origin+prefix+'index.html?trace='+encodeURIComponent(origin+prefix+'trace.zip');return {url,stop:()=>server.stop(true)};
}
