import {mkdtemp,mkdir,writeFile,rm,realpath} from 'node:fs/promises';import {tmpdir} from 'node:os';import {dirname,join} from 'node:path';import {digest} from '../packages/tools/source';import type {ParityCase} from './corpus';
export const baselineCommit='fdee1136acd7863885ed20c6760f61674f7e32c5';
export const fixtureDigest=(item:ParityCase)=>digest(JSON.stringify(item));
export async function materialize(item:ParityCase){const temporary=await mkdtemp(join(tmpdir(),'mavona-parity-'));const root=await realpath(temporary);const run=async(argv:string[])=>{const child=Bun.spawn(argv,{env:{PATH:process.env.PATH??'/usr/bin:/bin',GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:'/dev/null',GIT_AUTHOR_NAME:'Mavona fixture',GIT_AUTHOR_EMAIL:'fixture@mavona.test',GIT_COMMITTER_NAME:'Mavona fixture',GIT_COMMITTER_EMAIL:'fixture@mavona.test',GIT_AUTHOR_DATE:'2000-01-01T00:00:00Z',GIT_COMMITTER_DATE:'2000-01-01T00:00:00Z'},stdout:'pipe',stderr:'pipe'});const stderr=await new Response(child.stderr).text();if(await child.exited!==0)throw new Error(stderr);};
 try{for(const [path,text] of Object.entries(item.files)){await mkdir(dirname(join(root,path)),{recursive:true});await writeFile(join(root,path),text);}if(item.git!==false){await run(['git','init','-q','--initial-branch','fixture',root]);for(const path of Object.keys(item.files).filter(path=>!item.untracked?.includes(path)))await run(['git','-C',root,'add','--',path]);await run(['git','-C',root,'-c','core.hooksPath=/dev/null','commit','-qm','Frozen parity fixture']);}for(const [path,text] of Object.entries(item.dirty??{}))await writeFile(join(root,path),text);return {root,requested:join(root,item.requested??'.'),close:()=>rm(root,{recursive:true,force:true})};}catch(error){await rm(root,{recursive:true,force:true});throw error;}
}
/** v1 normalizer: key order only; arrays retain their semantic order. Times/opaque IDs map to labelled tokens. */
export function normalizeV1(value:unknown,root:string):unknown {const ids=new Map<string,string>();const walk=(item:unknown,key=''):unknown=>{
 if(typeof item==='string'){if(['id','session_id','task_id','evidence_id','created_at'].includes(key)){let token=ids.get(item);if(!token){token='<'+key.toUpperCase()+'_'+ids.size+'>';ids.set(item,token);}return token;}return item.replaceAll(root,'<FIXTURE_ROOT>');}
 if(Array.isArray(item))return item.map(child=>walk(child));if(item&&typeof item==='object')return Object.fromEntries(Object.entries(item).sort(([a],[b])=>a<b?-1:1).map(([name,child])=>[name,name==='timing'?'<VOLATILE_MEASUREMENT>':walk(child,name)]));return item;
 };return walk(value);}
