import {realpath} from 'node:fs/promises';import {resolve,relative} from 'node:path';import {createHash} from 'node:crypto';
import {excluded,isWithin,digest,type SourceSnapshot} from './source';
async function git(root:string,args:string[],limit:number){
 const child=Bun.spawn(['git','--no-pager','-c','core.fsmonitor=false','-c','core.hooksPath=/dev/null','-c','protocol.allow=never',...args],{cwd:root,env:{PATH:process.env.PATH??'/usr/bin:/bin',GIT_CONFIG_GLOBAL:'/dev/null',GIT_CONFIG_NOSYSTEM:'1',GIT_NO_REPLACE_OBJECTS:'1',GIT_NO_LAZY_FETCH:'1',GIT_LITERAL_PATHSPECS:'1',GIT_OPTIONAL_LOCKS:'0',GIT_TERMINAL_PROMPT:'0'},stdout:'pipe',stderr:'ignore'});const timer=setTimeout(()=>child.kill(9),3000),reader=child.stdout.getReader();let size=0;const chunks:Uint8Array[]=[];
 try{for(;;){const part=await reader.read();if(part.done)break;size+=part.value.length;if(size>limit){child.kill(9);throw new Error('Historical source output budget');}chunks.push(part.value);}if(await child.exited!==0)throw new Error('Historical Git source unavailable');return Buffer.concat(chunks);}
 finally{clearTimeout(timer);await reader.cancel();if(child.exitCode===null)child.kill(9);await child.exited;}
}
export async function readCommittedSource(repository:string,path:string,revision:string):Promise<SourceSnapshot>{
 if(revision!=='HEAD'&&!/^(?:[a-f0-9]{40}|[a-f0-9]{64})$/.test(revision))throw new Error('Use HEAD or a full commit ID');const root=await realpath(repository),target=resolve(root,path);if(!path||path.length>4096||path.includes('\0')||!isWithin(root,target)||relative(root,target)!==path||excluded(path))throw new Error('Historical source path outside or excluded');const checkout=await realpath((await git(root,['rev-parse','--show-toplevel'],8192)).toString('utf8').trim());if(!isWithin(checkout,root))throw new Error('Historical checkout mismatch');const commit=(await git(root,['rev-parse','--verify','--end-of-options',revision+'^{commit}'],256)).toString('ascii').trim();if(!/^(?:[a-f0-9]{40}|[a-f0-9]{64})$/.test(commit))throw new Error('Invalid resolved commit');
 const treePath=relative(checkout,target);const entry=await git(checkout,['ls-tree','-z','--full-tree',commit,'--',treePath],8192);const parts=entry.toString('utf8').split('\0').filter(Boolean);if(parts.length!==1)throw new Error('Historical source missing or ambiguous');const match=/^(100644|100755) blob ([a-f0-9]{40}|[a-f0-9]{64})\t([\s\S]+)$/.exec(parts[0]!);if(!match||match[3]!==treePath)throw new Error('Historical source must be a regular blob');const oid=match[2]!;const size=Number((await git(checkout,['cat-file','-s',oid],128)).toString('ascii').trim());if(!Number.isSafeInteger(size)||size<0||size>1024*1024)throw new Error('Historical source byte budget');const bytes=await git(checkout,['cat-file','blob',oid],1024*1024);if(bytes.length!==size||createHash(oid.length===64?'sha256':'sha1').update(Buffer.from('blob '+size+'\0')).update(bytes).digest('hex')!==oid||await realpath(repository)!==root)throw new Error('Historical blob or checkout changed');if(bytes.includes(0))throw new Error('Historical source is binary');const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);return {path,text,digest:digest(bytes),revision:`commit:${commit}`,lineCount:text.split('\n').length};
}
